\documentclass[12pt, a4paper]{article}\usepackage[]{graphicx}\usepackage[]{color}
%% maxwidth is the original width if it is less than linewidth
%% otherwise use linewidth (to make sure the graphics do not exceed the margin)
\makeatletter
\def\maxwidth{ %
  \ifdim\Gin@nat@width>\linewidth
    \linewidth
  \else
    \Gin@nat@width
  \fi
}
\makeatother

\definecolor{fgcolor}{rgb}{0.345, 0.345, 0.345}
\newcommand{\hlnum}[1]{\textcolor[rgb]{0.686,0.059,0.569}{#1}}%
\newcommand{\hlstr}[1]{\textcolor[rgb]{0.192,0.494,0.8}{#1}}%
\newcommand{\hlcom}[1]{\textcolor[rgb]{0.678,0.584,0.686}{\textit{#1}}}%
\newcommand{\hlopt}[1]{\textcolor[rgb]{0,0,0}{#1}}%
\newcommand{\hlstd}[1]{\textcolor[rgb]{0.345,0.345,0.345}{#1}}%
\newcommand{\hlkwa}[1]{\textcolor[rgb]{0.161,0.373,0.58}{\textbf{#1}}}%
\newcommand{\hlkwb}[1]{\textcolor[rgb]{0.69,0.353,0.396}{#1}}%
\newcommand{\hlkwc}[1]{\textcolor[rgb]{0.333,0.667,0.333}{#1}}%
\newcommand{\hlkwd}[1]{\textcolor[rgb]{0.737,0.353,0.396}{\textbf{#1}}}%
\let\hlipl\hlkwb

\usepackage{framed}
\makeatletter
\newenvironment{kframe}{%
 \def\at@end@of@kframe{}%
 \ifinner\ifhmode%
  \def\at@end@of@kframe{\end{minipage}}%
  \begin{minipage}{\columnwidth}%
 \fi\fi%
 \def\FrameCommand##1{\hskip\@totalleftmargin \hskip-\fboxsep
 \colorbox{shadecolor}{##1}\hskip-\fboxsep
     % There is no \\@totalrightmargin, so:
     \hskip-\linewidth \hskip-\@totalleftmargin \hskip\columnwidth}%
 \MakeFramed {\advance\hsize-\width
   \@totalleftmargin\z@ \linewidth\hsize
   \@setminipage}}%
 {\par\unskip\endMakeFramed%
 \at@end@of@kframe}
\makeatother

\definecolor{shadecolor}{rgb}{.97, .97, .97}
\definecolor{messagecolor}{rgb}{0, 0, 0}
\definecolor{warningcolor}{rgb}{1, 0, 1}
\definecolor{errorcolor}{rgb}{1, 0, 0}
\newenvironment{knitrout}{}{} % an empty environment to be redefined in TeX

\usepackage{alltt}

%\usepackage[pdf]{pstricks} % to use QR barcodes
%\usepackage{pst-barcode}
% sudo yum install texlive-auto-pst-pdf
% sudo yum install texlive-pst-barcode texlive-pdfcrop

% RNW RNW RNW RNW RNW RNW RNW RNW RNW RNW RNW RNW RNW RNW RNW RNW RNW RNW RNW RNW RNW RNW RNW RNW RNW RNW RNW RNW




\usepackage{fontspec}
\usepackage{polyglossia}

\setmainlanguage{russian}
\setotherlanguages{english}

% download "Linux Libertine" OTF-fonts:
% http://www.linuxlibertine.org/index.php?id=91&L=1
\setmainfont{Linux Libertine O} % or Helvetica, Arial, Cambria
% why do we need \newfontfamily:
% http://tex.stackexchange.com/questions/91507/
\newfontfamily{\cyrillicfonttt}{Linux Libertine O}
\newfontfamily{\cyrillicfont}{Linux Libertine O}
\newfontfamily{\cyrillicfontsf}{Linux Libertine O}

\usepackage{etoolbox} % to use ifdef, must be after babel
\input{title_bor_utf8} % use local copy

\usepackage{epigraph}

\AddEnumerateCounter{\asbuk}{\russian@alph}{щ} % для списков с русскими буквами
\setlist[enumerate, 2]{label=\asbuk*),ref=\asbuk*}


\unitlength=0.6mm

\title{Подборка экзаменов по теории вероятностей. \\Факультет экономики, НИУ-ВШЭ}
\date{\today}
\author{Коллектив кафедры \\
математической экономики и эконометрики,\\
 фольклор}


%%%%%%%%%%%%%%%%%% вставки
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% Списки без уродских отступов
\newenvironment{enumerate*}{
\begin{enumerate}
  \setlength{\itemsep}{0pt}
  \setlength{\parskip}{0pt}
  \setlength{\parsep}{0pt}
}{\end{enumerate}}

\newenvironment{itemize*}{
\begin{itemize}
  \setlength{\itemsep}{0pt}
  \setlength{\parskip}{0pt}
  \setlength{\parsep}{0pt}
}{\end{itemize}}

\abovedisplayskip=0mm
\abovedisplayshortskip=0mm
\belowdisplayskip=0mm
\belowdisplayshortskip=0mm
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\newcommand{\MIN}{\textbf{(MIN)}{}}
\newcommand{\ofbr}[1]{\bigl( \{ #1 \} \bigr)}     % Например, вероятность события. Большие круглые, нормальные фигурные скобки вокруг аргумента
%%%%%%%%%%%%%%%%%
\newenvironment{centered}{%
  \begin{list}{}{%
    \topsep0pt
  }
  \centering
  \item[]
}
{\end{list}}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%




\DeclareMathOperator*\plim{plim}
\newcommand{\cN}{\mathcal{N}}
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\begin{document}
\maketitle

\tableofcontents{}


\parindent=0 pt % no indent

\section{Описание}

Свежую версию можно скачать с блога \url{http://pokrovka11.wordpress.com/} или с github репозитория \url{http://bdemeshev.github.io/pr201/}.


Уникальное предложение для студентов факультета экономики ГУ-ВШЭ:


Найдите ошибки в этом документе или пришлите отсутствующие решения в техе и получите дополнительные бонусы! Найденные смысловые ошибки поощряются сильнее, чем просто опечатки. Замеченные ошибки и новые решения оформляйте в виде issues на \url{https://github.com/bdemeshev/probability_hse_exams/issues/}. Перед публикацией issue, пожалуйста, свертесь со свежей версией подборки.

Неполный список благодарностей:

\begin{enumerate}
\item Андрей Зубанов, решения (экзамен 26.03.2012, \ldots)
\item Кирилл Пономарёв, решения (контрольная 1, 2014)
\item Александр Левкун, решения (контрольная 1, 2014)
\item Оля Гнилова, решения (кр 3 2011, 2014, 2015, 2016)
\end{enumerate}


\section{Доброе напутствие пишущим эту подборку :)}

Здесь перечислены стилевые особенности коллекции, а узнать технические подробности по теху можно, например, \href{http://www.ccas.ru/voron/download/voron05latex.pdf}{в учебнике} К.В. Воронцова.

\begin{enumerate}

\item Дробную часть числа отделяй от целой точкой: $3.14$ — хорошо, $3{,}14$ — плохо.
\item Существует длинное тире, —, которое отличается от просто дефиса - и нужно, чтобы разделять части предложения. \href{https://ru.wikihow.com/напечатать-тире}{Инструкция в картинках по набору тире :)}
\item Выключные формулы следует окружать \verb|\[|\ldots\verb|\]|. Никаких \$\$\ldots\$\$!
\item Про остальные окружения: для системы уравнений подойдёт cases, для формул на несколько строк – multline*, для нумерации – enumerate.
\item Русский текст внутри формулы нужно писать в \verb|\text{|\ldots\}.
\item Для многоточий существует команда \verb|\ldots|.
\item В преамбуле определены сокращения! Самые популярные: \verb|\P, \E, \Var, \Cov, \Corr, \cN|.
\item Названия функций тоже идут со слэшем: \verb|\ln, \exp, \cos|\ldots
\item Таблицы нужно оформлять по стандарту booktabs. Самый удобный способ сделать это – зайти на
\href{https://www.tablesgenerator.com}{tablesgenerator} и выбрать там опцию booktabs table style вместо default table style.
\item Уважай букву ё – ставь над ней точки! :)
\end{enumerate}


\section{2004-2005}

\input{chapters/year_2004_2005.tex}

\section{2005-2006}

\input{chapters/year_2005_2006.tex}

\section{2006-2007}

\input{chapters/year_2006_2007.tex}

\section{2007-2008}

\input{chapters/year_2007_2008.tex}

\section{2008-2009}

\input{chapters/year_2008_2009.tex}

\section{2009-2010}

\input{chapters/year_2009_2010.tex}

\section{2010-2011}

\input{chapters/year_2010_2011.tex}

\section{2011-2012}

\input{chapters/year_2011_2012.tex}

\section{2012-2013}

\subsection{Контрольная работа №1, 14.11.2012}


%Теория вероятностей и математическая статистика. Контрольная работа 1, 14.11.12.

%\vspace{20pt}
%Обозначения: $\E(X)$ — математическое ожидание, $\Var(X)$ — дисперсия

\vspace{20pt}
14 ноября 1936 года в СССР была создана Гидрометеорологическая служба.
\vspace{20pt}

\begin{enumerate}

\item Погода завтра может быть ясной с вероятностью $0.3$ и пасмурной с вероятностью $0.7$. Вне зависимости от того, какая будет погода, Маша даёт верный прогноз с вероятностью $0.8$. Вовочка, не разбираясь в погоде, делает свой прогноз по принципу: с вероятностью $0.9$ копирует Машин прогноз, и с вероятностью $0.1$ меняет его на противоположный.
\begin{enumerate}
\item Какова вероятность того, что Маша спрогнозирует ясный день?
\item Какова вероятность того, что Машин и Вовочкин прогнозы совпадут?
\item Какова вероятность того, что день будет ясный, если Маша спрогнозировала ясный?
\item Какова вероятность того, что день будет ясный, если Вовочка спрогнозировал ясный?
\end{enumerate}

\item Машин результат за контрольную, $M$, равномерно распределен на отрезке $[0;1]$. Вовочка ничего не знает, поэтому списывает у Маши, да ещё может наделать ошибок при списывании. Поэтому Вовочкин результат, $V$, распределен равномерно от нуля до Машиного результата.
\begin{enumerate}
\item Найдите $\P(M>2V)$, $\P(M>V+0.1)$
\item Зачёт получают те, чей результат больше $0.4$. Какова вероятность того, что Вовочка получит зачёт? Какова вероятность того, что Вовочка получит зачёт, если Маша получила зачёт?
\end{enumerate}
Подсказка: попробуйте нарисовать нужные события в осях $(V,M)$

Это была задачка-неберучка!

\item Функция плотности случайной величины $X$ имеет вид $f(x)=\left\{\begin{array}{l}
\frac{3}{7}x^2,\, x\in[1;2] \\
0,\, x\notin [1,2]
\end{array}\right.$
\begin{enumerate}
\item Не производя вычислений найдите $\int_{-\infty}^{+\infty}f(x)\,dx$
\item Найдите $\E(X)$, $\E(X^2)$ и дисперсию $\Var(X)$
\item Найдите $\P(X>1.5)$
\item Найдите функцию распределения $F(x)$ и постройте её график
\end{enumerate}

\item Совместное распределение случайных величин $X$ и $Y$ задано таблицей

\begin{tabular}{@{}c|ccc@{}}
\toprule
      & $X=-2$ & $X=0$ & $X=2$ \\ \midrule
$Y=1$ & $0.2$  & $0.3$ & $0.1$ \\
$Y=2$ & $0.1$  & $0.2$ & $a$   \\ \bottomrule
\end{tabular}

\begin{enumerate}
\item Определите неизвестную вероятность $a$.
\item Найдите вероятности $\P(X>-1)$, $\P(X>Y)$
\item Найдите математические ожидания $\E(X)$, $\E(X^2)$
\item Найдите корреляцию $\Corr(X,Y)$
\end{enumerate}

\item Винни Пух собрался полакомиться медом, но ему необходимо принять решение, к каким пчелам отправиться за медом. Неправильные пчелы кусают каждого, кто лезет к ним на дерево с вероятностью 0.9, но их всего 10 штук. Правильные пчелы кусаются с вероятностью 0.1, но их 100 штук.
\begin{enumerate}
\item  Определите математическое ожидание и дисперсию числа укусов Винни Пуха для каждого случая
\item Определите наиболее вероятное число укусов и его вероятность для каждого случая
\item К каким пчелам следует отправиться Винни Пуху, если он не может выдержать больше двух укусов?
\end{enumerate}
\end{enumerate}



\subsection{Контрольная работа №1, 14.11.2012, решения}

\begin{enumerate}
\item
\begin{enumerate}
\item $\P(A)=0.8\cdot 0.3+0.7\cdot 0.2=0.38$
\item $\P(B)=0.9$
\item $\P(C|A)=\frac{0.3\cdot 0.8}{0.38}=0.632$
\item $\P(C|D)=\frac{0.3\cdot (0.9\cdot 0.8+0.1\cdot 0.2)}{0.9\cdot 0.38+0.1\cdot (1-0.38)}=0.55$
\end{enumerate}
\item Это была задачка-неберучка!
\item
\begin{enumerate}
\item $1$
\item $\E(X)=45/28\approx 1.61$, $\E(X^2)=93/35\approx 2.66$, $\Var(X)=291/3920\approx 0.07$
\item $37/56\approx 0.66$
\item $F(x)=\begin{cases} 0,\, x<1 \\
\frac{x^3-1}{7},\, x\in [1;2] \\
1,\, x>1 \end{cases}$
\end{enumerate}
\item
\begin{enumerate}
\item $a=0.1$
\item $\P(X>-1)=0.7$, $\P(X>Y)=0.1$
\item $\E(X)=-0.2$, $\E(X^2)=2$
\item $\Corr(X,Y)=0.117$
\end{enumerate}
\item
\begin{enumerate}
\item Правильные: $\E(X)=10$, $\Var(X)=9$, Неправильные: $\E(Y)=9$, $\Var(Y)=0.9$
\item Наиболее вероятное число укусов равно математическому ожиданию
\item Лучше идти к неправильным пчёлам, так как $\P(X\leq 2)<\P(Y\leq 2)$.
\end{enumerate}
\end{enumerate}


\subsection{Контрольная работа №2, 26.12.2012}

Тест:

\begin{enumerate}
\item Зная распределение компонент случайного вектора всегда можно восстановить их совместное распределение. Да. Нет.
\item Пусть $X$ — длина наугад выловленного удава в сантиметрах, а $Y$ — в дециметрах. Коэффициент корреляции между этими величинами равен 0.1. Да. Нет.
\item Для любой случайной величины $X$ справедливо неравенство
\[ \P(|X-\E(X)|>2\sqrt{\Var(X)})\leq 1/4 \]
Да. Нет.
\item Сумма независимых нормальных случайных величин нормальна. Да. Нет.
\item  Сумма $n$ независимых равномерно распределенных на интервале $(0,1)$ случайных величин асимптотически нормальна. Да. Нет.
\item Квадрат стандартной нормальной случайной величины имеет хи-квадрат распределение. Да. Нет.
\item Если ковариация компонент случайного двумерного нормального вектора равна нулю, то они независимы. Да. Нет.
\item Условная дисперсия всегда больше безусловной. Да. Нет.
\item Элементы выборки без возвращения из конечной генеральной совокупности независимы. Да. Нет.
\item Математическое ожидание выборочного среднего одинаково распределенных случайных величин не зависит от объема выборки. Да. Нет.
\item Конец света по техническим причинам переносится на показ работ по теории вероятности. Да. Может быть.
\end{enumerate}

Ответы: Нет, Нет, Да, Да, Да, Да, Да, Нет, Нет (зависимы), Да (не зависит), Любой верный

Задачи:
\begin{enumerate}
\item Купчиха Сосипатра Титовна очень любит чаёвничать. Её чаепитие продолжается случайное время $S$, имеющее равномерное распределение от 0 до 3 часов.  Встретив Сосипатру Титовну в пассаже на Петровке, её подруга Олимпиада Карповна узнала, сколько длилось вчерашнее чаепитие Сосипатры Титовны. Решив, что такая продолжительность чаепития является максимально возможной, Олимпиада Карповна устраивает чаепитие, продолжающееся случайное время $T$, имеющее равномерное распределение от 0 до $S$ часов.
\begin{enumerate}
\item Найдите совместную функцию плотности величин $S$ и $T$
\item Найдите вероятность $\P(S>T)$
\item Найдите $\E(T^2)$
\end{enumerate}

\item  Для случайно выбранного домохозяйства случайные величины $X$ и $Y$ принимают значения, равные доле расходов на продукты питания и алкоголь плюс табак соответственно. Случайный вектор $(X,Y)^T$  хорошо описывается двумерным нормальным законом распределения с математическим ожиданием $(0.45, 0.16)^T$ и ковариационной матрицей
\[
C=0.144\cdot
\left(\begin{array}{cc}
1 & -0.9 \\
-0.9 & 1
\end{array}\right)
\]
Найдите:
\begin{enumerate}
\item Вероятность того, что домохозяйство тратит более половины своих доходов на питание.
\item Вероятность того, что домохозяйство тратит более половины своих доходов на алкогольную и табачную продукцию и продукты питания.
\item Ожидаемую долю расходов на алкоголь и табак для домохозяйства, которое тратит на питание четверть своих доходов.
\item Вероятность того, что домохозяйство из предыдущего пункта тратит более трети своих доходов на алкогольную и табачную продукцию.

% из-за коррелированности этот пункт не решается :(
\begin{comment}
\item  Характеристикой отклонения от типичного потребления выступает величина
\[
U=\sqrt{\frac{(X-\E(X))^2}{\Var(X)}+\frac{(Y-\E(Y))^2}{\Var(Y)}}
\]
Найдите $\P(U>3)$.
\end{comment}
\item Для доли расходов на питание вычислите центральный момент 2013-го порядка.

\end{enumerate}




\item Вычислите (или оцените) вероятность того, что по результатам 4000 бросаний симметричной монеты,  частота выпадения герба будет отличаться от 0.5 не более, чем на $0.01$. Решите задачу с помощью неравенства Чебышёва и с помощью ЦПТ.





\item Компания кабельного телевидения НВТ, Новая Вершина Телевидения, анализирует возможность присоединения к своей сети пригородов N-ска. Опросы показали, что в среднем каждые 3 из 10 семей жителей пригородов хотели бы стать абонентами сети. Стоимость работ, необходимых для организации сети в любом пригороде оценивается величиной 2\,080\,000 у.е. При подключении каждого пригорода НВТ надеется получить 1\,000\,000 у.е. в год от рекламодателей. Планируемая чистая прибыль от оплаты за кабельное телевидение одной семьей в год равна 120 у.е.

Каким должно быть минимальное количество семей в пригороде для того, чтобы с вероятностью 0.99 расходы на организацию сети в этом пригороде окупились за год?


\item Оценки за контрольную работу по теории вероятностей 6 случайно выбранных студентов оказались равны:

8 5 6 7 3 9.

\begin{enumerate}
\item Выпишите вариационный ряд
\item Постройте график выборочной функции распределения
\item Вычислите значение выборочного среднего и выборочной дисперсии.
\end{enumerate}
\end{enumerate}

\subsection{Контрольная работа №2, 26.12.2012, решения}
\begin{enumerate}
\item  $f(s,t)=f(s)\cdot f(t|s)=\frac{1}{3s}$ при $0\leq t\leq s\leq 3$. Бонус тем, кто прочитал условие, $\P(S>T)=1$.
\[ \E(T^2)=\int_0^3\int_0^s \frac{t^2}{3s}\,dt\,ds=1 \]
\item
\begin{enumerate}
\item $\P(X>0.5)=\P(Z>0.1317616)\approx 0.4475864$, $\sigma_X\approx 0.3794733$
\item $\P(X+Y>0.5)=
\P(Z>-0.6481812)\approx 0.7415661$,
$\sigma_{X+Y}=0.1697056$, $\E(X+Y)=0.61$

\item $X=0.25$ при нормировке даёт $\tilde{X}=-0.5270463$. Получаем: $\E(\tilde{Y}\mid \tilde{X}=-0.5270463)=0.4743416$,  $\Var(\tilde{Y}\mid \tilde{X}=-0.5270463)=0.19$.

Значит $\E(Y \mid \tilde{X}=-0.5270463)=0.34$,  $\Var(Y\mid \tilde{X}=-0.5270463)=0.02736$.

\item $\P(Y>1/3\mid \tilde{X}=-0.5270463)=\P(Z>-0.0403042)=0.5160747$
\item Ноль
\end{enumerate}
\item $\E(\hat{p})=0.5$, $\Var(\hat{p})=0.25/n=1/16000$. По Чебышёву:
\[
\P(|\hat{p}-0.5|\leq 0.01)\geq 1-\frac{\Var(\hat{p})}{0.01^2}=\ldots=0.375
\]
Используя нормальную аппроксимацию:

\[
\P(|\hat{p}-0.5|\leq 0.01)=\P(|Z|\leq 1.2649111)\approx 0.7940968
\]
\item Обозначим $N$ — количество подключенных абонентов, тогда $N\sim Bin(n,0.3)$. При больших $n$ биномиальное распределение можно заменить на нормальное, $N\sim \cN(0.3n,0.21n)$.

\[ \P(120N>1\,080\,000)=\P(N>9000)=\P\left(Z>\frac{9000-0.3n}{\sqrt{0.21n}}\right)=0.99 \]

Из таблицы находим, что

\[ \frac{9000-0.3n}{\sqrt{0.21n}}=-2.3263479\]



Решаем квадратное уравнение, находим корни, один — отрицательный, другой, $n\approx 30622$.
\item


Вариационный ряд: 3, 5, 6, 7, 8, 9. $\bar{X}\approx 6.3333333$,
$\frac{\sum (X_i-\bar{X})^2}{n-1}\approx 4.6666667$,
$\frac{\sum (X_i-\bar{X})^2}{n}\approx 3.8888889$




\begin{kframe}


{\ttfamily\noindent\bfseries\color{errorcolor}{\#\# Error: Cannot create:\\\#\# 	 R\_plots/empirical\_cdf.tikz \\\#\# Because the directory does not exist or is not writable.}}\end{kframe}
\includegraphics[width=\maxwidth]{figure/empirical_cdf-1} 


\begin{figure}
\begin{tikzpicture}[scale = 0.025]
  \input{R_plots/empirical_cdf.tikz}
\end{tikzpicture}
\end{figure}
\end{enumerate}

\subsection{Демо-версия зачёта}

\begin{enumerate}
\item Двое подельников, Маша и Саша, украли десять миллионов евро. Через некоторое время Саша был найден убитым, а Маша была арестована. Из свидетельских показаний ясно следует, что Маша и Саша ругались по поводу делёжки. Защита и обвинение выясняют, убила ли Маша Сашу. Из статистических данных известно, что:
\begin{enumerate}
\item[A] 20\% подельников-мужчин ругаются по поводу делёжки
\item[B] 20\% оставшихся в живых подельников-мужчин ругаются по поводу делёжки
\item[C] 5\% мужчин убивают
\item[D] 3\% мужчин убивают их подельники
\item[E] 90\% убитых мужчин-подельников ругались по поводу делёжки
\end{enumerate}
Располагая этой информацией,
\begin{enumerate}
\item Найдите вероятность того, что Маша убила Сашу, если известно, что Маша и Саша ругались по поводу делёжки.
\item Найдите вероятность того, что Маша убила Сашу, если известно, что Маша и Саша ругались по поводу делёжки, и Саша был найден убитым.
\end{enumerate}


\item Маша подкидывает 300 игральных кубиков. Те, что выпали не на шестёрку, она перекидывает один раз. Обозначим буквой $N$ количество шестёрок на всех кубиках после возможных перекидываний.
\begin{enumerate}
\item Найдите $\E(N)$, $\Var(N)$
\item Какова примерно вероятность того, величина $N$ лежит от 50 до 70?
\item Укажите любой интервал, в который величина $N$ попадает с вероятностью 0.9
\end{enumerate}

\item На лукоморье набегают волны. Кот Учёный заметил, что размер каждой волны, $X_i$, — случайная величина, имеющая равномерное распределение от 0 до 1, а размеры волн независимы. Кот Учёный считает волну \textit{большой}, если она больше предыдущей и следующей. Случайная величина $R_i$ равна 1, если $i$-ая волна была \textit{большой}, и 0 иначе.
\begin{enumerate}
\item Найдите $\P(R_i=1)$, $\E(X_i)$
\item Найдите $\E(X_i \mid R_i=1)$
\item Найдите $\Cov(R_1,R_2)$, $\Cov(R_1,R_3)$
\end{enumerate}
\item Ермолай Лопахин решил приступить к вырубке вишневого сада. Однако выяснилось, что растут в нём не только вишни, но и яблони. Причём, по словам Любови Андреевны Раневской, среднее количество деревьев (а они периодически погибают от холода или жары, либо из семян вырастают новые) в саду распределено в соответствии с нормальным законом ($X$ — число яблонь, $Y$ — число вишен) со следующими параметрами:
\begin{equation*}
\begin{pmatrix}	X \\ 	Y 	\end{pmatrix}
\sim \mN
\left(
\begin{pmatrix}
25 \\ 125
\end{pmatrix}
;
\begin{pmatrix}
    5 & 4 \\
    4 & 10
    \end{pmatrix}
\right)
\end{equation*}

\begin{enumerate}
\item Найдите вероятность того, что Ермолаю Лопахину придется вырубить более 150~деревьев.
\item Каково ожидаемое число подлежащих вырубке вишен, если известно, что предприимчивый и последовательный Лопахин, не затронув ни одного вишнёвого дерева, начал очистку сада с яблонь и все 35~яблонь уже вырубил? Какова при этом вероятность того, что Лопахину придется вырубить более 100 вишен?
\end{enumerate}

\item Вопрос из интервью в Морган-Стэнли. Есть две независимых равномерных на отрезке $[0;1]$ случайных величины, $X$ и $Y$. Как их нужно преобразовать, чтобы корреляция между ними оказалась равна $\rho$?
\end{enumerate}

\subsection{Зачёт, 15.01.2013}


\begin{enumerate}
\item Самолёт упал либо в горах, либо на равнине. Вероятность того, что самолёт упал в горах, равна 0.75. Для поиска пропавшего самолёта выделено 3 вертолёта. Каждый вертолёт можно использовать только в одном месте. Как распределить имеющиеся вертолёты, если вероятность обнаружения пропавшего самолёта отдельно взятым вертолётом равна $0.6$?

\item Совместная функция плотности величин $X$ и $Y$ имеет вид
\[
f(x,y)=\frac{1}{x}e^{-x},\: \text{при}\: 0<y<x
\]

\begin{enumerate}
\item Найдите $\P\left( \frac{Y}{X}<0.7 \right)$
\item Найдите $\E(X)$
\item Являются ли $X$ и $Y$ независимыми?
\item Как распределена величина $Z=Y/X$?
\end{enumerate}

\item Величины $X_1$, \ldots, $X_n$ независимы и имеют биномиальное распределение, $X_i \sim Bin(10,p)$. Используя неравенство Чебышёва найдите наименьшее число $t$, чтобы выполнялось условие
\[
\P( | \bar{X}-\E(\bar{X}) | \geq t )\leq 0.01
\]



\item Допустим, что срок службы пылесоса имеет экспоненциальное распределение. В среднем один
пылесос бесперебойно работает 10 лет. Завод предоставляет гарантию 7 лет на свои изделия.
Предположим для простоты, что все потребители соблюдают условия гарантии.
\begin{enumerate}
\item Какой процент потребителей в среднем обращается за гарантийным ремонтом?
\item Какова вероятность того, что из 1000 потребителей за гарантийным ремонтом обратится
более 55\% покупателей?
\end{enumerate}
Подсказка: $\ln 2\approx 0.7$

\item Вася попадает мячом в корзину с вероятностью $0.2$, Петя — с вероятностью $0.25$. Каждый из них сделал по 100 бросков мяча.
\begin{enumerate}
\item Какова вероятность того, что Петя попал на 10 раз больше Васи?
\item Какое минимальное количество бросков мяча нужно сделать каждому, чтобы вероятность, того, что Петя попал на 10 раз больше Васи достигла 0.99?
\end{enumerate}
\end{enumerate}

\subsection{КоКо, компьютерная контрольная №3, 13.03.13}

Продолжительность 1 час 10 минут, разрешено пользоваться конспектами, книжками, заготовками программ, нельзя общаться, использовать Интернет. Текст работы в группах с R:

\begin{enumerate}
\item Величины $X$ и $Y$ независимы. Величина $X$ распределена нормально, $X\sim \cN(4.5,6.6)$, величина $Y$ распределена экспоненциально, $Y\sim \exp(\lambda=2.4)$. Используя симуляционный подход примерно посчитайте

\begin{enumerate}
\item $\P(X+Y>5.5)$
\item $\E(X/(X+2Y))$
\item $\Var(XY)$
\item $\Cov(XY,X/Y)$
\end{enumerate}

\item Загрузите данные по стоимости квартир в Москве, \href{http://goo.gl/zL5JQ}{goo.gl/zL5JQ}, в табличку с именем \verb|h|. Обозначим буквой \verb|a| ответ на первый вопрос первой задачи. Отберите индивидуальную выборку лично для себя, выполнив команды:
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{set.seed}\hlstd{(}\hlkwd{round}\hlstd{(}\hlnum{100} \hlopt{*} \hlstd{a))} \hlcom{# здесь "a" — это ответ на первый пункт первой задачи}
\hlstd{h} \hlkwb{<-} \hlstd{h[}\hlkwd{sample}\hlstd{(}\hlnum{1}\hlopt{:}\hlkwd{nrow}\hlstd{(h),} \hlnum{1000}\hlstd{), ]}
\end{alltt}
\end{kframe}
\end{knitrout}

Постройте 90\%-ый доверительный интервал для:
\begin{enumerate}
\item Доли кирпичных домов, \verb|brick==1|
\item Доли кирпичных домов, \verb|brick==1|, среди домов находящихся близко от метро,  \verb|walk==1|
\item Разницы доли кирпичных домов среди домов расположенных близко и далеко от метро
\end{enumerate}


\item Сгенерируйте искусственные данные, выполнив команды:
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{set.seed}\hlstd{(}\hlkwd{round}\hlstd{(}\hlnum{100} \hlopt{*} \hlstd{a)} \hlopt{+} \hlnum{42}\hlstd{)} \hlcom{# здесь "a" — это ответ на первый пункт первой задачи}
\hlstd{x} \hlkwb{<-} \hlkwd{rexp}\hlstd{(}\hlnum{200}\hlstd{,} \hlkwc{rate} \hlstd{=} \hlnum{2}\hlstd{)}
\end{alltt}
\end{kframe}
\end{knitrout}

Величины $X_i$ независимы и имеют функцию плотности $f(x)=e^{b-xe^b}$ при $x>0$.
\begin{enumerate}
\item Оцените неизвестный параметр $b$
\item Оцените дисперсию полученной оценки
\item Постройте 90\%-ый доверительный интервал для $b$
\item Используя результат предыдущего пункта, на 10\%-ом уровне значимости проверьте гипотезу $H_0$: $b=0.7$ против альтернативной гипотезы $H_a$: $b\neq 0.7$.
\end{enumerate}

\end{enumerate}


\subsection{Экзамен, 26.03.2013}


\begin{enumerate}
%в комментариях предполагаемые ответы


\item Вероятность выигрыша по лотерейному билету равна $0.05$. Вероятность того, что из трёх купленных билетов ровно два окажутся выигрышными примерно равна

\otvet{0.002}{0.0025}{0.007}{0.1}{0.3}

\item Закон распределения случайной величины задан табличкой

\begin{tabular}{@{}cccc@{}}
\toprule
$X$         & $-1$  & $0$   & $1$ \\ \midrule
$\P(\cdot)$ & $0.4$ & $0.2$ & ?   \\ \bottomrule
\end{tabular}

Дисперсия величины $X$, $\Var(X)$, равняется

\otvet{0}{0.02}{0.3}{0.8}{2}

%3
\item Если $f(x)$ — функция плотности, то $\int_{-\infty}^{x}f(u)\,du$ равен

\otvet{0}{1}{$\E(X)$}{$\Var(X)$}{$F(x)$}

%4
\item События $A$ и $B$ называются независимыми, если

\lotvet{$\P(A\cup B)=\P(A)+\P(B)$}
{$\P(A)\cdot\P(B)=\P(A\cap B)$}
{$\P(A\cup B)=\P(A)+\P(B)-\P(A\cap B)$}
{$\P(A\cap B)=0$}
{нет верного} \\ \\

%5
\item Правильную монетку подбрасывают два раза. Рассмотрим два события: $A$ — при втором броске выпала «решка», $B$ — «орёл» выпал хотя бы один раз. Найдите $\P(A|B)$

\otvet{0}{1/3}{1/2}{2/3}{1}

%6
\item Есть пять случайных величин: $X\sim \chi^2_{10}$, $Y\sim F_{5,10}$, $T\sim t_{10}$, $Z\sim \cN(0,1)$, $W\sim \cN(10,1)$. Какие из величин распределены симметрично относительно 0?

\otvet {X, Y, Z}{Z, W}{Z, T}{Z}{X, Y}

%7
\item Известно, что $\E(X)=3$, $\Var(X)=1$, $\E(Y)=4$, $\Var(Y)=9$, $\E(XY)=13$, найдите $\Cov(X,Y)$

\otvet{0}{-3}{18}{3}{1}

%8
\item Известно, что $\E(X)=3$, $\Var(X)=1$, $\E(Y)=4$, $\Var(Y)=9$, $\E(XY)=6$, найдите $\Var(2X+Y)$

\otvet{13}{7}{1}{17}{нет верного ответа}

%9
\item Если $F(x)$ — это функция распределения, то $\lim_{x\to -\infty}F(x)$ равен

\otvet{0}{0.5}{1}{$\E(X)$}{$+\infty$}

%10
\item Если $X\sim \cN(-4;1)$, то $\P(3X+571>0)$ примерно равна

\otvet{0}{0.5}{1}{$+\infty$}{нет верного ответа}

%11
\item Про закон распределения величины $X$ ничего не известно. Укажите самую точную оценку сверху для вероятности $\P(|X-\E(X)|>3\sqrt{\Var(X)})$

\otvet{$0.(3)$}{$0.6(3)$}{$0.(1)$}{$1$}{нет верного ответа}

%12
\item Функция распределения, $F(x)=\P(X\leq x)$ может не являться

\otvet{непрерывной}{непрерывной справа}{монотонно неубывающей}{ограниченной}{неотрицательной}

%13
\item Ковариационной может быть матрица:

\otvet {$\left(\begin{array}{cc}
-1 & 1\\
1 & 2
\end{array}\right)$}{$\left(\begin{array}{cc}
1 & 0.5\\
1 & 2
\end{array}\right)$}{$\left(\begin{array}{cc}
1 & -1\\
-1 & 2
\end{array}\right)$}{$\left(\begin{array}{cc}
-1 & 1\\
1 & -2
\end{array}\right)$}{$\left(\begin{array}{cc}
1 & 1\\
-0.7 & 2
\end{array}\right)$}\\

%14
\item Если $X$ и $Y$ независимые случайные величины, то неверным может быть утверждение

\lotvet{$\E(X+Y)=\E(X)+\E(Y)$}
{$\E(X/Y)=\E(X)/\E(Y)$}
{$\E(XY)=\E(X)\cdot\E(Y)$}
{$\Var(X+Y)=\Var(X)+\Var(Y)$}
{$\Cov(X,Y)=0$} \\ \\

%15
\item Известно, что  $\Cov(X,Y)=0$, $\Var(X)=10$, $\Var(Y)=10$. \\
Неверным может быть утверждение

\lotvet{$\Corr(X,Y)=0$}
{$\Corr(X+a,Y+b)=0$}
{$\E(X\cdot Y)=\E(X)\cdot \E(Y)$}
{$\Var(X+Y)=\Var(X)+\Var(Y)$}
{$X$ и $Y$ независимы} \\ \\

%16
\item $Z_1,Z_2,\ldots,Z_n\sim\cN(0,1)$. Тогда величина $\frac{Z_1\sqrt{n-2}}{\sqrt{\sum_{i=3}^n Z_i^2}}$ имеет распределение

\otvet {$\cN(0,1)$}{$t_n$}{$F_{1,n-2}$}{$\chi^2_n$}{$t_{n-2}$}

%17
\item Количество страниц в книгах авторов $X$ и $Y$ распределено нормально с дисперсиями $\sigma^2_X$ и $\sigma^2_Y$ соответственно. Для тестирования гипотезы о равенстве дисперсий было выбрано $n$ книг автора $X$ и $m$ книг — автора $Y$. Какое распределение имеет статистика, используемая в данном случае?

\otvet {$\chi^2_{\min(m,n)}$}{$\chi^2_{\max(m,n)}$}{$F_{m,n}$}{$F_{m-1,n-1}$}{$F_{m+1,n+1}$}

%18
\item Если величина $X$ имеет $\chi^2_k$-распределение, величина $Y$ — $\chi^2_n$-распределение, и они независимы, то дробь $nX/(kY)$ имеет распределение

\otvet{$F_{k,n}$}{$F_{n,k}$}{$F_{k-1,n-1}$}{$\chi^2_{n-k}$}{$F_{n-1,k-1}$}

%19
\item \emph{Смещённой} оценкой математического ожидания по выборке независимых,
одинаково распределенных случайных величин $X_1$, $X_2$, $X_3$ является оценка

\lotvet{$(X_1+X_2)/2$}{$(X_1+X_2+X_3)/3$}{$0.7X_1+0.2X_2+0.1X_3$}{$0.3X_1+0.3X_2+0.3X_3$}{$X_1+X_2-X_3$} \\ \\

%20
\item Если величины $X$ и $Y$ независимы и равномерно распределены на $[0;1]$, а $F(x,y)$ — их совместная функция  распределения, то $F(0.5,3)$ равно

\otvet{0}{0.5}{1}{1.5}{не существует}

%21
\item Если $X_i$ независимы и имеют нормальное распределение $\cN(-1;2013)$, то $\sqrt{n}(1+\bar{X})/\hat{\sigma}$ имеет распределение

\otvet{$\cN(0;1)$}{$t_{n-1}$}{$\chi^2_{n-1}$}{$\cN(0;2013/n)$}{$t_n$}

%22
\item Последовательность оценок $\hat{\theta}_1$, $\hat{\theta}_2$, \ldots называется состоятельной, если

\lotvet{$\E(\hat{\theta}_n)=\theta$}{$\Var(\hat{\theta}_n)\to 0$}{$\P(|\hat{\theta}_n - \theta |>t)\to 0$ для всех $t>0$}{$\E(\hat{\theta}_n)\to \theta$}
{$\Var(\hat{\theta}_n)\geq \Var(\hat{\theta}_{n+1})$} \\ \\

%23
\item Величины $X_1$, \ldots, $X_5$ равномерны на отрезке $[0;a]$. Известно, что $\sum_{i=1}^5 x_i=25$. При использовании первого момента оценка методом моментов неизвестного $a$ равна

\otvet{1}{5}{10}{20}{нет верного ответа}

%24
\item При построении доверительного интервала для отношения дисперсий по двум независимым нормальным выборкам из $n$ наблюдений каждая, используется статистика, имеющая распределение

\otvet{$F_{n-1,n-1}$}{$t_{n-1}$}{$\chi^2_{n-1}$}{$\chi^2_{n}$}{$t_n$}

%25
\item Ботаники\footnote{В отличие от ботаников, зоологи точно знают, сколько иголок у ёжиков!} строят доверительный интервал для математического ожидания числа иголок у ёжа. Количество иголок на одном еже предполагается нормально распределенным. Среднее число иголок у пойманных 100 ёжиков равно 1500, выборочная дисперсия — 400. На 5\% уровне значимости какой примерно доверительный интервал должны построить ботаники?


\lotvet {$[1499;1501]$}{$[1498;1502]$}{$[1497;1503]$}{$[1496;1504]$}{нет верного ответа}\\ \\

%26
\item Функция правдоподобия, построенная по случайной выборке $X_1$, \ldots, $X_n$ из распределения с функцией плотности $f(x)=(\theta+1)x^{\theta}$ при $x\in [0;1]$ имеет вид

\otvet{$(\theta+1)x^{n\theta}$}{$\sum (\theta+1)x_i^{\theta}$}
{$(\theta+1)^{\sum x_i}$}{$(\sum x_i)^{\theta}$}{$(\theta+1)^n\prod x_i^{\theta}$}

%27
\item Если $X_i$ независимы, $\E(X_i)=\mu$ и $\Var(X_i)=\sigma^2$, то математическое ожидание величины $Y=\sum_{i=1}^{n}(X_i-\bar{X})^2$ равно

\otvet{$\hat{\sigma}^2$}{$(n-1)\sigma^2$}{$\mu$}{$\sigma^2$}{$\sigma^{2}/n$}

%28
\item Если $P$-значение меньше уровня значимости $\alpha$, то гипотеза $H_0$: $\sigma=\sigma_0$

\lotvet{отвергается}{не отвергается}{отвергается только если $H_a$: $\sigma \neq \sigma_0$}{отвергается только если $H_a$: $\sigma<\sigma_0$}{недостаточно информации} \\

\item Если $H_0$ верна, то $P$-значение имеет распределение

\otvet{$U[0;1]$}{$\cN(0,1)$}{$t_n$}{$t_{n-1}$}{$\chi^2_{n-1}$}


\end{enumerate}




\textbf{Экзамен по теории вероятностей! Суперигра!}

\vspace{20pt}
\begin{center}
\textbf{DON'T PANIC}
\end{center}
\vspace{20pt}


\begin{enumerate}
\item В группе учится 30 студентов, 20 девушек и 10 юношей. Они входят в аудиторию в случайном порядке. Рассчитайте вероятности событий:
\begin{enumerate}
\item Маша Петрова\footnote{Маша Петрова — единственная и неподражаемая!} войдёт девятой по счёту
\item Девятый вошедший окажется девушкой
\item Перед Машей Петровой войдут ровно 5 юношей
\item Перед Машей Петровой войдут ровно 5 юношей, если известно, что Маша Петрова вошла девятой
\item Маша Петрова войдёт девятой по счёту, если известно, что перед ней вошло ровно 5 юношей
\end{enumerate}

\item В поселке 2500 жителей. Каждый из них в среднем 6 раз в месяц ездит в город, выбирая день поездки независимо от других людей. Поезд ходит в город один раз в сутки.
\begin{enumerate}
\item Какой наименьшей вместимостью должен обладать поезд, чтобы он переполнялся в среднем не чаще 1 раза в 100 дней?
\item Сколько в среднем человек будет ехать в таком поезде, если предположить, что при переполнении часть людей полностью откажется от поездки?
\end{enumerate}

Источник: экзамен РЭШ

\item Случайные величины $X_1$, $X_2$, \ldots, $X_n$ независимы и имеют пуассоновское распределение с неизвестным параметром $\lambda$.
\begin{enumerate}
\item С помощью метода максимального правдоподобия постройте оценки для $\lambda$ и для $\exp(\lambda)$
\item Предположим, что исследователь не знает, чему равны $X_i$. Ему известно лишь, равно ли каждое из $X_i$ нулю или нет. С помощью метода максимального правдоподобия постройте оценки для $\lambda$ и для $\exp(\lambda)$. Всегда ли существуют предложенные оценки?
\end{enumerate}


\item В таблице представлены данные по количеству пассажиров «Титаника», поделенные на группы по классу каюты:

% latex table generated in R 3.4.2 by xtable 1.8-2 package
% Sat Oct 28 20:27:11 2017
\begin{table}[ht]
\centering
\begin{tabular}{rrrr}
  \hline
 & 1 класс & 2 класс & 3 класс \\ 
  \hline
Погиб & 122 & 167 & 528 \\ 
  Выжил & 203 & 118 & 178 \\ 
   \hline
\end{tabular}
\end{table}


Проверьте гипотезу о независимости шансов выжить от класса каюты.

\item Перед Вами две внешне неотличимых монетки. Одна из них выпадает «орлом» вверх с вероятностью $0.7$, другая — с вероятностью $0.3$. Вы имеете право на 4 подбрасывания. Перед каждым подбрасыванием Вы можете выбирать подбрасываемую монетку. За каждого выпавшего «орла» вы получаете 1 рубль.
\begin{enumerate}
\item Какова оптимальная стратегия?
\item Каков ожидаемый выигрыш при использовании оптимальной стратегии?
\end{enumerate}

\end{enumerate}

\section{2013-2014}

\input{chapters/year_2013_2014.tex}

\section{2014-2015}


\subsection{Контрольная работа 1. Базовый поток. 30.10.2014}
\subsubsection*{Тест}

\begin{enumerate}

\item Если $A \cap B = \emptyset$, то $A$ и $B$ — независимые события. Да. Нет.

\item Попарно независимые события независимы в совокупности. Да. Нет.

\item $\P(A \cap B) \le \P(A|B)$. Да. Нет.

\item Для любого числа $a$ и любой случайной величины $X$: $\P(X=a)>0$. Да. Нет.

\item Любая неотрицательная функция $f(x)$, такая что $\int_{-\infty}^{+\infty} f(x) dx = 1$, может быть функцией плотности некоторой случайной величины. Да. Нет.

\item Функция распределения имеет не более, чем счетное, число точек разрыва. Да. Нет.

\item Для того, чтобы существовало математическое ожидание абсолютно непрерывной случайной величины достаточно, чтобы $\int_{-\infty}^{+\infty} x f(x) dx < \infty$. Да. Нет.

\item В Пуассоновском распределении математическое ожидание всегда совпадает с дисперсией.	Да. Нет.

\item Математическое ожидание суммы случайных величин всегда равно сумме их математических ожиданий.	Да. Нет.

\item Дисперсия суммы случайных величин всегда равна сумме их дисперсий.	Да. Нет.

\item Хорошо, что не было вопросов про корреляцию.	Да. Нет.

\end{enumerate}

\subsubsection*{Задачи}

\begin{enumerate}



\item Вася забыл какую-то (какую?) формулу. Он помнит, что она начинается с $\P(A|B) = $ . Дальше была дробь, три буквы $P$ со скобками после них и в сумме по две буквы $A$ и $B$ внутри этих скобок. Ещё там была вертикальная черта «|». Из этих элементов Вася случайным образом составляет формулу.
\begin{enumerate}
\item С какой вероятностью Вася напишет правильную формулу?
\item Напишите формулу, которую забыл Вася.
\end{enumerate}

Примечание: Вася всё-таки успел сходить на пару лекций по теории вероятностей и помнит, что $\P(A|B)$ и $\P(B|A)$ — это не одно и то же, «|» должна стоять именно между буквами (то ли $A|B$, то ли $B|A$), а в скобках, которые идут после $P$, должно хоть что-то стоять. При этом формула должна иметь смысл, то есть  $\P(A|B)$   не должна выражаться через себя же, и дробь не должна быть сократимой.

\item Точка с координатами $(\xi, \eta)$ бросается наудачу в треугольник с вершинами $(1,0)$, $(0,0)$, $(0,1)$.  Сформулируйте определение независимости двух событий и проверьте, будут ли события $A=\{ \xi < 1/2 \}$  и $B=\{ \eta < 1/2 \}$  независимыми?

\item На учениях три самолёта одновременно и независимо атакуют цель. Известно, что первый самолёт поражает цель с вероятностью $0.6$, второй — $0.4$, третий — $0.3$. При разборе учений выяснилось, что цель была поражена только одним самолётом. Какова вероятность того, что это был первый самолёт?

\item Книга в $500$ страниц содержит $400$ опечаток. Предположим, что каждая из них независимо от остальных опечаток может с одинаковой вероятностью оказаться на любой странице книги.
\begin{enumerate}

\item Определите вероятность того, что на $13$-й странице будет не менее двух опечаток, в явном виде и с помощью приближения Пуассона.
\item Определите наиболее вероятное число, математическое ожидание и дисперсию числа опечаток на $13$-ой странице.
\item Является ли $13$-ая страница более «несчастливой», чем все остальные (в том смысле, что на $13$-ой странице ожидается большее количество очепяток, чем на любой другой)?
\end{enumerate}

Подсказка.  Можно считать, что опечатки «выбирают» любую из страниц для своего появления независимо друг от друга. Успех заключается в выборе $13$-ой страницы. Вероятность успеха?

\item Вероятность того, что медицинский тест выявит наличие заболевания, когда оно действительно есть, называется чувствительностью теста. Специфичностью теста называется вероятность того, что тест покажет отсутствие заболевания, когда пациент здоров. Вероятность того, что пациент болен, когда тест показал наличие заболевания, называется прогностической силой теста. Предположим, что только 1\,\%  всего населения страдает данным заболеванием.  Чувствительность используемого теста равна $0.9$, а специфичность — $0.95$.
\begin{enumerate}
\item Какова вероятность того, что у случайно выбранного человека тест покажет наличие заболевания?
\item Какова прогностическая сила теста? Что нужно сделать, чтобы её повысить?
\end{enumerate}

\item Функция плотности случайной величины $X$ имеет вид:
\begin{equation*}
f(x) =
 \begin{cases}
   1.5 (x-a)^2 &, x \in [0,a]\\
   1.5 (x+a)^2 &, x \in [-a,0]\\
   0 &, x \not\in [-a,a]
 \end{cases}
\end{equation*}

\begin{enumerate}
\item Найдите константу $a$, вероятность попадания в отрезок $\left[1/2, 2 \right]$, математическое ожидание $X$ и дисперсию случайной величины $X$.
\item Нарисуйте функцию распределения случайной величины $X$.
\end{enumerate}

\item Вася случайным образом посещает лекции по ОВП (Очень Важному Предмету). С вероятностью $0.9$ произвольно выбранная лекция полезна, и с вероятностью $0.7$ она интересна. Полезность и интересность — независимые друг от друга и от номера лекции свойства. Всего Вася прослушал 30 лекций.
\begin{enumerate}
\item Определите математическое ожидание и дисперсию числа полезных лекций и числа интересных лекций, прослушанных Васей.
\item Определите математическое ожидание числа бесполезных и неинтересных лекций, прослушанных Васей, и числа лекций, обладающих хотя бы одним из свойств (полезность,  интересность).
\end{enumerate}

\item Пусть $\E(X) = 1$, $\E(Y) = 2$, $\E(X^2) = 5$, $\E(XY) = -1$. Найдите:
\begin{enumerate}
\item $\E(2X + Y - 4)$
\item $\Var(X)$, $\Var(Y)$
\item $\Cov(X,Y)$, $\Corr(X,Y)$
\item $\Var(X-Y-1)$,  $\Var(X+Y+1)$
\item $\Cov(X-Y-1, X+Y+1)$,  $\Corr(X-Y-1, X+Y+1)$
\end{enumerate}

\item Совместное распределение случайных величин $X$ и $Y$ задано в виде таблицы:

\begin{tabular}{c|cc}
\toprule
 & $X=1$ & $X=2$ \\ \midrule
$Y=-1$ & $0.1$ & $0.2$ \\
$Y=0$ & $0.2$ & $0.3$ \\
$Y=1$ & $0$ & $0.2$ \\ \bottomrule
\end{tabular}

\begin{enumerate}
\item Найти частные распределения $Y$ и $Y^2$
\item Найти ковариацию случайных величин $X$ и $Y$
\item Можно ли утверждать, что случайные величины зависимы?
\end{enumerate}

\item Бонусная задача

Какова вероятность того, что наугад выбранный ответ на этот вопрос окажется верным (искомую вероятность вычислить и записать!)?
\begin{enumerate}
\item 0.25
\item 0.5
\item 0.6
\item 0.25
\end{enumerate}

\end{enumerate}

\subsection{Решение кр 1. Базовый поток}
\begin{enumerate}
\item Внимательно читайте примечание! Всего 6 возможных ситуаций, только 1 — благоприятная. Требуемая вероятность равна $1/6$.

\item
Два события $A$ и $B$ независимы, если: $\P(AB) = \P(A) \P(B)$.

Проверим, независимы ли события $A = \{ \xi < 1/2 \} $ и  $B = \{ \eta < 1/2 \} $:

$\P(AB)$ ищется как отношение площади квадрата с вершинами в $(0,\,0)$; $(0,\,1/2)$; $(1/2,\,1/2)$; $(1/2,\,0)$ к площади данного треугольника, т.е.:
\[\P(AB) = \frac{(1/2)^2}{1/2}= \frac{1}{2}\]

$\P(A)$ ищется как отношение площади трапеции с вершинами в $(0,\,0)$; $(0,\,1)$; $(1/2,\,1/2)$; $(1/2,\,0)$ к площади данного треугольника, т.е.:
\[\P(A) = \frac{(1/2)\cdot (3/2) \cdot (1/2)}{1/2}= \frac{3}{4}\]

$\P(B)$ ищется как отношение площади трапеции с вершинами в $(0,\,0)$; $(1,\,0)$; $(1/2,\,1/2)$; $(0,\,1/2)$ к площади данного треугольника, т.е.:
\[\P(B) = \frac{(1/2)\cdot (3/2) \cdot (1/2)}{1/2}= \frac{3}{4}\]

\[\P(A)\cdot \P(B) = \frac{3}{4} \cdot  \frac{3}{4} = \frac{9}{16} \ne \frac{1}{2} = \P(AB)\]

Итак, события $A$ и $B$ зависимы.

\item
Пусть событие $A$ = \{ Цель была поражена первым самолетом \}, событие $B$ = \{ Цель была поражена только одним самолетом \}. Тогда событие $AB$ = \{Первый самолет поразил цель, второй и третий — промахнулись  \}. По формуле условной вероятности:

\[\P(A|B) = \frac{\P(AB)}{\P(B)} = \frac{0.6 \cdot 0.6 \cdot 0.7}{0.6\cdot 0.6 \cdot 0.7 + 0.4 \cdot 0.4 \cdot 0.7 + 0.4 \cdot 0.6 \cdot 0.3} = \frac{0.252}{0.436} \approx 0.578\]

\item
Удобно рассуждать следующим образом: предположим, что каждая опечатка наугад (\textcolor{red}{с равными вероятностями и независимо от других опечаток}) выбирает, на какую страницу ей попасть.


\begin{enumerate}
\item Пусть $X$ - число опечаток на 13 странице. \[\P(X \geqslant 2) = 1 - \P(X=0) - \P(X=1) \]
$\P(X=0) = \left( \frac{499}{500} \right)^{400}$ — каждая из 400 опечаток не должна попасть на 13 страницу.\\
$\P(X=1) = 400\cdot\frac{1}{500}\cdot\left( \frac{499}{500} \right)^{399}$ — ровно одна опечатка (а есть 400 вариантов) должна попасть на 13 страницу, а остальные — мимо. Соответственно:
\[
\P(X \geqslant 2) = 1 - \left( \frac{499}{500} \right)^{400} - 400\cdot\frac{1}{500}\cdot\left( \frac{499}{500} \right)^{399} \approx 0.1911357
\]
Это если считать в явном виде. А если пользоваться приближением Пуассона:
\[
p(k) = \P(X = k) = \frac{\lambda^k}{k!}e^{-\lambda}
\]
неплохо бы вспомнить, что параметр $\lambda$ это математическое ожидание $X$, поэтому расчеты здесь пока оставим до лучших времен.

\item Пусть $X$ - число опечаток на 13 странице. Введем случайную величину
\[X_i =
\begin{cases}
1 & \text{если } i\text{-ая опечатка попала на 13 страницу}\\
0 & \text{если нет}
\end{cases}
\]
Тогда $X = \sum\limits_{i=1}^{400}X_i$. Рассмотрим отдельно $X_i$:

\begin{tabular}{@{}ccc@{}}
\toprule
$X$         & $1$             & $0$               \\ \midrule
$\P(\cdot)$ & $\frac{1}{500}$ & $\frac{499}{500}$ \\ \bottomrule
\end{tabular}

Так как $i$-ая опечатка наугад выбирает одну страницу из 500 и это должна быть именно 13.

Тогда:
\[
\E(X_i) = \frac{1}{500} = \E(X^2_i) \Rightarrow
\]
\[
\Rightarrow \Var(X_i) = \E(X^2_i) - (\E(X_i))^2 = \frac{1}{500} - \left(\frac{1}{500}\right)^2 = \frac{499}{500^2}
\]
Значит
\[
\E(X) = \E\left(\sum\limits_{i=1}^{400}X_i\right) = \sum\limits_{i=1}^{400}\E(X_i)  = \frac{400}{500} = 0.8
\]

\[
\Var(X) = \Var\left(\sum\limits_{i=1}^{400}X_i\right) = \sum\limits_{i=1}^{400}\Var(X_i) = 400\cdot\frac{499}{500^2} = 0.8\cdot\frac{499}{500}
\]

Теперь мы знаем, что $\lambda = \E(X) = 0.8$ поэтому можем вернуться к пункту (а):
\[
\P(X \geqslant 2) = 1 - \P(X=0) - \P(X=1)  = 1 - \frac{0.8^0}{0!}e^{-0.8} - \frac{0.8^1}{1!}e^{-0.8} = 0.1912079
\] \vspace{-1.2cm}

\hspace{13cm} \fcolorbox{ForestGreen}{white}{So close!}

Осталось найти наиболее вероятное число опечаток на 13 странице:
\[
\P(X=k) = \frac{0.8^k}{k!}e^{-0.8} \rightarrow \max \limits_k
\]
Очевидно, что эта функция убывает по $k$, ведь с ростом $k$:\\
 $k!$ растет, а $0.8^k$ убывает. Значит наиболее вероятное число ошибок — $X = 0$


\item \href{https://en.wikipedia.org/wiki/Triskaidekaphobia}{Ох уж эти предрассудки!} 13-я страница точно такая же как и все остальные, ведь везде в решении можно просто заменить номер 13 на любой другой и ничего не изменится.

\end{enumerate}

\item
Перепишем условие задачи:

Чувствительность теста = \\$=\P(\text{Медицинский тест показывает наличие заболевания} | \text{Заболевание есть})$

Специфичность теста = \\$=\P(\text{Медицинский тест показывает отсутствие заболевания} | \text{Заболевания нет})$

Прогностическая сила теста = \\$=\P(\text{Заболевание есть} | \text{Медицинский тест показывает наличие заболевания})$

$\P(\text{Заболевание есть}) = 0.01 \Rightarrow \P(\text{Заболевания нет}) = 0.99 $

По условию чувствительность теста равна 0.9, тогда из формулы условной вероятности:

\[\P(\text{Мед. тест пок-ет наличие заб-ия} | \text{Заб-ие есть}) = \]
\[\frac{\P(\text{Мед. тест пок-ет наличие заб-ия, Заб-ие есть})}{\P(\text{Заб-ие есть})} \Rightarrow\]
\[\Rightarrow \P(\text{Мед. тест пок-ет наличие заб-ия, Заб-ие есть}) = 0.9 \cdot 0.01 = 0.009\]

При этом очевидно, что:
\[\P(\text{Заболевание есть}) = \P(\text{Мед. тест пок-ет наличие заб-ия, Заб-ие есть}) + \]
\[+ \P(\text{Мед. тест пок-ет отсутствие заб-ия, Заб-ие есть}) \Rightarrow\]
\[\Rightarrow \P(\text{Мед. тест пок-ет отсутствие заб-ия, Заб-ие есть}) = 0.01 - 0.009 = 0.001\]

По условию специфичность теста равна 0.95, тогда из формулы условной вероятности:
\[\P(\text{Мед. тест пок-ет отсутствие заб-ия} | \text{Заб-ия нет}) = \]
\[\frac{\P(\text{Мед. тест пок-ет отсутствие заб-ия, Заб-ия нет})}{\P(\text{Заб-ия нет})} \Rightarrow\]
\[\P(\text{Мед. тест пок-ет отсутствие заб-ия, Заб-ия нет}) =0.95 \cdot 0.99 = 0.9405\]

При этом очевидно, что:
\[\P(\text{Заб-ия нет}) = \P(\text{Мед. тест пок-ет наличие заб-ия, Заб-ия нет}) + \]
\[+ \P(\text{Мед. тест пок-ет отсутствие заб-ия, Заб-ия нет}) \Rightarrow\]
\[\Rightarrow \P(\text{Мед. тест пок-ет наличие заб-ия, Заб-ия нет}) = 0.99 - 0.9405 = 0.0495\]

Теперь мы готовы отвечать на заданные вопросы:

\begin{itemize}
\item
\[\P(\text{Мед. тест пок-ет наличие заб-ия}) = \]
\[= \P(\text{Мед. тест пок-ет наличие заб-ия, Заб-ия нет}) + \]
\[+ \P(\text{Мед. тест пок-ет наличие заб-ия, Заб-ие есть}) = 0.009+0.0495 = 0.0585 \]

\item Прогностическая сила теста:

\[\P(\text{Заболевание есть} | \text{Медицинский тест показывает наличие заболевания}) = \]
\[= \frac{\P(\text{Мед. тест пок-ет наличие заб-ия, Заб-ие есть})}{\P(\text{Мед. тест пок-ет наличие заб-ия}) } = \frac{0.009}{0.0585} \approx 0.154\]

Для того, чтобы повысить прогностическую силу теста, необходимо понизить $\P(\text{Мед. тест пок-ет наличие заб-ия, Заб-ия нет}) $, а для этого необходимо повысить специфичность теста.

\end{itemize}

\item
\begin{itemize}
\item
Должно выполняться условие нормировки:
\[\int \limits_{-a}^0 1.5(x+a)^2 dx + \int \limits_0^a 1.5(x- a)^2  dx = 1   \]
\[0.5(x+a)^3 |_{-a}^0 + 0.5(x- a)^3 |_0^a  = 1   \]
\[0.5a^3 + 0.5a^3 = 1\]
\[a = 1\]

Теперь легко понять, как выглядит функция распределения (смотри определение функции распределения):

$F(x) = \begin{cases}
0, & x < 1 \\
0.5 (x+1)^3, & -1 \leqslant x <0 \\
1 + 0.5 (x-1)^3, & 0 \leqslant x < 1 \\
1, & x \geqslant 1
\end{cases}$

\[P\left(X \in \left[\frac{1}{2}, 2 \right]  \right) = F(2) - F\left(\frac{1}{2} \right) = 1 - 1 +0.5^4 = 0.5^4 \]

\[\E(X) = \int \limits_{-1}^0 x \cdot 1.5 (x + 1)^2 dx +  \int \limits_0^1 x \cdot 1.5 (x - 1)^2 dx = \]
\[= 1.5 \int \limits_{-1}^0\left( x^3 + 2x^2 + x\right) dx + 1.5 \int \limits_0^1\left( x^3 -2x^2 + x\right) dx = \]
\[=  \frac{3}{8} x^4 |_{-1}^0 + x^3 |_{-1}^0 + \frac{3}{4} x^2|_{-1}^0+    \frac{3}{8} x^4 |_0^1   - x^3 |_0^1 + \frac{3}{4} x^2|_0^1  = - \frac{3}{8}  + 1- \frac{3}{4} + \frac{3}{8} - 1 +\frac{3}{4} = 0 \]

А можно было заметить, что функция плотности — четная функция, поэтому сразу $\E(X) = 0$

Вычислим $\E(X^2)$:
\[\E(X^2) = \int \limits_{-1}^0 x^2 \cdot 1.5 (x + 1)^2 dx +  \int \limits_0^1 x^2 \cdot 1.5 (x - 1)^2 dx = \]
\[= 1.5 \int \limits_{-1}^0\left( x^4 + 2x^3 + x^2\right) dx + 1.5 \int \limits_0^1\left( x^4 -2x^3 + x^2\right) dx = \]
\[=  \frac{3}{10} x^5 |_{-1}^0 + \frac{3}{4} x^4|_{-1}^0 + \frac{1}{2} x^3 |_{-1}^0 +  \frac{3}{10} x^5 |_0^1 - \frac{3}{4} x^4|_0^1  + \frac{1}{2} x^3 |_0^1 =  \frac{1}{10}\]

\[\Var(X) = \E(X^2) - (\E(X))^2 = 0.1\]

\item Верим, что график $F(x)$, выписанной выше, вы построить можете :)
\end{itemize}
\item
Пусть $A = \{\text{«Лекция полезна»}\}$, $B = \{\text{«Лекция интересна»}\}$. Заметим, что лекции вообще независимы друг от друга.

\begin{enumerate}
\item Пусть $X_A$ — число полезных лекций, прослушанных Васей,  $X_B$ — число интересных лекций, прослушанных Васей. Введем случайную величину:
\[X_i =
\begin{cases}
1 & \text{если } i\text{-ая лекция была полезна}\\
0 & \text{если нет}
\end{cases}
\]

Тогда $X_A = \sum\limits_{i=1}^{30}X_i$. Рассмотрим отдельно $X_i$:

\begin{tabular}{@{}ccc@{}}
\toprule
$X$         & $1$             & $0$               \\ \midrule
$\P(\cdot)$ & $0.9$ & $0.1$ \\ \bottomrule
\end{tabular}

Вероятность 0.9 дана. Тогда:
\[
\E(X_i) = 0.9 = \E(X^2_i) \Rightarrow
\]
\[
\Rightarrow \Var(X_i) = \E(X^2_i) - (\E(X_i))^2 = 0.9 - 0.9^2 = 0.09
\]

Значит
\[
\E(X_A) = \E\left()\sum\limits_{i=1}^{30}X_i\right) = \sum\limits_{i=1}^{30}\E(X_i)  = 0.9\cdot30 = 27
\]
\[
\Var(X_A) = \Var\left(\sum\limits_{i=1}^{30}X_i\right) = \sum\limits_{i=1}^{30}\Var(X_i) = 0.09\cdot30 = 2.7
\]

Аналогично для числа интересных лекций можем получить:
\[
\E(X_B) = 0.7\cdot 30 = 21
\]
\[
\Var(X_A) = 0.21\cdot 30 = 6.3
\]


\item Так как интересность и полезность — независимые свойства лекций, то:\\
 $\P(\overline{A} \cap \overline{B}) = \P(\overline{A})\cdot \P(\overline{B}) = 0.3\cdot0.1 = 0.03$, где $\overline{A}$ значит «не $A$». В свою очередь:\\
 $\P(A\cup B) = \P(A\cap\overline{B}) + \P(B\cap\overline{A}) + \P(A\cap B) = 1 - \P(\overline{A})\cdot \P(\overline{B}) = 0.97$ , где $(A\cup B)$ значит «$A$ или $B$», а $(A\cap)B$ — «$A$ и $B$». Аналогично, путем введения бинарной случайной величины можем получить:
 \[
 \E(X_{\overline{A} \cap \overline{B}}) = 0.03 \cdot  30 = 0.9
 \]
 \[
 \E(X_{A\cup B}) = 0.97\cdot30 = 29.1
\]

\end{enumerate}

\item
Дано: $\E(X) = 1$, $\E(Y) = 2$, $\E(X^2) = 5$, $\E(Y^2) = 8$, $\E(XY) = -1$.

Будем использовать только свойства математического ожидания, ковариации и дисперсии, и ничего больше. Ни-че-го.

\begin{itemize}
\item  $\E(2X + Y - 4) = 2\E(X) + \E(Y) + \E(-4) = 2 + 2 - 4 = 0 $
\item $\Var(X) = \E(X^2) - (\E(X))^2 = 5 - 1 = 4 $
\item $\Var(Y) = \E(Y^2) - (\E(Y))^2 = 8 - 4 = 4 $
\item $\Cov(X, Y) = \E(XY) - \E(X)\E(Y) = -1 - 2 = -3$
\item $\Corr(X, Y) = \frac{\Cov(X, Y)}{\sqrt{\Var(X)}\sqrt{\Var(Y)}} = -\frac{3}{2\cdot 2} = -0.75$
\item $\Var(X-Y-1) = \Var(X) + \Var(Y) - 2\Cov(X, Y) = 4+4 -2(-3) = 14$
\item $\Var(X+Y+1) = \Var(X) + \Var(Y) + 2\Cov(X, Y) = 4+4+2(-3) =2 $
\item \begin{multline}
\Cov(X-Y-1, X+Y+1)=\E((X-Y)(X+Y))-\E(X-Y)\E(X+Y) = \\
\E(X^2-Y^2) - (\E(X)-\E(Y))(\E(X) + \E(Y)) =
\E(X^2) - \E(Y^2) - ((\E(X))^2 -(\E(Y))^2)=\\
 = \Var(X)-\Var(Y) = 0
 \end{multline}
 \item $\Cov(X-Y-1, X+Y+1)=0 \Rightarrow \Corr(X-Y-1, X+Y+1) = 0 $
\end{itemize}

\item Найдем частные распределения $Y$ и $Y^2$:
\begin{center}
\begin{tabular}{c|cc|c}
\toprule
 & $X=1$ & $X=2$ & $\sum$ \\ \midrule
$Y=-1$ & $0.1$ & $0.2$ & $0.3$ \\
$Y=0$ & $0.2$ & $0.3$ & $0.5$ \\
$Y=1$ & $0$ & $0.2$ & $0.2$ \\
$\sum$ & $0.3$ & $0.7$ & \\ \bottomrule
\end{tabular}
\end{center}

\begin{center}
\begin{tabular}{@{}cccc@{}}
\toprule
$Y$         & $-1$             & $0$      & $1$         \\ \midrule
$\P(\cdot)$ & $0.3$ & $0.5$  & $0.2$\\ \bottomrule
\end{tabular}
\end{center}

Так как $Y^2$ может принимать только значения 0 или 1:

\begin{center}
\begin{tabular}{@{}ccc@{}}
\toprule
$Y^2$         & $0$             & $1$               \\ \midrule
$\P(\cdot)$ & $0.5$ & $0.5$ \\ \bottomrule
\end{tabular}
\end{center}
А ковариация:
 \begin{multline*}
 \Cov(X, Y) = \E(XY) - \E(X)\E(Y) =
 ((-1)\cdot 1\cdot0.1 + (-1)\cdot2 \cdot 0.2 + 1\cdot2\cdot 0.2) -\\
 - (0.3\cdot1 + 0.7 \cdot 2)\cdot(0.3\cdot(-1) + 0.1\cdot 0.2) = 0.07
\end{multline*}

Так как $\Cov(X, Y) \ne 0$ — величины зависимы

\item Бонусная задача

Предположим, что правильный ответ 0.25. Но это невозможно, потому что вариантов ответа 0.25 — два (1 и 4), значит ответ 0.5 тоже был бы правильный. Предположим, что правильный 0.5. Тогда 0.25 тоже правильный — таких вариантов два из четырех, значит вероятность попасть в 0.25, выбрав ответ наугад, равна 0.5. Ответ 0.6, очевидно, неверен, потому что вероятность попасть в него равна 0.25. \\
\textbf{Правильный ответ:} 0
\end{enumerate}


\subsection{Праздник номер 1, i-поток, 30.10.2014}

\subsubsection*{ Часть 1}

\begin{enumerate}
%\item Винни-Пух собирается играть в Пустяки и готовит для игры палочки. Он нашел палку длиной 1 м, а дальше поступает следующим образом. Разламывает палку равномерно в случайном месте, одну полученную часть использует для игры, а вторую снова случайным образом делит на две части. Далее одну новую часть Винни-Пух снова использует для игры, а вторую новую часть снова делит на две. И так далее. Обозначим $X_i$ — длину палочки, использованной Винни-Пухом в $i$-ых Пустяках.

%Найдите функцию плотности $X_i$, $\E(X_i)$, $\Var(X_i)$

\item Вася купил два арбуза у торговки тети Маши и один арбуз у торговки тети Оли. Арбузы у тети Маши спелые с вероятностью 90\% (независимо друг от друга), арбузы у тети Оли спелые с вероятностью 70\%.

\begin{enumerate}
\item Какова вероятность того, что все Васины арбузы спелые?
\item Придя домой Вася выбрал случайным образом один из трех арбузов и разрезал его. Какова вероятность того, что это арбуз от тёти Маши, если он оказался спелым?
\item Какова вероятность того, что второй и третий съеденные Васей арбузы были от тёти Маши, если все три арбуза оказались спелыми?
\end{enumerate}


\item В большой большой стране живет очень большое количество $n»0$ семей. Количества детей в разных семьях независимы. Количество детей в каждой семье — случайная величина с распределением заданным табличкой:

\begin{tabular}{ccccc}
\toprule
$X$ & $0$ & $1$ & $2$ & $3$ \\ \midrule
$\P(\cdot)$ & $0.1$ & $0.3$ & $0.2$ & $0.4$ \\ \bottomrule
\end{tabular}

\begin{enumerate}
\item Исследователь Афанасий выбирает одну семью из всех семей наугад, пусть $X$ — число детей в этой семье. Найдите $\E(X)$ и $\Var(X)$.
\item Исследователь Бенедикт выбирает одного ребенка из всех детей наугад, пусть $Y$ — число детей в семье этого ребёнка. Как распределена величина $Y$? Что больше, $\E(Y)$ или $\E(X)$?
\end{enumerate}

\item Функция плотности случайной величины $X$ имеет вид
\[
f(x)=
\begin{cases}
\frac{3}{8} x^2, \text{ если } x\in [0;2] \\
0, \text{ иначе }
\end{cases}
\]
\begin{enumerate}
\item Не производя вычислений найдите $\int_{-\infty}^{+\infty}f(x)\,dx$
\item Найдите $\E(X)$, $\E(X^2)$ и дисперсию $\Var(X)$
\item Найдите $\P(X>1.5)$, $\P(X>1.5 \mid X>1)$
\item При каком $c$ функция $g(x)=c x f(x)$ будет функцией плотности некоторой случайной величины?
\end{enumerate}

\item Известно, что  $\E\left(Z\right)=-3$. $\E\left(Z^{2} \right)=15$,  $\Var\left(X+Y\right)=20$  и  $\Var\left(X-Y\right)=10$.
\begin{enumerate}
\item Найдите  $\Var\left(Z\right)$,  $\Var\left(4-3Z\right)$  и  $\E\left(5+3Z-Z^{2} \right)$
\item Найдите  $\Cov\left(X,Y\right)$  и  $\Cov\left(6-X,3Y\right)$
\item Можно ли утверждать, что случайные величины $X$ и $Y$ независимы?
\end{enumerate}

\item Листая сборник задач по теории вероятностей Вася наткнулся на задачу:


\fbox{%
\parbox{15cm}{%
Какова вероятность того, что наугад выбранный ответ на этот вопрос окажется верным?

1) 0.25		2) 0.5		3) 0.6		4) 0.25 }
}

Чему же равна вероятность выбора верного ответа?

\item Книга в 500 страниц содержит 400 опечаток. Предположим, что каждая из них независимо от остальных опечаток может с одинаковой вероятностью оказаться на любой странице книги.
\begin{enumerate}
\item Определите вероятность того, что на 13-й странице будет не менее двух опечаток, в явном виде и с помощью приближения Пуассона.
\item Определите наиболее вероятное число, математическое ожидание и дисперсию числа опечаток на 13-ой странице.
\item Является ли 13-ая страница более «несчастливой», чем все остальные (в том смысле, что на 13-ой странице ожидается большее количество очепяток, чем на любой другой)?
\end{enumerate}
\item Вася случайным образом посещает лекции по ОВП (Очень Важному Предмету). С вероятностью 0.9 произвольно выбранная лекция полезна, и с вероятностью 0.7 она интересна. Полезность и интересность — независимые друг от друга и от номера лекции свойства. Всего Вася прослушал 30 лекций.
\begin{enumerate}
\item Определите математическое ожидание и дисперсию числа полезных лекций, прослушанных Васей
\item Определите математическое ожидание числа одновременно бесполезных и неинтересных лекций, прослушанных Васей, и математическое ожидание числа лекций, обладающих хотя бы одним из свойств (полезность,  интересность)
\end{enumerate}
\item Функция распределения случайной величины X задана следующей формулой:
 \[
 F(x)=\frac{ae^x}{1+e^x}+b
 \]
Определите: константы $a$ и $b$, математическое ожидание и третий начальный момент случайной величины $X$, медиану и моду распределения.

%\item Вы хотите приобрести некую фирму. Стоимость фирмы для ее нынешних владельцев — случайная величина, равномерно распределенная на отрезке $[0;1]$. Вы предлагаете владельцам продать ее за называемую Вами сумму. Владельцы либо соглашаются, либо нет. Если владельцы согласны, то Вы платите обещанную сумму и получаете фирму. Когда фирма переходит в Ваши руки, ее стоимость сразу возрастает на 20\%.

%\begin{enumerate}
%\item Чему равен Ваш ожидаемый выигрыш, если Вы предлагаете цену 0.5?
%\item Какова оптимальная предлагаемая цена?
%\end{enumerate}

\end{enumerate}



\subsubsection*{Часть 2}

\begin{enumerate}
\item Маша подкидывает кубик до тех пор, пока два последних броска в сумме не дадут\footnote{Изначально вместо 12 задумывалось число 10, но  опечатка была замечена поздно, поэтому решение приводится для 12.} 12. Обозначим случайные величины: $N$ — количество бросков, а $S$ — сумма набранных за всю игру очков.
\begin{enumerate}
\item Найдите $\P(N=2)$, $\P(N=3)$
\item Найдите $\E(N)$, $\E(S)$, $\E(N^2)$
\item Пусть $X_N$ — результат последнего броска. Как распределена случайная величина $X_N$?
\end{enumerate}


\item В столовую пришли 30 студентов и встали в очередь в случайном порядке. Среди них есть Вовочка и Машенька. Пусть $V$ — это количество человек в очереди перед Вовочкой, а $M\geq 0$ — количество человек между Вовочкой и Машенькой.
\begin{enumerate}
\item Найдите $\P(V=1)$, $\P(M=1)$, $\P(M=V)$
\item Найдите $\E(V)$, $\E(M)$, $\Var(M)$
\end{enumerate}

\item Польский математик Стефан Банах имел привычку носить в каждом из двух карманов пальто по коробку спичек. Всякий раз, когда ему хотелось закурить трубку, он выбирал наугад один из коробков и доставал из него спичку. Первоначально в каждом коробке было по $n$ спичек. Но когда-то наступает момент, когда выбранный наугад коробок оказывается пустым.

\begin{enumerate}
\item Какова вероятность того, что в другом коробке в этот момент осталось ровно $k$ спичек?
\item Каково среднее количество спичек в другом коробке?
\end{enumerate}

\item Производитель чудо-юдо-йогуртов наклеивает на каждую упаковку одну из 50 случайно выбираемых наклеек. Покупатель собравший все виды наклеек получает приз от производителя. Пусть $X$ — это количество упаковок йогурта, которое нужно купить, чтобы собрать все наклейки.

Найдите $\P(X=50)$, $\E(X)$, $\Var(X)$

Hint: $\ln(50)\approx 3.91$, а $\sum_{i=1}^n \frac{1}{i} \approx \int_1^n \frac{1}{x}\, dx$ :)


\item В самолете $n$ мест и все билеты проданы. Первой в очереди на посадку стоит Сумасшедшая Старушка. Сумасшедшая Старушка несмотря на билет садиться на случайно выбираемое место. Каждый оставшийся пассажир садится на своё место, если оно свободно и на случайное выбираемое место, если его место уже кем-то занято.

\begin{enumerate}
\item Какова вероятность того, что все пассажиры сядут на свои места?
%\item Какова вероятность того, что второй пассажир в очереди сядет на своё место?
\item Какова вероятность того, что последний пассажир сядет на своё место?
\item Чему примерно равно среднее количество пассажиров севших на свои места?
\end{enumerate}


\end{enumerate}


\subsection{Праздник номер 1 по теории вероятностей, i-поток. Решение }

\subsubsection*{Часть 1}

Не претендуя на единственность, решения претендуют на правильность!


\begin{enumerate}
\item

\begin{enumerate}
\item $\P(\cdot) = 0.9^2\cdot 0.7 = 0.567  $
\item $A$ = \{случайно выбранный арбуз — от тети Маши\}; $B$ = \{случайно выбранный арбуз оказался спелым\}. Формула условной вероятности:
\[\P(A|B) = \frac{\P(AB)}{\P(B)}= \frac{2/3 \cdot 0.9}{2/3 \cdot 0.9 + 1/3 \cdot 0.7} =\frac{18}{25}\]
\item $A$ = \{второй и третий съеденные арбузы — от тети Маши\}; $B$ = \{все три арбуза — спелые\}. Дает ли нам что-то о принадлежности арбузов к тете Маше или тете Оле то, что все арбузы — спелые? События независимы!
\[\P(A|B) = \P(A) = \frac{1}{3}\]
\end{enumerate}

\item
\begin{enumerate}
\item $\E(X) = \sum \P(X_i) X_i = 1.9$

$\Var(X) = \E(X^2) - (\E(X))^2 = 0\cdot 0.1 + 1 \cdot 0.3 + 4 \cdot 0.2 + 9 \cdot 0.4 - 1.9^2 = 1.09$

\item Раз ребенок выбран, значит, в его семье дети есть! Всего детей $n\E(X) = 1.9n$. Семей с одним ребенком — $0.3n$, значит, детей из семей с одним ребенком — $0.3n$. Аналогично, детей из семей с двумя детьми — $0.4n$; детей из семей с тремя детьми — $1.2n$.

Теперь легко построить закон распределения случайной величины $Y$:

\begin{tabular}{cccc}
\toprule
$Y$ & $1$ & $2$ & $3$  \\ \midrule
$\P(\cdot)$ & $3/19$ & $4/19$ & $12/19$  \\ \bottomrule
\end{tabular}


\[\E(Y) = \frac{3}{19} + \frac{8}{19} + \frac{36}{19} = \frac{47}{19} > \E(X)\]

\end{enumerate}


\item
Любителям (или нелюбителям) интегралов:
\begin{enumerate}
\item Да это же интеграл от функции плотности на всей числовой прямой! Ответ: единица!
\item \[\E(X) = \int \limits_0^2 x f(x) dx = \int \limits_0^2 \frac{3}{8} x^3 dx = \frac{3}{32} x^4 |_0^2 = \frac{3}{2}\]

\[\E(X^2) = \int \limits_0^2 x^2 f(x) dx = \int \limits_0^2 \frac{3}{8} x^4 dx = \frac{3}{40} x^5 |_0^2 = \frac{12}{5}\]

Формула дисперсии:
\[\Var(X) = \E(X^2) - \left(\E(X) \right)^2 = \frac{12}{5} - \frac{9}{4} = \frac{3}{20} \]

\item \[\P(X>1.5) = \int \limits_{1.5}^2 f(x) dx = \int \limits_{1.5}^2 \frac{3}{8} x^2 dx = \frac{1}{8} x^3 |_{1.5}^2 = \frac{37}{64}\]

Вычислим вероятность условия:

\[\P(X>1) = \int \limits_1^2 f(x) dx = \int \limits_1^2 \frac{3}{8} x^2 dx = \frac{1}{8} x^3 |_1^2 = \frac{7}{8}\]

\[\P(X>1.5 | X>1) = \frac{\P(X>1.5)}{\P( X>1)} = \frac{37/64}{7/8} = \frac{37}{56}\]

\item Должно выполниться следующее соотношение:
\[\int \limits_{-\infty}^{+\infty} c x f(x) dx  = 1\]

Применительно к нашей задаче:
\[\frac{3c}{8} \int \limits_0^2 x^3 dx  = \frac{3c}{32} x^4 |_0^2 = \frac{3c}{2} = 1 \Rightarrow c = \frac{2}{3}\]
\end{enumerate}

\item
You have to learn the rules of the game. And then you have to play better than anyone else. (А. Эйнштейн)

\begin{enumerate}
\item \[\Var(Z) = \E(Z^2) - (\E(Z))^2 = 15 - 9 = 6\]
\[\Var(4 - 3Z) = 9\Var(Z) = 54\]
\[\E(5 + 3Z - Z^2) = 5 + 3\cdot (-3)  - 15 = -19 \]

\item \[\Var(X \pm Y) = \Var(X) + \Var(Y) \pm 2 \cdot \Cov(X, Y)\]
Отсюда получаем:
\[\Var(X + Y) - \Var(X - Y) = 4 \Cov(X, Y) \Rightarrow \Cov(X, Y) = 2.5\]
\[\Cov(6 - X, 3Y) = -3\cdot 2.5 = -7.5\]

\item \[\Cov(X, Y) = 2.5 \ne 0\] Случайные величины действительно независимы.
\end{enumerate}


\item
 В условии не сказано сколько ответов являются верными. Предположим, что правильный ответ 0.25. Но это невозможно, потому что вариантов ответа 0.25 — два (1 и 4), значит ответ 0.5 тоже был бы правильный. Предположим, что правильный 0.5. Тогда 0.25 тоже правильный — таких вариантов два из четырех, значит вероятность попасть в 0.25, выбрав ответ наугад, равна 0.5. Ответ 0.6, очевидно, неверен, потому что вероятность попасть в него равна 0.25. \\
\textbf{Правильный ответ:} 0

\item
Удобно рассуждать следующим образом: предположим, что каждая опечатка наугад (\textcolor{red}{с равными вероятностями и независимо от других опечаток}) выбирает, на какую страницу ей попасть\footnote[1]{Ну очень самостоятельные!}.

\begin{enumerate}
\item Пусть $X$ - число опечаток на 13 странице. \[\P(X \geqslant 2) = 1 - \P(X=0) - \P(X=1) \]
$\P(X=0) = \left( \frac{499}{500} \right)^{400}$ — каждая из 400 опечаток не доложна попасть на 13 страницу.\\
$\P(X=1) = 400\cdot\frac{1}{500}\cdot\left( \frac{499}{500} \right)^{399}$ — ровно одна опечатка (а есть 400 вариантов) должна попасть на 13 страницу, а остальные — мимо. Соответственно:
\[
\P(X \geqslant 2) = 1 - \left( \frac{499}{500} \right)^{400} - 400\cdot\frac{1}{500}\cdot\left( \frac{499}{500} \right)^{399} \approx 0.1911357
\]
Это если считать в явном виде. А если пользоваться приближением Пуассона:
\[
p(k) = \P(X = k) = \frac{\lambda^k}{k!}e^{-\lambda}
\]
неплохо бы вспомнить, что параметр $\lambda$ это математическое ожидание $X$, поэтому расчеты здесь пока оставим до лучших времен.

\item Пусть $X$ — число опечаток на 13 странице. Введем случайную величину
\[X_i =
\begin{cases}
1 & \text{если } i\text{-ая опечатка попала на 13 страницу}\\
0 & \text{если нет}
\end{cases}
\]
Тогда $X = \sum\limits_{i=1}^{400}X_i$. Рассмотрим отдельно $X_i$:

\begin{tabular}{@{}ccc@{}}
\toprule
$X$         & $1$             & $0$               \\ \midrule
$\P(\cdot)$ & $\frac{1}{500}$ & $\frac{499}{500}$ \\ \bottomrule
\end{tabular}

Так как $i$-ая опечатка наугад выбирает одну страницу из 500 и это должна быть именно 13.

Тогда:
\[
\E(X_i) = \frac{1}{500} = \E(X^2_i) \Rightarrow
\]
\[
\Rightarrow \Var(X_i) = \E(X^2_i) - (\E(X_i))^2 = \frac{1}{500} - \left(\frac{1}{500}\right)^2 = \frac{499}{500^2}
\]
Значит
\[
\E(X) = \E\left(\sum\limits_{i=1}^{400}X_i\right) = \sum\limits_{i=1}^{400}\E(X_i)  = \frac{400}{500} = 0.8
\]

\[
\Var(X) = \Var\left(\sum\limits_{i=1}^{400}X_i\right) = \sum\limits_{i=1}^{400}\Var(X_i) = 400\cdot\frac{499}{500^2} = 0.8\cdot\frac{499}{500}
\]

Теперь мы знаем, что $\lambda = \E(X) = 0.8$ поэтому можем вернуться к пункту (а):
\[
\P(X \geqslant 2) = 1 - \P(X=0) - \P(X=1)  = 1 - \frac{0.8^0}{0!}e^{-0.8} - \frac{0.8^1}{1!}e^{-0.8} = 0.1912079
\] \vspace{-1.2cm}

\hspace{13cm} \fcolorbox{ForestGreen}{white}{So close!}

Осталось найти наиболее вероятное число опечаток на 13 странице:
\[
\P(X=k) = \frac{0.8^k}{k!}e^{-0.8} \rightarrow \max \limits_k
\]
Очевидно, что эта функция убывает по $k$, ведь с ростом $k$:\\
 $k!$ растет, а $0.8^k$ убывает. Значит наиболее вероятное число ошибок — $X = 0$


\item \href{https://en.wikipedia.org/wiki/Triskaidekaphobia}{Ох уж эти предрассудки!} 13-я страница точно такая же как и все остальные, ведь везде в решении можно просто заменить номер 13 на любой другой и ничего не изменится.
\begin{center}
\includegraphics[width=6cm]{images/13}
\end{center}
\end{enumerate}

\item
Пусть $A = \{\text{«Лекция полезна»}\}$, $B = \{\text{«Лекция интересна»}\}$. Заметим, что лекции вообще независимы друг от друга.

\begin{enumerate}
\item Пусть $X_A$ — число полезных лекций, прослушанных Васей,  $X_B$ — число интересных лекций, прослушанных Васей. Введем случайную величину:
\[X_i =
\begin{cases}
1 & \text{если } i\text{-ая лекция была полезна}\\
0 & \text{если нет}
\end{cases}
\]

Тогда $X_A = \sum\limits_{i=1}^{30}X_i$. Рассмотрим отдельно $X_i$:

\begin{tabular}{@{}ccc@{}}
\toprule
$X$         & $1$             & $0$               \\ \midrule
$\P(\cdot)$ & $0.9$ & $0.1$ \\ \bottomrule
\end{tabular}

Вероятность 0.9 дана. Тогда:
\[
\E(X_i) = 0.9 = \E(X^2_i) \Rightarrow
\]
\[
\Rightarrow \Var(X_i) = \E(X^2_i) - (\E(X_i))^2 = 0.9 - 0.9^2 = 0.09
\]

Значит
\[
\E(X_A) = \E\left(\sum\limits_{i=1}^{30}X_i\right) = \sum\limits_{i=1}^{30}\E(X_i)  = 0.9\cdot30 = 27
\]
\[
\Var(X_A) = \Var\left(\sum\limits_{i=1}^{30}X_i\right) = \sum\limits_{i=1}^{30}\Var(X_i) = 0.09\cdot30 = 2.7
\]

Аналогично для числа интересных лекций можем получить:
\[
\E(X_B) = 0.7\cdot 30 = 21
\]
\[
\Var(X_B) = 0.21\cdot 30 = 6.3
\]


\item Так как интересность и полезность — независимые свойства лекций, то:\\
 $\P(\overline{A} \cap \overline{B}) = \P(\overline{A})\cdot \P(\overline{B}) = 0.3\cdot0.1 = 0.03$, где $\overline{A}$ значит «не $A$». В свою очередь:\\
 $\P(A\cup B) = \P(A\cap\overline{B}) + \P(B\cap\overline{A}) + \P(A\cap B) = 1 - \P(\overline{A})\cdot \P(\overline{B}) = 0.97$ , где $(A\cup B)$ значит «$A$  или $B$». Аналогично, путем введения бинарной случайной величины можем получить:
 \[
 \E(X_{\overline{A} \cap \overline{B}}) = 0.03 \cdot  30 = 0.9
 \]
 \[
 \E(X_{A\cup B}) = 0.97\cdot30 = 29.1
\]
\end{enumerate}

\item
Будем пользоваться свойствами функций распределения и плотности. Для начала:
\[
\lim\limits_{x \rightarrow +\infty} F(X) = 1, \hspace{0.5cm} \lim\limits_{x \rightarrow -\infty} F(X) = 0,
\]
\[
\lim\limits_{x \rightarrow +\infty} \left(\frac{ae^x}{1+e^x}+b\right) = a+b := 1
\]
\[
\lim\limits_{x \rightarrow -\infty} \left(\frac{ae^x}{1+e^x}+b\right) = b :=0
\]
Откуда сразу получаем \[a =1, b = 0 \Rightarrow F(x) = \frac{e^x}{1+e^x}\]
Для дальнейших развлечений нам понадобится функция плотности:
\[
f(x) = F'(x) = \frac{e^x}{(1+e^x)^2}
\]
 Заметим, что она симметрична относительно нуля:
 \[
 f(-x) = \frac{\frac{1}{e^x}}{\left(1+\frac{1}{e^x}\right)^2} = \frac{e^x}{(1+e^x)^2} = f(x)
 \]
 Из того этого следует, что \textbf{математическое ожидание, а так же мода и медиана равны нулю}. Более того, так как функция плотности симметрична относительно \textbf{нулевого} математического ожидания, \textbf{центральный и начальный моменты третьего порядка равны между собой и равны нулю.} Можно было выписать интегралы для математического ожидания и третьего начального момента и сослаться на нечетность функции.





\begin{kframe}


{\ttfamily\noindent\bfseries\color{errorcolor}{\#\# Error: Cannot create:\\\#\# 	 R\_plots/logis\_pdf.tikz \\\#\# Because the directory does not exist or is not writable.}}\end{kframe}
\includegraphics[width=\maxwidth]{figure/logis_pdf-1} 


\begin{figure}
\begin{tikzpicture}[scale = 0.025]
  \input{R_plots/logis_pdf.tikz}
\end{tikzpicture}
\end{figure}



\end{enumerate}


\subsubsection*{Часть 2}

\begin{flushright}
 — Это невозможно! \\
— Нет. Это необходимо.\\
\textcopyright \hspace{0.1cm} Interstellar
\end{flushright}

\begin{enumerate}
\item
Алгоритм решения: рисуешь дерево $\rightarrow$ PROFIT

\begin{center}

 \begin{tikzpicture}[->,>=stealth',shorten >=1pt,auto,node distance=3cm,
  thick,main node/.style={circle,fill=blue!20,draw,font=\sffamily\Large\bfseries}]

  \node[main node] (1) {1};
  \node[main node] (2) [below of=1] {2};
  \node[main node] (3) [below of=2] {3};

  \path[every node/.style={font=\sffamily\small}]
    (1) edge [loop right] node {«не 6»} (1)
        edge [bend right] node[left] {«6»} (2)
    (2) edge [bend right] node[right] {«не 6»} (1)
        edge [above] node[left] {«6»} (3);
\end{tikzpicture}

\end{center}

Комментарии к построению дерева: состояние 1 — начальное, состояние 3 — конец игры, когда выпало две «шестерки» подряд. Заметим, что выпадение любой «нешестерки» в процессе игры приводит нас к состоянию, эквивалентному начальному.

Вероятность выпадения «шестерки» равна 1/6, «нешестерки» — 5/6.

Теперь мы готовы оседлать коня!

\begin{enumerate}
\item $\P(N = 1) = 0$ — невозможно за ход закончить игру.

$\P(N = 2) = \frac{1}{36}$

$\P(N = 3) = \frac{5}{6} \cdot \frac{1}{6} \cdot \frac{1}{6} = \frac{5}{216}$

\item А теперь будет видна вся сила рисования дерева:

Пусть $\E_1$ — число ходов, за которое мы ожидаем закончить игру, если игра начинается в состоянии 1, $\E_2$ — число ходов, за которое мы ожидаем закончить игру, если игра начинается в состоянии 2.

Получим два уравнения:
$\begin{cases} \E_2 = \frac{1}{6} \cdot 1 +  \frac{5}{6} (\E_1 + 1)   \\ \E_1 =  \frac{5}{6} (\E_1 + 1) + \frac{1}{6} ( \E_2 + 1) \end{cases} $

Решив эту систему, получим, что $\E_1 = 42$. А ведь это и есть $\E(N)$.

Аналогична логика для оставшихся мат. ожиданий.

Найдем математическое ожидание суммы набранных очков. Ясно, что если выпадает «не 6», то мы ждем 3 очка. Тогда переопределив $\E_1$ и $\E_2$ следующим образом: пусть $\E_1$ — число набранных очков, которое мы ожидаем получить за игру, если игра начинается в состоянии 1, $\E_2$ — число набранных очков, которое мы ожидаем получить за игру, если игра начинается в состоянии 2.

Новые два уравнения:
$\begin{cases} \E_2 = \frac{1}{6} \cdot 6 +  \frac{5}{6} (\E_1 + 3)   \\ \E_1 =  \frac{5}{6} (\E_1 + 3) + \frac{1}{6} ( \E_2 + 6) \end{cases} $

Решаем и получаем: $\E(S) = \E_1 = 147$

А можно было сделать еще круче! Выше показано, что  $\E(N) = 42$. А сколько мы ждем очков за 1 ход? 3.5! Тогда $\E(S) = \E(N) \cdot 3.5 = 147$

Применяя схожую логику для $\E(N^2)$:\\
\[\E(N^2) = \frac{5}{6} \cdot \E\left((N + 1)^2\right) + \frac{1}{6} \cdot \frac{5}{6}  \cdot \E\left((N + 2)^2\right) + \frac{1}{6} \cdot \frac{1}{6} \cdot 2^2\]

Учитывая, что $\E(N) = 42$, получим: $\E(N^2) = 3414$.

\item Veni, vidi, vici
\begin{center}
  \begin{tabular}{@{}cc@{}}
  \toprule
  $X_n$       & $6$ \\ \midrule
  $\P(\cdot)$ & $1$ \\ \bottomrule
  \end{tabular}
\end{center}

\end{enumerate}

\item
\begin{enumerate}
\item $\P(V = 1) = 1/30$, т.к. именно этому равна вероятность того, что Вовочка стоит ровно вторым в очереди;

$M = 1$ значит, что между Машенькой и Вовочкой ровно один человек в очереди. Если Вовочка находится от 3 (включительно) до 28 позиции в очереди, то для Машеньки есть две благоприятные позиции для события $M = 1$ (например, если Вовочка стоит на 15 месте, то благоприятные позиции для Машеньки — стоять либо 13-ой, либо 17-ой). Если же Вовочка стоит на других позициях в очереди, то для Машеньки существует ровно одна благоприятная позиция:

\[\P(M = 1) = \frac{26}{30} \cdot \frac{2}{29} +  \frac{4}{30} \cdot \frac{1}{29} = \frac{56}{30\cdot 29} = \frac{28}{435}\]

$M = V$ произойдет только, если Машенька стоит за Вовочкой. При этом для Машеньки существует только одна благоприятная позиция и только в том случае, что Вовочка стоит до 15 позиции (включительно):
\[\P(M = V) = \frac{1}{2} \cdot \frac{1}{29} = \frac{1}{58} \]

\item \[\E(V) = \frac{0 + 1 + \ldots + 29}{30} = \frac{30\cdot 14 + 15}{30} = 14.5\]

Для $\E(M)$ можно решить в лоб, и получится красивая сумма, а можно вот так:

Сначала случайно кинем Вовочку и Машеньку на две из 30 позиций в очереди. Образуется три отрезка: точки между Вовочкой и Машенькой и два крайних отрезка (может быть, отрезок из 0 точек). Затем будем закидывать в очередь на оставшиеся позиции случайно 28 оставшихся людей (назовем их «пропавшими»). Т.к. все броски были случайны (или из соображений симметрии, как хотите), вероятность попасть в отрезок между Машенькой и Вовочкой для «пропавшего» равна $1/3$, вне отрезка — соответственно $2/3$, и независима от остальных бросков (!).

Введем случайную величину $X_i$ для $i$-го «пропавшего», которая равна $1$, если он попал в отрезок между Машенькой и Вовочкой, $0$, если не попал:


\begin{center}
\begin{tabular}{ccc}
\toprule
$X_i$ & $1$ & $0$ \\ \midrule
$\P(\cdot)$ & $1/3$ & $2/3$ \\ \bottomrule
\end{tabular}

\end{center}


Легко считается: $\E(X_i) = 1/3$, $\E(X^2_i) = 1/3$, $\Var(X_i) = 1/3 - 1/9 = 2/9$.
Ясно, что $M = \sum_1^{28} X_i$. Тогда учитывая независимость $X_i$:

\[\E(M) = \frac{28}{3}\]
\[\Var(M) = \frac{56}{9}\]
\end{enumerate}

\item
Биномиальное распределение — \textit{À l’abordage!}.

Задача интерпретируется так: последний ход — это когда мы обратились к коробку, в котором нет спичек (то есть к одному коробку нужно обратиться $n+1$ раз).

\begin{enumerate}
\item Пусть $\xi$ — это случайная величина, обозначающая число оставшихся спичек в непустом коробке перед последним ходом.

Если $0<k \leqslant n$, будем считать успехом — попадание в коробок, к которому мы на последнем ходу игры (пустому коробку) обратились. До этого момента из него было вытащено $n$ спичек, а из другого $n-k$ спичек, то есть спички брались $2n - k$ раз.
Таким образом, перед последним ходом произошло $n$ успехов и $n-k$ неудач.
\[
\P(\xi = k) = C_{2n-k}^{n-k} = \left(\frac{1}{2}\right)^{n-k} \left(\frac{1}{2}\right)^{n} = C_{2n-k}^{n-k} \left(\frac{1}{2}\right)^{2n-k}
\]
Теперь нужно учесть, что на последнем ходе был выбран именно пустой коробок. Вероятность этого события — $1/2$, значит, искомая вероятность равна:
\[
\P(\text{в одном коробке осталось k спичек}) =  C_{2n-k}^{n-k} \left(\frac{1}{2}\right)^{2n-k} \cdot \frac{1}{2} = C_{2n-k}^{n-k} \left(\frac{1}{2}\right)^{2n-k+1}
\]
%Успехов — $n + 1$ (вытащено $n$ спичек, и на последнем ходу мы к нему обратились). По формуле Бернулли получаем следующее ($X$ — случайная величина, показывающая сколько спичек осталось в коробке, к которому мы не обратились на последнем ходу игры):
%\[\P(X = k) = C^{n+1}_{2n-k+1} \left(\frac{1}{2} \right)^{2n-k+1}\]

%Если $k = 0$, то мы вытащили все спички из обоих коробков к последнему ходу, и нам без разницы к какому коробку мы обратимся на последнем шагу, т.е.:
%\[\P(X = 0) =2 C^{n+1}_{2n+1} \left(\frac{1}{2} \right)^{2n+1}\]

\item Среднее спичек в другом коробке:

\[\E(X) = \sum \limits_{k=1}^{n} k \cdot C^{n-k}_{2n-k} \left(\frac{1}{2} \right)^{2n-k+1}\]


\end{enumerate}


\item
Для того чтобы количество упаковок, которые необходимо купить, равнялось 50, нужно чтобы ни одну из наклеек Покупатель не встретил дважды, поэтому:
\[
\P(X=50) = 1\cdot\frac{49}{50}\cdot\frac{48}{50}\cdot\dots\cdot\frac{1}{50} = \frac{49!}{50^{49}} \approx 3.4\cdot
10^{-21}\] \vspace{-1cm}

\hspace{10.5cm}\fcolorbox{ForestGreen}{white}{Dum spiro, spero!}\footnote[2]{Надежда умирает последней!}

Теперь введем понятие «шаг». Переход на новый шаг происходит в тот момент, когда покупатель получил наклейку, которой у него раньше не было. Начинаем с шага 0, когда нет ни одной наклейки, и шагать будем до 49, потому что в момент перехода на шаг 50 Покупатель получит последнюю необходимую наклейку и «прогулка» закончится. Введем случайную величину $X_q$ равную количеству покупок в течение шага номер $q$. Тогда $X = \sum \limits_{q=0}^{49}X_q$.  Найдем математическое ожидание $X_q$:
\[
\E(X_q) = \frac{n-q}{n}\cdot 1 + \frac{q}{n}\cdot\frac{n-q}{n}\cdot 2 + \left(\frac{q}{n}\right)^2\cdot\frac{n-q}{n}\cdot 3 + \ldots
\]
здесь $\frac{n-q}{n}$ —  это вероятность найти наклейку, которой еще нет, а $\frac{q}{n}$, соответственно — вероятность повториться. Вопрос теперь в том, как посчитать сумму:
\[
\E(X_q) = \frac{n-q}{n}\left( 1 + \frac{q}{n}\cdot 2 + \left(\frac{q}{n}\right)^2 \cdot 3 + \ldots\right) = \frac{n-q}{n}\cdot\sum\limits_{k=0}^{\infty}\left(\frac{q}{n}\right)^k(k+1)
\]

Можем выписать в столбик несколько первых членов вышестоящей суммы:
\[
\begin{array}{l}
\hspace{0.3cm}1 \\
\vspace{0.2cm}
\left(\frac{q}{n}\right)^1  + \left(\frac{q}{n}\right)^1  \\
\vspace{0.2cm}
\left(\frac{q}{n}\right)^2 + \left(\frac{q}{n}\right)^2  + \left(\frac{q}{n}\right)^2 \\
\left(\frac{q}{n}\right)^3 + \left(\frac{q}{n}\right)^3 + \left(\frac{q}{n}\right)^3 + \left(\frac{q}{n}\right)^3 \\
\hspace{0.1cm}\cdots\cdots\cdots\cdots\cdots\cdots\cdots\cdots\cdots\cdots\cdots
\end{array}
\]
Достаточно! Можем скомпоновать всю сумму другим способом, а именно — по столбцам. Заметим, что сумма элементов в каждом столбце это сумма бесконечно убывающей геометрической прогрессии с одним и тем же знаменателем $\frac{q}{n}$ и различными первыми членами. Соответственно:

\[
\sum\limits_{k=0}^{\infty}\left(\frac{q}{n}\right)^k(k+1) = \frac{1}{1-\frac{q}{n}} + \frac{\frac{q}{n}}{1-\frac{q}{n}} + \frac{\left(\frac{q}{n}\right)^2}{1-\frac{q}{n}} + \frac{\left(\frac{q}{n}\right)^3}{1-\frac{q}{n}} + \dots =
\]
\[
= \frac{1}{1-\frac{q}{n}}\left( 1 + \frac{q}{n} + \left(\frac{q}{n}\right)^2 + \left(\frac{q}{n}\right)^3 + \dots\right) = \frac{n}{n-q}\cdot\frac{n}{n-q} = \left( \frac{n}{n-q}\right)^2
\]

Таким образом, получаем, что:
\[
\E(X_q) = \frac{n-q}{n}\cdot \left( \frac{n}{n-q}\right)^2 = \frac{n}{n-q}
\]
\hspace{10cm} и это верно для любого q!

\[
\E(X) = \E\left(\sum \limits_{q=0}^{49}X_q\right) = \sum \limits_{q=0}^{49}\E(X_q) =
\frac{50}{50-0} + \frac{50}{50-1} + \dots + \frac{50}{50-49} = 50\left(\frac{1}{50} + \frac{1}{49} + \dots + 1\right) \approx
\]
\[
\approx 50\int\limits_{1}^{50}\frac{1}{x}\mathbf{d}x = 50\ln(50) \approx 195.5
\]

А теперь ещё одно решение:


Величины $X_q$ независимы (но по разному распределены). Если долго пришлось ждать $i$-го шага, это ничего не говорит о $j$-ом шаге. Величины $X_q$ имеют известный закон распределения — это число опытов до первого успеха при заданной вероятности успеха. Это геометрическое распределение, математическое ожидание которого равно $\frac{1}{p}$, а дисперсия: $\frac{1-p}{p^2}$, где $p$ — \vspace{0.2cm}  вероятность успеха.

А те, кто забыл, могут \textbf{проще решить} методом первого шага:
Если $X$ — число опытов до успеха при вероятности успеха $p$, то
\[
\E(X)=p\cdot 1 + (1-p)\cdot \E(X+1)
\]
Откуда $\E(X)=\frac{1}{p}$ и дело в шляпе :)
Аналогично:
\[
\E(X^2)=p\cdot 1^2 + (1-p) \cdot \E((X+1)^2)
\]
и решая, находим $\E(X^2)$.



\item
\begin{enumerate}
\item Необходимое и достаточное условие — старушка не должна занять чужое место. С вероятностью $\frac{1}{n}$ она угадает свое место, значит, для каждого входящего его место будет свободно и он туда сядет.\\
\textbf{Ответ:} $\frac{1}{n}$
\item Будем искать вероятность того, что последний человек не сядет на свое место.

Пусть $A_i = \{\text{Старушка села на  место } i\text{-го} \}$,  $B_{(i,j)} = \{i \text{-ый  пассажир сел на место } j\text{-ого} \}$

\[
P[n\text{-ый не сядет на свое место}] = \P(A_n) + P[A_{n-1}]P[B_{(n-1,n)}]+
\]
\[
+ P[A_{n-2}](P[B_{(n-2,n)}]
+ P[B_{(n-2,n-1)}]P[B_{(n-1,n)}]  ) + \dots
\]

Можем заметить, что:
\renewcommand{\labelitemi}{$\checkmark$}
\begin{itemize}
\item $\P[A_i] = P[A_j] = \frac{1}{n}$ $\forall \hspace{0.1cm} i, j$
\item $\P[B_{(n-1,n)}]=\frac{1}{2}$, потому что $n-1$-ый выбирает из двух оставшихся мест
\item $\P[B_{(n-2,n)}]
+ \P[B_{(n-2,n-1)}]P[B_{(n-1,n)}]  = \frac{1}{3} + \frac{1}{3}\cdot \frac{1}{2} = \frac{1}{2}$
\item
\begin{multline*}
\P[B_{(n-3,n)}] + \P[B_{(n-3,n-2)}](\P[B_{(n-2,n)}]+\P[B_{(n-2,n-1)}]\P[B_{(n-1,n)}])+\\
+ \P[B_{(n-3,n-1)}]\P[B_{(n-1,n)}] =   \frac{1}{4}+\frac{1}{4}\left(\frac{1}{3}+\frac{1}{3}\cdot\frac{1}{2}\right) +\frac{1}{4}\cdot \frac{1}{2} = \frac{1}{2}
\end{multline*}
\item И так далее до того момента, пока старушка не сядет на место первого человека, который заходит после нее, — всего $n-2$ вариантов.
\end{itemize}

Таким образом мы получаем сумму:
\[
\P[n\text{-ый не сядет на свое место}] = \frac{1}{n} + \frac{1}{n}\cdot \frac{1}{2} + \frac{1}{n}\cdot \frac{1}{2} + \dots = \frac{1}{n}  + \frac{1}{2n}(n-2) = \frac{1}{2}
\]
\begin{center}
\fcolorbox{ForestGreen}{white}{
Значит вероятность $\P[n\text{-ый сядет на свое место}] = 1 -\frac{1}{2} = \frac{1}{2}$}
\end{center}

А вот ещё один вариант решения:

\underline{Метод математической индукции:} допустим что это утверждение доказано для одного, двух и так далее до $k$ человек. Рассмотрим $k+1$ человека. Когда последний сядет на своё место? Если старушка сядет на своё место, а вероятность этого равна $\frac{1}{k+1}$ или, с вероятностью $\frac{1}{2}$ (по индукции), если старушка сядет на любое место кроме своего и последнего, то есть $\frac{1}{2}\cdot\frac{k-1}{k+1}$. В этом случае тот\vspace{0.2cm} пассажир, чье место  она заняла, становится старушкой, и мы получаем задачу при меньшем $k$. Складывая эти две дроби, получаем $\frac{1}{2} $.

Чтобы найти среднее число пассажиров, разобьем эту величину в сумму индикаторов: $Y_1$ — сел ли первый на место, $\dots$, $Y_n$ — сел ли $n$-ый на место (индикатор равен единице, если сел).

Стало быть $\E(Y)=\E(Y_1)+\E(Y_2)+\ldots+\E(Y_n)$. $\E(Y_n)=\frac{1}{2}$.

Почти аналогично можем рассуждать для предпоследнего:

База индукции: если пассажиров трое ($n=3$ включая старушку), то для предпоследнего вероятность сесть на своё место равна $\frac{2}{3}$.

Шаг индукции: допустим что для $3, 4, \ldots n$ пассажиров эта вероятность равна $\frac{2}{3}$.
Рассмотрим случай $(n+1)$-го пассажира.
Предпоследний сядет на своё место, если:

\renewcommand{\labelitemi}{\textbullet}

\begin{itemize}
\item старушка сядет на своё место или на место последнего $\frac{2}{n+1}$
\item в $\frac{2}{3}$ тех случаев, когда старушка сядет на место $2, 3, \ldots, (n-1)$, т.е. $\frac{2}{3}\cdot \frac{n-2}{n+1}$
складываем, получаем $\frac{2}{3}$.
То есть по индукции вероятность того, что предпоследний сядет на своё место равна $\frac{2}{3}$
\end{itemize}
И по аналогии можно увидеть, что вероятность того, что $k$-ый с конца пассажир сядет на своё место равна $k/(k+1)$

Если у нас $n$ пассажиров включая СС, то среднее количество севших на свои места (раскладывая с конца) равно \[\frac{1}{2}+\frac{2}{3}+\frac{3}{4}+\dots+\frac{n-1}{n}+\frac{1}{n}\]

\end{enumerate}

\end{enumerate}



\subsection{Контрольная работа 2. Базовый поток. 15.12.2014}


\begin{enumerate}
\item Ежемесячные расходы студенческой семьи Маши и Васи хорошо описываются случайным
вектором $(X,Y)$, ($X$ — расходы Маши, $Y$ — расходы Васи), имеющим равномерное
распределение в треугольнике, задаваемом ограничениями $\{0 \leq X, \; 0\leq Y, \; X+Y \leq 1 \}$.

Найдите:

\begin{enumerate}
\item Вероятность того, что совокупные расходы превысят половину бюджета, $\P(X+Y>1/2)$
\item Плотность распределения расходов Васи.
\item Вероятность того, что Машины расходы составили менее трети бюджета, если
известно, что Вася израсходовал более половины семейного бюджета.
\item Условную плотность распределения и условное математическое ожидание расходов Маши, при условии, что Вася израсходовал половину бюджета.
\item Математическое ожидание условного математического ожидания расходов Маши, $\E(\E(X|Y))$
\item Коэффициент корреляции расходов Маши и Васи
\end{enumerate}

\item Задана последовательность независимых случайных величин $X_1$, $X_2$, \ldots

\begin{tabular}{llll}
\toprule
$X_n$ & $-\sqrt{n}$ & $0$ & $\sqrt{n}$ \\ \midrule
$\P(\cdot)$ & $1/2n$ & $1-1/n$ & $1/2n$ \\
\bottomrule
\end{tabular}

\begin{enumerate}
\item Сформулируйте закон больших чисел. Выполняется ли для данной последовательности
закон больших чисел?
\item Запишите неравенство Чебышёва. Оцените вероятность того, что модуль среднего
значения по $n$ наблюдениям не превысит $1$, $\P(|\bar X_n| \leq 1)$
\item Сколько членов последовательности необходимо взять, чтобы вероятность того, что
модуль среднего значения не превысит $1$, была не менее $0.9$, $\P(|\bar X_n| \leq 1)\geq 0.9$
\end{enumerate}

\item Размер выплат каждому клиенту банка — случайная величина с математическим
ожиданием, равным 5000 ед. и среднеквадратическим отклонением, равным 2000 ед.
Выплаты отдельным клиентам независимы. Сколько должно быть наличных денег в банке,
чтобы с вероятностью 0.95 денег хватило на обслуживание 60 клиентов?

\item Рекламная компания хочет оценить вероятность $p$, с которой адресная реклама приводит к
заявке. С этой целью она  рассылает $n$ рекламных проспектов. Обозначим за $\hat p$ отношение
числа поданных заявок к числу разосланных проспектов $n$. С помощью теоремы Муавра–Лапласа и неравенства Чебышёва определите:
\begin{enumerate}
\item  Сколько нужно разослать рекламных проспектов, для того чтобы $\hat p$ отличалось от
истинной вероятности $p$ не более, чем на $0.1$ с вероятностью не меньшей $0.99$
\item С какой точностью $\varepsilon$ удастся оценить $p$ с вероятностью 0.99, если разослана 1000
проспектов, т.е. $\P(|\hat p - p|\leq \varepsilon)\geq 0.99$?
\end{enumerate}
\end{enumerate}





\subsection{Контрольная работа 2. Базовый поток. 15.12.2014, решение}


\begin{enumerate}
\item
\begin{enumerate}
\item
Так как $(X, Y)$ имеют совместное равномерное распределение, $\P\left\{X+Y > \frac{1}{2}\right\}$ можно рассчитать как отношение соответствующих площадей:
\begin{center}
\definecolor{zzttqq}{rgb}{0.6,0.2,0.}
\begin{tikzpicture}[line cap=round,line join=round,>=triangle 45,x=5.692307692307692cm,y=5.692307692307692cm]
\draw[->,color=black] (-0.1,0.) -- (1.2,0.);
\foreach \x in {,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.,1.1}
\draw[shift={(\x,0)},color=black] (0pt,2pt) -- (0pt,-2pt) node[below] {\footnotesize $\x$};
\draw[->,color=black] (0.,-0.1) -- (0.,1.2);
\foreach \y in {0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.,1.1}
\draw[shift={(0,\y)},color=black] (2pt,0pt) -- (-2pt,0pt) node[left] {\footnotesize $\y$};
\draw[color=black] (0pt,-10pt) node[right] {\footnotesize $0$};
\clip(-0.1,-0.1) rectangle (1.2,1.2);
\fill[color=zzttqq,fill=zzttqq,fill opacity=0.1] (0.,0.5) -- (0.5,0.) -- (1.,0.) -- (0.,1.) -- cycle;
\draw (0.,1.)-- (1.,0.);
\draw [color=zzttqq] (0.,0.5)-- (0.5,0.);
\draw [color=zzttqq] (0.5,0.)-- (1.,0.);
\draw [color=zzttqq] (1.,0.)-- (0.,1.);
\draw [color=zzttqq] (0.,1.)-- (0.,0.5);
\draw (0.344196516991,0.436512272899) node[anchor=north west] {$S_0$};
\draw (0.129676687465,0.218325437741) node[anchor=north west] {$S_1$};
\draw (0.0233335241101,1.16441289103) node[anchor=north west] {$y$};
\draw (1.06109611823,0.08) node[anchor=north west] {$x$};
\end{tikzpicture}
\end{center}

Соответственно: \[\P\left(X+Y > \frac{1}{2}\right) = \frac{S_0}{S_0+S_1} = \frac{0.5-S_1}{0.5} = \frac{\frac{1}{2}-\frac{1}{8}}{\frac{1}{2}} = \frac{3}{4}\]

\item
\[
f_Y(y) = \int \limits_{0}^{1-y} f_{XY}(x,y) dx
\]

Поэтому, нам сначала нужно найти $f_{XY}(x,y)$, которая для равномерного распределения должна быть константой. Это можно сделать из условия:
\[
\int\limits_{0}^{1}\int \limits_{0}^{1-x} f_{XY}(x, y) dxdy = \int\limits_{0}^{1}\int \limits_{0}^{1-x} C dxdy = 1 \Rightarrow
\]
\[
\int\limits_{0}^{1}\int \limits_{0}^{1-x} C dxdy = \int\limits_{0}^{1} C(1-x) dx = \left. \left( Cx-C\frac{x^2}{2}\right) \right| _{0}^{1} =
 \frac{C}{2}  = 1\]

 Откуда имеем $f_{XY}(x, y) = C = 2$. Теперь можем найти плотность распределения расходов Васи:
 \[ f_Y(y) = \int \limits_{0}^{1-y} 2 dx = 2(1-y) \]



\item В данном случае площади немного другие, но смысл тот же:

\begin{center}
\definecolor{zzttqq}{rgb}{0.6,0.2,0.}
\begin{tikzpicture}[line cap=round,line join=round,>=triangle 45,x=5.692307692307692cm,y=5.692307692307692cm]
\draw[->,color=black] (-0.1,0.) -- (1.2,0.);
\foreach \x in {,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.,1.1}
\draw[shift={(\x,0)},color=black] (0pt,2pt) -- (0pt,-2pt) node[below] {\footnotesize $\x$};
\draw[->,color=black] (0.,-0.1) -- (0.,1.2);
\foreach \y in {,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.,1.1}
\draw[shift={(0,\y)},color=black] (2pt,0pt) -- (-2pt,0pt) node[left] {\footnotesize $\y$};
\draw[color=black] (0pt,-10pt) node[right] {\footnotesize $0$};
\clip(-0.1,-0.1) rectangle (1.2,1.2);
\fill[color=zzttqq,fill=zzttqq,fill opacity=0.1] (0.,0.5) -- (0.,1.) -- (0.333333333333,0.666666666667) -- (0.333333333333,0.5) -- cycle;
\draw (0.,1.)-- (1.,0.);
\draw[dashed] (1/3, 2/3) -- (1/3,0);
\draw (0.1004007648034,0.729040237615) node[anchor=north west] {$S_0$};
\draw (0.343364031073,0.5908861537646) node[anchor=north west] {$S_1$};
\draw (0.0233335241101,1.16441289103) node[anchor=north west] {$y$};
\draw (1.06109611823,0.08) node[anchor=north west] {$x$};
\draw (0.,0.5)-- (0.5,0.5);
\draw [color=zzttqq] (0.,0.5)-- (0.,1.);
\draw [color=zzttqq] (0.,1.)-- (0.333333333333,0.666666666667);
\draw [color=zzttqq] (0.333333333333,0.666666666667)-- (0.333333333333,0.5);
\draw [color=zzttqq] (0.333333333333,0.5)-- (0.,0.5);
\end{tikzpicture}
\end{center}


\[\P\left( \left. X<\frac{1}{3} \hspace{1mm} \right| Y>\frac{1}{2}\right) = \frac{S_0}{S_0+S_1} = \frac{\frac{1}{8} - S_1}{\frac{1}{8}} = \frac{\frac{1}{8}-\frac{1}{72}}{\frac{1}{8}} = \frac{8}{9}\]

\item При $Y = \frac{1}{2}$, $X$ распределен равномерно от 0 до $\frac{1}{2}$, поэтому его плотность равна \[f_X(x) = \frac{1}{\frac{1}{2} - 0} = 2\]
Соответственно, условное математическое ожидание:
\[
\E \left( X| Y =\frac{1}{2}\right) = \frac{1}{4}
\]

\item $\E(\E(X|Y)) = \E(X)$, а маргинальную функцию плотности для $X$ мы можем найти так же, как искали для $Y$, и получим $f_X(x) = 2(1-x)$. Отсюда:
\[
\E(X) = \int \limits_{0}^{1} 2x(1-x)dx = \left .\left(x^2 - \frac{2}{3}x^3\right) \right|^{1}_{0} = \frac{1}{3}
\]

\item Если вспомнить формулу для корреляции:
\[
\rho_{XY} = \frac{\Cov(X, Y)}{\sigma_X\sigma_Y}  = \frac{\E(XY) - \E(X)\E(Y)}{\sigma_X\sigma_Y}
\]

то станет более-менее очевидно, что надо найти $\E(XY)$ и дисперсии $X$ и $Y$.

\[
\E(XY) = \int \limits_{0}^{1} \int \limits_{0}^{1-x} 2xy dxdy = \int \limits_{0}^{1} 2xdx \int \limits_{0}^{1-x}ydy =  \int \limits_{0}^{1}x(x^2-2x+1)dx =
\]
\[
= \left. \left(\frac{x^4}{4} - \frac{2}{3}x^3 + \frac{x^2}{2}\right) \right|^{1}_{0} = \frac{3}{4}-\frac{2}{3} = \frac{1}{12}
\]

Соответственно:

\[
\Cov(X, Y) = \frac{1}{12} - \frac{1}{3}\cdot \frac{1}{3} = -\frac{1}{36}
\]

Найдем теперь дисперсии $X$ и $Y$ (они будут одинаковыми, как и математические ождания, в силу симметрии):

\[
\E(X^2) = \int \limits_{0}^{1} 2x^2(1-x)dx = \left. \left( \frac{2}{3}x^2 - \frac{x_4}{2} \right) \right|_{0}^{1} = \frac{1}{6}
\]

Поэтому:
\[
\Var[X] = \E(X^2) - (\E(X))^2 = \frac{1}{6} - \frac{1}{9} = \frac{1}{18}
\]

Теперь наконец-то можем найти корреляцию:
\[
\rho_{XY} = -\frac{\frac{1}{36}}{\sqrt{\frac{1}{18}}\sqrt{\frac{1}{18}}} = -\frac{1}{2}
\]
\end{enumerate}

\item

\begin{enumerate}

\item Закон больших чисел гласит, что $\bar{X} \rightarrow
\E(X)$ при $n\rightarrow \infty$. Проверим его выполнение в данном случае:
\[
\E(X_n) = \frac{1}{2n}(-\sqrt{n}) + \left(1-\frac{1}{n}\right)\cdot0 + \frac{1}{2n}\sqrt{n} = 0
\]

\[
\lim\limits_{n\rightarrow\infty} \bar{X} = \lim\limits_{n\rightarrow\infty} \frac{X_1 +\dots + X_n}{n} = 0
\]
так как числитель ограничен, а знаменатель бесконечно возрастает.
Видим, что ЗБЧ в данном случае, конечно, выполняется.

Как вариант, можно было сказать, что дисперсия ограничена, и из этого также следует выполнение ЗБЧ.
\item Неравенство Чебышева:
\[
\P(|X-\E(X)|\geqslant \varepsilon) \leqslant \frac{\Var(X)}{\varepsilon^2}
\]

Соответственно, искомую вероятность можем оценить следующим образом:
\[
\P(|\bar{X}| \leqslant 1) = 1 -\P(|\bar{X}| \geqslant 1) \Rightarrow \P(|\bar{X}| \leqslant 1) \geqslant 1 - \frac{\Var[\bar{X}]}{1}
\]
\[
\Var[\bar{X}] = \Var\left(\frac{\sum\limits_{i=1}^{n} X_i}{n}\right) = \frac{1}{n^2}\sum \limits_{i=1}^{n} \Var{X_i}
\]
В свою очередь:

\[
\E(X_i^2) = 2\cdot\frac{1}{2n}\cdot n + \left(1-\frac{1}{n}\right)\cdot0 = 1 \Rightarrow \Var[X_i] = 1 \Rightarrow \Var[\bar{X}] = \frac{1}{n}
\]

Поэтому:
\[
\P(|\bar{X}| \leqslant 1)\geqslant 1 - \frac{1}{n}
\]

\item  \[1 - \frac{1}{n} = 0.9  \Rightarrow n = 10\]

\end{enumerate}

\item

Обозначим за $R$ — необходимое количество наличных денег в банке. Пусть $X$ — случайная величина, показывающее размер суммарной выплаты $60$ ($n$ — достаточное большое для применения ЦПТ) клиентам. Ясно, что т.к. выплаты отдельным клиентам независимы: \( \E X = 60 \cdot 5000 = 3\cdot 10^5 \); \( \Var X = 60 \cdot 2000^2 = 2.4 \cdot 10^8 \); \( \sigma_X = \sqrt{2.4} \cdot 10^4 \approx 1.55 \cdot 10^4\)

Теперь по ЦПТ:
\[\P(R \geqslant X) = 0.95 \]
\[\P \left(\frac{X - \E X}{\sigma_X} \leqslant \frac{R - \E X}{\sigma_X} \right) = 0.95 \]
\[ \P \left( Z \leqslant \frac{R - 3 \cdot 10^5}{1.55 \cdot 10^4} \right) = 0.95 \]
Слева функция распределения; подставляя 95-\% квантиль стандартного нормального распределения, получаем:
\[ \frac{R - 3 \cdot 10^5}{1.55 \cdot 10^4} = 1.64 \]
\[ R = 325420 \]


\item

\begin{enumerate}
\item По предельной теореме Муавра-Лапласа:
\[ \frac{\hat{p} - p}{\sqrt{p(1-p)/n}} \sim N (0,1) \]
\[ \P \left( \frac{|\hat{p} - p|}{\sqrt{p(1-p)/n}} \leqslant \frac{0.1}{\sqrt{p(1-p)/n}} \right) \geqslant 0.99 \]
\[ \P \left( |Z| \leqslant \frac{0.1}{\sqrt{p(1-p)/n}} \right) \geqslant 0.99 \]
Из симметричности стандартного нормального распределения и зная его 99.5-\% квантиль, равный приблизительно 2.58, получаем:
\[ \frac{0.1}{\sqrt{p(1-p)/n}} \geqslant 2.58 \]
\[ \frac{\sqrt{n}}{\sqrt{p(1-p)}} \geqslant \frac{2.58}{0.1} \]
\[ \sqrt{n} \geqslant \frac{2.58}{0.1} \sqrt{p(1-p)} \]
\[ n \geqslant 665.64 \cdot p(1-p) \]

С помощью неравенства Чебышева:
\[ \P \left( |\hat{p} - p| \leqslant 0.1 \right) \geqslant 0.99 \]
\[ \P \left( |\hat{p} - p| \geqslant 0.1 \right) \leqslant 0.01 \]
Теперь просто смотрим на неравенство Чебышева и на строчку выше, на неравенство Чебышева и на строчку выше\ldots
\[ \frac{p(1-p)/n}{0.1^2} = 0.01\]
\[ n = 10^4 p(1-p) \]
Принимаются оба ответа!

\item По предельной теореме Муавра-Лапласа:
\[ \P \left( \frac{|\hat{p} - p|}{\sqrt{p(1-p)/n}} \leqslant \frac{\varepsilon}{\sqrt{p(1-p)/1000}} \right) \geqslant 0.99 \]
\[ \P \left( |Z| \leqslant \frac{\varepsilon}{\sqrt{p(1-p)/1000}} \right) \geqslant 0.99 \]
Аналогично пункту 1:
\[ \frac{\varepsilon}{\sqrt{p(1-p)/1000}} \geqslant 2.58 \]
\[ \varepsilon \geqslant 0.082 \sqrt{p(1-p)} \]

С помощью неравенства Чебышева:
\[ \P \left( |\hat{p} - p| \leqslant \varepsilon \right) \geqslant 0.99 \]
\[ \P \left( |\hat{p} - p| \geqslant \varepsilon \right) \leqslant 0.01 \]
Аналогично пункту 1:
\[ \frac{p(1-p)/1000}{\varepsilon^2} = 0.01\]
\[ \varepsilon^2 = \frac{p(1-p)}{10} \]
\[ \varepsilon = \sqrt{\frac{p(1-p)}{10}} \approx 0.316 \sqrt{p(1-p)} \]

\end{enumerate}

Нужно было показать, как мастерство владения теоремой Муавра-Лапласа, так и неравенством Чебышева.


\end{enumerate}


\subsection{Праздник номер 2, i-поток, 15.12.2014}

Time: 180 min

\begin{enumerate}
\item Вася может получить за экзамен равновероятно либо $8$ баллов, либо $7$ баллов. Петя может получить за экзамен либо $8$ баллов — с вероятностью $1/3$; либо $7$ баллов — с вероятностью $2/3$. Известно, что корреляция их результатов равна $0.7$.

Какова вероятность того, что Петя и Вася покажут одинаковый результат?

\item В  городе Туме проводят демографическое исследование семейных пар. Стандартное отклонение возраста мужа оказалось равным 5 годам, а стандартное отклонение возраста жены — 4 годам. Найдите корреляцию возраста жены и возраста мужа, если стандартное отклонение разности возрастов оказалось равным 2 годам. В каких пределах лежит вероятность того, что возраст случайно выбираемого женатого мужчины отклоняется от своего математического ожидания больше чем на 10 лет?


\item На окружности единичной длины случайным образом равномерно и независимо друг от друга выбирают две дуги: длины $0.3$ и длины $0.4$.
\begin{enumerate}
\item  Найдите функцию распределения длины пересечения этих отрезков
\item Найдите среднюю длину пересечения
\end{enumerate}


\item  Совместная функция плотности величин $X$ и $Y$ имеет вид
\begin{equation}
\nonumber
f(x,y)=\begin{cases}
2(x^3+y^3), \text{ если } x\in [0;1], y\in [0;1] \\
0, \mbox{ иначе}
\end{cases}
\end{equation}
\begin{enumerate}
\item Найдите $\P(X+Y>1)$
\item Найдите $\Cov(X,Y)$
\item Являются ли величины $X$ и $Y$ независимыми?
\item Являются ли величины $X$ и $Y$ одинаково распределенными?
\end{enumerate}



\item Изначально цена акций компании «Пумперникель» равна $X_0=1000$ рублей. Каждый последующий день в течение 100 дней цена равновероятно может вырасти на 2 рубля или упасть на 1 рубль. Обозначим цену акции через $n$ дней как $X_n$.
\begin{enumerate}
\item Чему равны математическое ожидание и дисперсия изменения цены за отдельный день?
\item Найдите $\E(X_n)$, $\Var(X_n)$, $\Cov(X_n, X_k)$
\item Сформулируйте центральную предельную теорему
\item Примерно найдите вероятность $\P(X_{100}>1060)$
\item Биржевой игрок Вениамин утверждает, что через 100 дней с вероятностью 95\% цена акций «Пумперникель» не опустится ниже $a$. Чему равно $a$?
\end{enumerate}
\item  Сэр Фрэнсис Гальтон —  учёный XIX-XX веков, один из основоположников как
генетики, так и статистики — изучал, среди всего прочего, связь между ростом детей и родителей.  Он исследовал данные о росте 928 индивидов. Обозначим $X_1$ — рост случайного человека, а $X_2$ — среднее арифметическое роста его отца и матери. По результатам исследования Гальтона:


\[
\begin{pmatrix}
X_1 \\
X_2
\end{pmatrix}
\sim
\cN\left[
\begin{pmatrix}
68.1 \\
68.3
\end{pmatrix};
\begin{pmatrix}
6.3 & 2.1 \\
2.1 & 3.2
\end{pmatrix}
\right]
\]

\begin{enumerate}
\item Обратите внимание на то, что дисперсия роста детей выше дисперсии среднего роста
родителей. С чем это
может быть связано? Учтите, что рост детей измерялся уже по достижении
зрелости, так что разброс не должен быть связан с возрастными различиями.
\item Рассчитайте корреляцию между $X_1$ и $X_2$
\item Один дюйм примерно равен $2.54$ сантиметра. Пусть $X_1'$ и $X_2'$ — это те же $X_1$ и $X_2$, только измеренные в сантиметрах. Найдите вектор математических ожиданий и ковариационную матрицу вектора $X'=(X_1', X_2')$.
\item Определите, каков ожидаемый рост и дисперсия роста человека, средний рост родителей которого составляет 72 дюйма?
\item Найдите вероятность того, что рост человека превысит 68 дюймов, если средний рост его родителей равен 72 дюймам. Подсказка: используйте предыдущий пункт и нормальность распределения!
\end{enumerate}

%\item Пуассоновское казино. В пуассоновском казино сигнальная лампочка загорается согласно пуассоновскому потоку в среднем один раз в минуту. В любой момент азартный игрок Вениамин может нажать кнопку. Нажать кнопку Вениамин может только один раз. Вениамин срывает джек-пот,

\item Звонки поступают в пожарную часть согласно пуассоновскому потоку в среднем $2$~раза в час. Предположим, что после получения звонка пожарная часть занята тушением пожара случайное время равномерно распределённое от получаса до часа. В это время звонки перенаправляются в соседнюю пожарную часть.

Пожарная часть только-только начала работать и готова принимать звонки.
\begin{enumerate}
\item Какова вероятность того, что за ближайший час не поступит звонков?
\item Какова вероятность того, что за ближайший час не будет перенаправленных звонков?
\item Найдите закон распределения количества звонков до первого перенаправленного звонка.
\end{enumerate}

\item  Судьба Дон-Жуана


У Дон-Жуана $n$  знакомых девушек, и их всех зовут по-разному. Он пишет
им $n$  писем, но по рассеянности раскладывает их в конверты
наугад. Случайная величина $X$ обозначает количество девушек, получивших письма, адресованные лично им.

\begin{enumerate}
\item Найдите $\E(X)$, $\Var(X)$
\item Какова при большом $n$ вероятность того, что хотя бы одна девушка получит письмо, адресованное ей?
\end{enumerate}

\item Игла Бюффона

Плоскость разлинована параллельными линиями через каждый сантиметр. Случайным образом на эту плоскость бросается иголка длины $a<1$.

\begin{enumerate}
\item Какова вероятность того, что иголка пересечёт какую-нибудь линию?
\item Предложите вероятностный способ оценки числа $\pi$
\end{enumerate}


\end{enumerate}


\subsection{Решение. Праздник номер 2, i-поток}

\begin{enumerate}
\item
Пусть $X$ — оценка Пети, $Y$ — оценка Васи. Тогда исходя из условия:
\begin{center}

\begin{tabular}{ccc}
\toprule
$X$ & $7$ & $8$ \\ \midrule
$\P(\cdot)$ & $\frac{1}{2}$ & $\frac{1}{2}$ \\ \bottomrule
\end{tabular}
\hspace{1cm}
\begin{tabular}{ccc}
\toprule
$Y$ & $7$ & $8$ \\ \midrule
$\P(\cdot)$ & $\frac{2}{3}$ & $\frac{1}{3}$  \\ \bottomrule
\end{tabular}
\end{center}

Теперь можем найти математические ожидания и дисперсии:
\[
\E(X) = \frac{15}{2}, \hspace{0.5cm} \E(Y) = \frac{22}{3} \Rightarrow
\]
\[
\Var[X] = \frac{1}{2}\cdot 64 + \frac{1}{2}\cdot 49 - \left(\frac{15}{2}\right)^2 = \frac{1}{4}
\]
\[
\Var[Y] = \frac{1}{3}\cdot 64 + \frac{2}{3}\cdot 49 - \left(\frac{22}{3}\right)^2 = \frac{2}{9}
\]

Теперь из формулы для корреляции мы можем найти $\E(XY)$:

\[
0.7 = \frac{\E(XY)-\frac{15}{2}\cdot\frac{22}{3}}{\sqrt{\frac{1}{4}}\sqrt{\frac{2}{9}}} \Rightarrow \E(XY) \approx 55.16499
\]

Можем составить табличку для совместного распределения, немножко подумав:

\begin{center}
\begin{tabular}{@{}lccr@{}}
\toprule
$Y$ \textbackslash $X$ & $7$             & $8$             & $\sum$        \\ \midrule
$7$                              & $p$             & $\frac{1}{2}-p$ & $\frac{1}{2}$ \\
$8$                              & $\frac{2}{3}-p$ & $p-\frac{1}{6}$ & $\frac{1}{2}$ \\
$\sum$                           & $\frac{2}{3}$   & $\frac{1}{3}$   &               \\ \bottomrule
\end{tabular}
\end{center}

\[
\E(XY) = 49p+56\left(\frac{1}{2} - p + \frac{2}{3}-p\right) + 64\left(p-\frac{1}{6}\right) = 55.16499
\]

\[
\Rightarrow p \approx 0.4983233 \Rightarrow \P(X=Y) = p + p-\frac{1}{6} = 0.8299799
\]



\item

Пусть $M$ — возраст мужа, $F$ — возраст жены. Тогда из условия:
\[
\Var(M-F) = \Var(M) + \Var(F) - 2\Cov(M, F) = 4 \Rightarrow \Cov(M, F) = \frac{37}{2}
\]

\[
\rho_{MF} = \frac{\frac{37}{2}}{5\cdot4} = \frac{37}{40}
\]


Согласно неравенству Чебышева:
\[
\P(|M-\E(M)|\geqslant10) \leqslant\frac{\Var(M)}{10^2} = 0.25
\]

Поэтому данная вероятность лежит в пределах $(0, 25]$.

\renewcommand{\labelenumii}{(\alph{enumii})}
\item
\begin{enumerate}
\item Пусть $X$ — длина пересечения. Требуется найти $\P(X\leqslant x)$. Рассмотрим расположение центров отрезков относительно друг друга:

\begin{center}
\definecolor{zzttqq}{rgb}{0.6,0.2,0.}
\begin{tikzpicture}[line cap=round,line join=round,>=triangle 45,x=7cm,y=7]
\draw[color=black] (0.,0.) -- (1.1,0.);
\foreach \x in {0,0.5,0.3,1.1}
\draw[shift={(\x,0)},color=black, line width= 1pt] (0pt,2pt) -- (0pt,-2pt) node[below] {};
\draw (0.25,0.) node[circle, inner sep = 1pt,  fill] {};
\draw (0.7,0.) node[circle, inner sep = 1pt,  fill] {};
\draw[<->, color = black] (0,-2) -- (0.25, -2) ;
\draw[<->, color = black] (0.25,-2) -- (0.7, -2) ;
\draw[<->, color = black] (0.7,-2) -- (1.1, -2) ;
\draw[color=black, dashed] (0,0) -- (0,-2);
\draw[color=black, dashed] (0.25,0) -- (0.25,-2);
\draw[color=black, dashed] (0.7,0) -- (0.7,-2);
\draw[color=black, dashed] (1.1,0) -- (1.1,-2);
\draw (0.125,-2) node[below] {0.15};
\draw (0.4,-2) node[below] {$R$};
\draw (0.8,-2) node[below] {0.2};
\draw[color = red, line width = 2pt] (0.3, 0) -- (0.5, 0);

\end{tikzpicture}
\end{center}

Заматим, что $X = 0.15-(R-0.2) = 0.35-R$. Однако, $R \sim U\left[0, \frac{1}{2}\right]$. Можно представить, что эти точки бросают на окружность по очереди, тогда расстояние между ними не может превышать $\frac{1}{2}$ и распределено равномерно. Имеем:
\[
\P(X \leqslant x) = \P(0.35-R\leqslant x) = \P(R \geqslant 0.35-x) = \frac{0.5-0.35+x}{0.5} = 0.3+2x
\]

Строго говоря, длина пересечения не может быть больше 0.3 по понятным причинам, поэтому функция распределения выглядит так:
\[
F(x) = \begin{cases}
0.3+2x, & x < 0.3\\
1, & x \geqslant 0.3
\end{cases}
\]

\item Зная функцию распределения, можем найти плотность:
\[f_X(x) = \begin{cases}
2, & x < 3\\
0, & \text{else}
\end{cases}\]

Сответственно:
\[
\E(X) = \int \limits_{0}^{0.3} 2x dx = \left.  x^2 \right|_{0}^{0.3} = 0.09
\]
\end{enumerate}



\item

\begin{enumerate}
\item \[\P(X+Y > 1) = \iint \limits_{\mathcal{G}}2(x^3+y^3)dxdy = \int \limits_{0}^{1} dx \int \limits_{1-x}^{1}2(x^3+y^3)dy = \ldots  = 0.8\]
\item Для того, чтобы найти ковариацию, придется найти :
\[\E(X) = \int\limits_{0}^{1} dx \int\limits _{0}^{1}2x(x^3+y^3)dy = \ldots = 0.65\]
\[\E(Y) = \int\limits_{0}^{1} dy \int\limits_{0}^{1}2y(x^3+y^3)dx = \ldots = 0.65 \]
\[\E(XY) = \int\limits_{0}^{1}dx\int\limits_{0}^{1}2xy(x^3+y^3)dy = \ldots = 0.4\]

Ну а потом все просто: $\Cov(X, Y) = \E(XY) - \E(X)\E(Y) = -0.0225$

\item Проверить свойство функций плотности $f_XY(x, y) = f_X(x)\cdot f_Y(y)$, а если $\Cov(X, Y) \ne 0$, то сразу зависимы. Здесь — зависимы.
\item Да, являются.
\end{enumerate}


\item
Для этой задачи аккуратно нужно писать \( \left(\Delta X \right)_j \), но так как приращения цен независимы (см. биномиальная модель рынка в интернетах) будем писать \( \Delta X \).
\begin{enumerate}
\item \[\E (\Delta X) = 2 \cdot \frac{1}{2} - 1 \cdot \frac{1}{2} = \frac{1}{2} \]
\[\E (\Delta X)^2 = 4 \cdot \frac{1}{2} + 1 \cdot \frac{1}{2} = \frac{5}{2} \]
\[\Var (\Delta X) = \frac{5}{2} - \left(\frac{1}{2}\right)^2 = \frac{10-1}{4}=\frac{9}{4} \]
\item \[\E (X_n) = \E \left(1000 + n\Delta X \right)  = 1000 + n \E \Delta X = 1000 + 0.5 n     \]
\[ \Var (X_n) = n \Var (\Delta X) = n \frac{9}{4}  \]
\[ \Cov (X_n, X_k) = \Cov \left(X_k, X_k + (n-k) \Delta X \right)     \]
Так как цена в момент $k$ никак не связана с последующими случайными блужданиями, то:
\[ \Cov (X_n, X_k) = \Cov \left(X_k, X_k + (n-k) \Delta X \right) =  \Cov \left(X_k, X_k \right) + 0 = \Var X_k = k \frac{9}{4}    \]
\item Заметим, что для самих цен акций ЦПТ мы формулировать не можем ввиду того, что случайные величины коррелированы, не i.i.d. Зато мы можем сформулировать ее для независимых приращений!

\( \left(\Delta X \right)_1, \ldots, \left(\Delta X \right)_{k} \) — последовательность i.i.d. случайных величин (при большом $k$) с конечными математическим ожиданием \(1/2 \) и стандартным отклонением \(3/2 \). Пусть также \( S_k = \sum_{i=1}^k \left(\Delta X \right)_j \). Тогда формулировка ЦПТ:
\[ \frac{S_k - k/2}{3/2 \sqrt{k}} \sim \cN(0,1)    \]
\item Воспользуемся результатом ЦПТ!
\[\P(X_{100} > 1060) = \P (1000 + S_{100} > 1060) = \P(S_{100} >60) = \]
\[ = \P \left(\frac{S_{100} -50 }{3/2\cdot 10} > \frac{60-50}{3/2 \cdot 10}\right) = \P \left(Z > \frac{2}{3}\right) = 1-pnorm(2/3) \approx 0.25   \]

\item \[ \P \left(1000 + S_{100} > a \right) = 0.95              \]
\[ \P \left( S_{100} < a-1000 \right) = 0.05              \]
Используя ЦПТ:
\[ a-1000 = qnorm(0.05, mean = 50, sd = 15 )            \]
\[ a \approx 1025.33   \]
\end{enumerate}

\item
\[\begin{pmatrix}
X_1 \\
X_2
\end{pmatrix} \sim \cN \left( \begin{pmatrix}
68.1 \\
68.3
\end{pmatrix} ; \begin{pmatrix}
6.3 & 2.1 \\
2.1 & 3.2
\end{pmatrix}                   \right)\]

\begin{enumerate}
\item \href{http://johnhawks.net/explainer/stats/heritability-and-stature/}{Смотреть здесь}
\item \[ \Corr(X_1, X_2) = \frac{\Cov(X_1, X_2)}{\sigma_{X_1} \sigma_{X_2}} = \frac{2.1}{\sqrt{6.3\cdot 3.2}} \approx 0.47   \]
\item \[\begin{pmatrix}
X_1' \\
X_2'
\end{pmatrix} \sim \cN \left( \begin{pmatrix}
68.1\cdot 2.54 \\
68.3\cdot 2.54
\end{pmatrix} ; \begin{pmatrix}
6.3\cdot 2.54^2 & 2.1 \cdot 2.54^2\\
2.1\cdot 2.54^2 & 3.2 \cdot 2.54^2
\end{pmatrix} \right) \]
\[\begin{pmatrix}
X_1' \\
X_2'
\end{pmatrix} \sim \cN \left( \begin{pmatrix}
172.97 \\
173.48
\end{pmatrix} ; \begin{pmatrix}
40.65 & 13.55\\
13.55 & 20.61
\end{pmatrix} \right) \]
\item Универсальный способ:

Всегда можно представить $X_1$ и $X_2$ в следующем виде (из соображений ЛНЗ для $X_1$ две стандартные нормальные независимые $Z_1$ и $Z_2$):
\[X_1 = \E X_1 + a Z_1 + b Z_2 \]
\[X_2 = \E X_2 + c Z_1 \]
\[X_1 = 68.1 + a Z_1 + b Z_2 \]
\[X_2 = 68.3 + c Z_1 \]
Зная ковариационную матрицу, легко найти коэффициенты $a$, $b$, $c$:
\[\Var X_1 = a^2 + b^2 = 6.3   \]
\[\Var X_2 = c^2 = 3.2   \]
\[\Cov (X_1, X_2) = ac\Var Z_1= ac = 2.1   \]
Получаем $c = 1.79$, $a = 1.17$, $b=2.22$.
Итак: \[X_1 = 68.1 + 1.17 Z_1 + 2.22 Z_2 \]
\[X_2 = 68.3 + 1.79 Z_1 \]
Теперь легко получаем:
\begin{multline*}
\E (X_1 | X_2 = 72) = \E ( 68.1 + 1.17 Z_1 + 2.22 Z_2|  68.3 + 1.79 Z_1 = 72) =   \\
 =   \E ( 68.1 + 1.17 Z_1 + 2.22 Z_2|  Z_1 = 2.07) = \\
 = \E (68.1 + 1.17 \cdot 2.07 + 2.22 Z_2) = 70.52
\end{multline*}
Это кстати отражает довольно известный факт, что дети высоких родителей будут тоже высокими, но менее высокими: некий mean reversion (regression to the mean — узнаете в эконометрике).
\[ \Var (X_1 | X_2 = 72) = \Var ( 68.1 + 1.17 \cdot 2.07 + 2.22 Z_2) = 2.22^2 = 4.93   \]

\item Используем стандартизацию и факт о том, что условное распределение нормальных — нормальное:
\begin{multline*}
\P (X_1 > 68 | X_2 = 72)  = \P \left(\frac{(X_1 | X_2 = 72) - \E (X_1 | X_2 = 72)}{\sqrt{\Var (X_1 | X_2 = 72)}} > \frac{68 - 70.52}{\sqrt{4.93}} \right) = \\
= \P (Z> -1.135 ) = 1 - pnorm(-1.135) =0.87
\end{multline*}
\end{enumerate}

\item
\begin{enumerate}
\item \[X \sim Poiss(\lambda = 2 )\]
Тогда: \[\P (X = 0) = e^{-\lambda}= e^{-2}\approx 0.135  \]
\item Учитывая закон распределения времени на тушение пожара $Z \sim U[1/2,1]$ можно однозначно сказать, что за ближайший час может не быть перенаправленных звонков только при $X\leqslant 2$. Пусть $Y_1$ — время между 1-ым и 2-ым звонком. Оно имеет экспоненциальное распределение $Y \sim exp(1/2)$. Итак, искомая вероятность:
\[ \P (\cdot) = \P(X=0) + \P(X=1) + \P(X=2) \P(Y_1 > Z_1) \]
Сложность в нахождении вероятности $\P(Y_1 > Z_1)$. Предоставим путь в лоб:

Совместная функция плотности случайных величин $Y_1$ и $Z_1$, очевидно:
\[ p(y,z) = p(y) p(z) = 2e^{-2y} \cdot 2 = 4e^{-2y} \]
Тогда:
\begin{multline*}
\P(Y_1 > Z_1) = \int \limits_{1/2}^1 \int \limits_z^\infty 4e^{-2y}  dy dz = -\int \limits_{1/2}^1 2e^{-2y} |_z^\infty dz = \int \limits_{1/2}^1 2e^{-2z} dz= \\
= -e^{-2z} |_{1/2}^1 =e^{-1} - e^{-2}
\end{multline*}
Можно и без двойных интегралов, но более мозгоемко. Благодаря memoryless property пуассоновского потока:
\[\P(Y_1 > Z_1) = F_{Y_1} (1) - F_{Y_1} (1/2) = 1 - e^{-2} - (1 - e^{-1}) = e^{-1} - e^{-2} \]
Итак:
\[ \P (\cdot) = e^{-2} + 2 e^{-2} + 2 e^{-2} \left( e^{-1} - e^{-2} \right) \approx 0.47 \]

\item Благодаря memoryless property, вероятность перенаправления для каждого звонка, начиная со 2, равна $e^{-1} - e^{-2}$. Обозначим за $Q$ — количество звонков до первого перенаправленного звонка. \[Q - 1 \sim Geom (e^{-1} - e^{-2}) \]
\end{enumerate}



\item
\begin{enumerate}
\item Обозначим:
$X_i =
\begin{cases}
1, &\text{если i-ая девушка получила свое письмо} \\
0, &\text{иначе}
\end{cases}
$

Так как письма раскладывались рандомно, то: $\P (X_i = 1) = 1/n$. Тогда:
\[ \E X_i = \frac{1}{n} \]
\[ \E X_i^2 = \frac{1}{n} \]
\[ \Var X_i = \frac{1}{n} - \frac{1}{n^2} \]

Легко найти:
\[ \E X = \E (X_1 + \ldots + X_n) = n \E X_i = 1 \]

Для поиска дисперсии понадобятся ковариации, так как ясно, что если одна из девушек получила свое письмо, значит, она не отняла чье-то письмо, а следовательно, повышает вероятность получения своего письма для других девушек.
\[\Cov(X_i, X_j) = \E (X_i X_j) - (\E X_i)( \E X_j ) = \P (X_i = 1, X_j = 1) - \frac{1}{n^2}   \]
Чтобы убедиться в \(  \E (X_i X_j) = \P (X_i = 1, X_j = 1) \) можно нарисовать табличку совместного распределения этих случайных величин.
Теперь если $i$-ая девушка получила свое письмо, то для второй девушки остается $n-1$ писем и одно благоприятное письмо, следовательно:
\[\P (X_i = 1, X_j = 1) = \frac{1}{n(n-1)} \]
Итак:
\[\Cov(X_i, X_j) = \frac{1}{n(n-1)} - \frac{1}{n^2} =  \frac{n - n + 1}{n^2 (n-1)}  = \frac{ 1}{n^2 (n-1)} \]

Остался последний шаг:
\begin{multline*}
\Var X = \Var (X_1 + \ldots + X_n) = n \Var X_i + 2C_n^2 \Cov(X_i, X_j) = \\
=   1 - \frac{1}{n} + 2 \frac{n (n-1)}{2} \cdot \frac{ 1}{n^2 (n-1)} = 1
\end{multline*}
\item Т.к. $\P (X_i = 1) = 1/n$, то: \[ \P(\cdot) = \left(1 - \frac{1}{n} \right)^n   \]
Первый замечательный предел!
\[ \P(\cdot) = \frac{1}{e} \]
\end{enumerate}

\item
\href{http://www.nsu.ru/mmf/tvims/chernova/tv/lec/node6.html}{Решение внизу страницы}

\end{enumerate}

\subsection{Пересдача за 1-ый семестр??}


\input{tests/2014_midterm_retake}

\AMCnumero{1} % сбрасываем номер вопроса на 1

\cleargroup{all}

\copygroup[5]{retprobability1}{all}
\copygroup[7]{retprobability}{all}
\copygroup[1]{retcommontext}{all}
\copygroup[4]{ret1316}{all}
\copygroup[1]{retcommontext2}{all}
\copygroup[3]{ret1719}{all}
\copygroup[1]{retcommontext3}{all}
\copygroup[4]{ret2023}{all}
\copygroup[1]{retcommontext4}{all}
\copygroup[2]{ret2425}{all}
\copygroup{retruler}{all}
\copygroup[5]{ret2630}{all}


\insertgroup{all}



\subsection{Контрольная номер 3}

\begin{enumerate}

\item В студенческом буфете осталось только три булочки одинаковой привлекательности и цены, но разной калорийности: 250, 400 и 550 ккал. Голодные Маша и Саша, не глядя на калорийность, покупают по булочке. Найдите математическое ожидание и дисперсию суммы поглощенных студентами калорий.

\item Ресторанный критик ходит по трем типам ресторанов (дешевых, бюджетных и дорогих) города N для того, чтобы оценить среднюю стоимость бизнес-ланча. В городе N 30\% дешевых ресторанов, 60\% бюджетных  и 10\% дорогих. Стандартное отклонение цены бизнес-ланча составляет 10, 30 и 60 рублей соответственно. В ресторане критик заказывает только кофе.  Стоимость кофе в дешевых/бюджетных/дорогих ресторанах составляет 150, 300 и 600 рублей соответственно, а бюджет  исследования — 15 000 рублей. Какое количество ресторанов каждого типа нужно посетить критику, чтобы как можно точнее оценить среднюю стоимость бизнес-ланча при заданном бюджетном ограничении (округлите полученные значения до ближайших целых)? Вычислите дисперсию соответствующего стратифицированного среднего.

\item Дана случайная выборка $X_1$, \ldots, $X_n$  из некоторого распределения с математическим ожиданием $\mu$ и дисперсией $\sigma^2$. Даны три оценки $\mu$:
 \[
\hat\mu_1 = (X_1 + X_2)/2, \quad \hat\mu_2 = X_1/4 + (X_2 + \ldots + X_{n-1})/(2n-4) + X_n/4, \quad \hat\mu_3 = \bar X
 \]
\begin{enumerate}
\item Какая из оценок является несмещенной?
\item Какая из оценок является более эффективной, чем остальные?
\end{enumerate}

\item Случайный вектор $(X, Y)^T$ имеет двумерное нормальное распределение с математическим ожиданием  $(1, 2)^T$ и ковариационной матрицей
$C=\begin{pmatrix}
1 & -1 \\
-1 & 4
\end{pmatrix}$.
\begin{enumerate}
\item $\P(X>1)$
\item $\P(2X+Y>2)$
\item $\E(2X+Y|X=2)$, $\Var(2X+Y|X=2)$, $\P(2X+Y>2|X=2)$
\item Сравните вероятности двух предыдущих пунктов, объясните, почему они отличаются.
Являются ли компоненты случайного вектора независимыми?
\end{enumerate}


\item Величины $X_1$, $X_2$ и $X_3$  независимы и стандартно нормально распределены. Вычислите
\begin{enumerate}
\item $\P(X_1^2 + X_2^2 > 6)$
\item $\P(X_1^2 / (X_2^2 + X_3^2) > 9.25 )$
\end{enumerate}

\item Дана случайная выборка $X_1$, \ldots, $X_n$ из равномерного распределения $U[0, \theta]$.
\begin{enumerate}
\item  С помощью статистики $X_{(n)}=\max\{X_1, \ldots, X_n \}$ постройте несмещенную оценку параметра $\theta$  вида $cX_{(n)}$ (укажите значение $c$).
\item Будет ли данная оценка состоятельной?
\item Найдите оценку параметра $\theta$ методом моментов
\item Какая из двух оценок является более эффективной?
\end{enumerate}

\item Каждый из $N$ биатлонистов одинакового уровня подготовки стреляет по мишеням до первого промаха.  Пусть $X_i$ — число выстрелов $i$-го биатлониста, $\P(X_i = x_i)=p^{x_i-1}(1-p)$, где $p$ — вероятность попадания при одном выстреле.
\begin{enumerate}
\item Методом максимального правдоподобия найдите оценку $p$.
\item Методом максимального правдоподобия найдите оценку математического ожидания числа выстрелов.
\item Сформулируйте определения несмещенности, состоятельности и эффективности  оценок, и проверьте выполнение данных свойств для найденной в предыдущем пункте оценки математического ожидания.
\end{enumerate}


\end{enumerate}


\subsection{Контрольная номер 3, решение}

\begin{enumerate}
\item Пусть случайная величина $S$ – это сумма поглощённых калорий

\begin{tabular}{cccc}
\toprule
$S$ & $650$ & $800$ & $950$ \\ \midrule
$\P(\cdot)$ & $1/3$ & $1/3$ & $1/3$ \\ \bottomrule
\end{tabular}

Тогда $\E(S) = \frac{1}{3}\cdot 650 +  \frac{1}{3}\cdot 800 +  \frac{1}{3}\cdot 950 = 800$, $\Var(S) = \frac{1}{3}(650-800)^2 + \frac{1}{3}(800-800)^2 + \frac{1}{3}(950-800)^2 = 15000$

\item
$
\begin{cases}
\Var(\overline{X}_S) = \frac{0.3^2\cdot 10^2}{n_1} + \frac{0.6^2 \cdot 30^2}{n_2} + \frac{0.1^2 \cdot 60^2}{n_3} \to min_{n_1, n_2, n_3} \\
150\cdot n_1 + 300 \cdot n_2 + 600 \cdot n_3 \leq 15000
\end{cases}
$

\item
\begin{enumerate}
\item $\E(\mu_1) = \E\left(\frac{X_1+X_2}{2}\right)  = \frac{1}{2}(\mu+\mu) = \mu \Rightarrow$  несмещённая

$\E(\mu_2) = \E \left(\frac{X_1}{4} + \frac{X_2+\ldots+X_{n-1}}{2n-4} + \frac{X_n}{4}\right) = \frac{1}{4}\mu + \frac{n-2}{2n-4}\mu + \frac{1}{4}\mu = \mu \Rightarrow$ несмещённая

$\E(\overline{X}) = \E\left(\frac{X_1 + \ldots + X_n}{n}\right) = \mu \Rightarrow$ несмещённая

\item $\Var(\mu_1) = \Var\left(\frac{X_1+X_2}{2}\right)  = \frac{1}{4}2\Var(X_1) = \frac{\sigma^2}{2}$

$\Var(\mu_2) = \Var \left(\frac{X_1}{4} + \frac{X_2+\ldots+X_{n-1}}{2n-4} + \frac{X_n}{4}\right)  = \frac{\sigma^2}{16} + \frac{(n-2)\sigma^2}{(2n-4)^2} + \frac{\sigma^2}{16} = \sigma^2\left(\frac{1}{8} + \frac{1}{2(2n-4)} \right)$

$\Var(\mu_3) = \Var\left(\frac{X_1 + \ldots + X_n}{n}\right)  = \frac{1}{n^2}n\sigma^2 = \frac{\sigma^2}{n}$
\end{enumerate}

\item
\begin{enumerate}
\item $X \sim \cN (1;1)$

$\P(X>1) = 0.5$, так как нормальное распределение симметрично относительно своего математического ожидания

\item $X \sim \cN (1;1)$, $2X \sim \cN(2; 4), Y \sim \cN(2, 4) \Rightarrow 2X+Y \sim \cN (4, 4)$

$\P(2X+Y > 2) = 1 - \P(2X+Y < 1) = 1 - \P\left(\frac{2X+Y - 4}{2} < \frac{1-4}{2}\right) = 1 - 0.0668 = 0.9332$

\item $Y \mid X \sim \cN\left(\mu_Y + \rho\sigma_Y\cdot\frac{X-\mu_X}{\sigma_X}; \sigma_Y^2(1-\rho^2)\right)$, $Y \mid X=2 \sim \cN(1.5, 3)$

$\E(2X+Y \mid X=2) = 2\E (X\mid X=2) + \E(Y\mid X=2) = 4 + 1.5 = 5.5$
\end{enumerate}

\item
\begin{enumerate}
\item $X_1^2 + X_2^2 \sim \chi^2_2$, $\P(X_1^2 + X_2^2 > 6)  \approx 0.05$
\item $\P\left(\frac{X_1^2}{X_2^2+X_3^2} > 9.25\right) = \P\left(\frac{\frac{X_1^2}{1}}{\frac{X_2^2+X_3^2}{2}} > 18.5\right) \approx 0.05$, $\frac{\frac{X_1^2}{1}}{\frac{X_2^2+X_3^2}{2}} \sim F_{1, 2}$
\end{enumerate}
\end{enumerate}

\subsection{Контрольная номер 4, 05.06.2015}


\textbf{Задача 1 (для первого потока).}

Проверка  40 случайно выбранных лекций показала, что студент Халявин присутствовал только на 16 из них.
\begin{enumerate}
\item Найдите 95\% доверительный интервал для вероятности увидеть Халявина на лекции.
\item На уровне значимости 5\% проверьте гипотезу о том, что Халявин посещает в среднем половину лекций.
\item Вычислите минимальный уровень значимости, при котором основная гипотеза отвергается (P-значение).
\end{enumerate}

\vspace{0.5cm}

\textbf{Задача 1 (для второго потока).}

Вес упаковки с лекарством является нормальной случайной величиной. Взвешивание 20~упаковок показало, что выборочное среднее равно 51 г., а  несмещенная оценка дисперсии равна~4.
\begin{enumerate}
\item На уровне значимости 10\% проверьте гипотезу, что в среднем вес упаковки составляет~55 г.
\item Контрольное взвешивание 30 упаковок такого же лекарства другого производителя показало, что несмещенная оценка дисперсии веса равна 6. На уровне значимости 10\% проверьте гипотезу о равенстве дисперсий веса упаковки двух производителей.
\end{enumerate}

\vspace{0.5cm}

\textbf{Задача 2 (для первого потока).}

В ходе анкетирования  15 сотрудников банка «Альфа» ответили на вопрос о том, сколько времени они проводят на работе ежедневно. Среднее выборочное оказалось равно 9.5 часам при выборочном стандартном отклонении 0.5 часа. Аналогичные показатели для 12 сотрудников банка «Бета» составили 9.8 и 0.6 часа соответственно.

Считая распределение времени нормальным, на уровне значимости 5\% проверьте гипотезу о том, что сотрудники банка «Альфа» в среднем проводят на работе столько же времени, сколько и сотрудники банка «Бета».

\vspace{0.5cm}

\textbf{Задача 2 (для второго потока).}

Экзамен принимают два преподавателя, случайным образом выбирая студентов. По выборке из 85 и 100 наблюдений, выборочные доли не сдавших экзамен студентов составили соответственно 0.2  и 0.17.
\begin{enumerate}
\item Можно ли при уровне значимости в 1\% утверждать, что преподаватели предъявляют к студентам одинаковый уровень требований?
\item Вычислите минимальный уровень значимости, при котором основная гипотеза отвергается (P-значение).
\end{enumerate}

\vspace{0.5cm}

\textbf{Задача 3 (общая).}


Методом максимального правдоподобия найдите оценку параметра $\theta$ для выборки $X_1$, \ldots, $X_n$ из распределения с функцией плотности
\[
f(x)=\begin{cases}
\frac{1}{\theta^2}xe^{-\frac{x}{\theta}}, \; x>0 \\
0, \; x\leq 0
\end{cases}
\]

\vspace{0.5cm}

\textbf{Задача 4 (общая).}

Пусть $X_1$, \ldots, $X_{100}$ — случайная выборка из нормального распределения с математическим ожиданием $\mu$ и дисперсией $\nu$, где $\mu$ и $\nu$ — неизвестные параметры. По 100 наблюдениям $\sum x_i=30$, $\sum x_i^2=146$, $\sum x_i^3=122$.

При помощи теста отношения правдоподобия протестируйте гипотезу $H_0: \nu=1$ на уровне значимости 5\%.


\textbf{Задача 5 (исследовательская).}

\vspace{0.1cm}

Пусть $X_1$, \ldots, $X_{n}$ — случайная выборка из нормального распределения с математическим ожиданием $\mu$ и дисперсией $\nu$, где $\mu$ и $\nu$ — неизвестные параметры. Рассмотрим три классических теста, отношения правдоподобия, $LR$, множителей Лагранжа, $LM$ и Вальда, $W$, для тестирования гипотезы $H_0: \; \mu=0$.

\begin{enumerate}
\item Сравните  статистики $LR$, $LM$ и $W$ между собой. Какая — наибольшая, какая — наименьшая?
\item Изменится ли упорядоченность статистик, если проверять гипотезу $H_0: \; \mu=\mu_0$?
\end{enumerate}

\vspace{0.5cm}

Подсказка: $
\frac{x}{1+x} \leq \ln(1+x) \leq x\, \; \text{ при } x>-1
$

\vspace{0.5cm}

\textbf{Задача 6 (исследовательская).}
\thispagestyle{empty}
\vspace{0.1cm}

Величины $X_1$, \ldots, $X_n$ независимы и одинаково распределены с функцией плотности
\[
f(x)=\begin{cases}
a^2xe^{-ax}, \; x>0 \\
0, \; x\leq 0
\end{cases}
\]

По выборке из 100 наблюдений оказалось, что $\sum x_i =300$, $\sum x_i^2=1000$, $\sum x_i^3=3700$.

\begin{enumerate}
\item Найдите оценку неизвестного параметра $a$ методом моментов
\item Используя дельта-метод или иначе оцените дисперсию полученной оценки $a$
\item Постройте 95\%-ый доверительный интервал используя оценку метода моментов
\end{enumerate}


\subsection{Экзамен, 15.06.2015}

\input{tests/2014_final}

\vspace{3ex}

Можно пользоваться простым калькулятором.  В каждом вопросе единственный верный ответ. Ни пуха, ни пера!

\vspace{3ex}

\AMCnumero{1} % сбрасываем номер вопроса на 1

\insertgroup{exam_15} % вставим группу "all" в текст работы

\section{2015-2016}


\subsection{Контрольная номер 1, базовый поток, 26.10.2015}

\begin{enumerate}
\item
Подбрасываются две симметричные монеты. Событие А — на первой монете выпал
герб, событие В — на второй монете выпал герб, событие С — монеты выпали
разными сторонами.
\begin{enumerate}
    \item[$\alpha$)] Будут ли эти события попарно независимы?
    \item[$\beta$)]  Сформулируйте определение независимости в совокупности для трех событий. Являются ли события $A$, $B$, $C$ независимыми в совокупности?
\end{enumerate}

\item
Имеются два игральных кубика:
\begin{itemize}
    \item красный со смещенным центром тяжести, так что вероятность выпадения «6»
    равняется 1/3, а оставшиеся грани имеют равные шансы на появление
    \item честный белый кубик
\end{itemize}

\begin{enumerate}
    \item[$\alpha$)] Петя случайным образом выбирает кубик и подбрасывает его. Найдите
    вероятность того, что выпадет «6».
    \item[$\beta$)]   Петя случайным образом выбирает кубик и подбрасывает его. Какова
    вероятность того, что Петя взял красный кубик, если известно, что выпала
    шестерка?
\end{enumerate}

\item
Все те же кубики. Петя играет с Васей в следующую игру: Петя выбирает кубик и
подбрасывает его. Вася подбрасывает оставшийся кубик. Выигрывает тот, у кого
выпало большее число. Если выпадает равное число очков, выигрывает тот, у кого
белый кубик.

Пусть случайная величина $\xi$ — число очков, выпавших на красном кубике, случайная величина $\eta$ — число очков,
выпавших на белом кубике, а величина $\zeta$ — максимальное число очков.

\begin{enumerate}
    \item[$\alpha$)] Задайте в виде таблицы совместное распределение величин $\xi$ и $\eta$. Отметьте (* или кружочком) все те пары значений, когда выигрывает красный кубик.
    \item[$\beta$)] Какой кубик нужно выбрать Пете, чтобы его шансы выиграть были выше?
    \item[$\gamma$)] Сформулируйте определение функции распределения и постройте функцию
    распределения величины $\zeta$.
    \item[$\delta$)] Вычислите математическое ожидание величины $\zeta$.
\end{enumerate}

\item
Проводится исследование с целью определения процента мужчин, которые любят
петь в душе. Поскольку некоторые мужчины стесняются прямо отвечать на этот
вопрос, предлагается перед ответом на вопрос: «поете ли Вы, когда принимаете
душ?» подбросить правильный кубик, и выбрать ответ «ДА», если выпала
шестерка, ответ «НЕТ», если выпала единица, и честный ответ («ДА» или «НЕТ»),
если выпала любая другая цифра.

Предположим, что по результатам исследования
вероятность ответа «ДА» составляет $2/3$. Каков истинный процент «певцов»?

\item
Ваш полный тезка страдает дисграфией. При подписывании контрольной работы
по теории вероятностей в своих имени и фамилии в именительном падеже Ваш
тезка с вероятностью 0.1 вместо нужной буквы пишет любую другую (независимо
от предыдущих ошибок).

\begin{enumerate}
    \item[$\alpha$)] Найдите вероятность того, что он напишет свою фамилию правильно.
    \item[$\beta$)] Найдите вероятность того, что он сделает ровно 2 ошибки в своем имени.
    \item[$\gamma)$] Вычислите наиболее вероятное число допущенных тезкой ошибок.
    \item[$\delta$)] Найдите вероятность того, что при подписывании работы Ваш тезка допустит хотя бы одну ошибку.
\end{enumerate}

\item
Время (в часах), за которое студенты выполняют экзаменационное задание
является случайной величиной с функцией плотности

\[
f(y) =
    \begin{cases}
        cy^2 + y , & \mbox{if } 0 \le y \le 1 \\
        0, & \mbox{else}
    \end{cases}
\]

\begin{enumerate}
    \item[$\alpha$)] Найдите константу $c$.
    \item[$\beta$)]  Найдите функцию распределения и постройте её.
    \item[$\gamma)$] Вычислите вероятность того, что случайно выбранный студент закончит работу менее чем за полчаса.
    \item[$\delta$)] Найдите медиану распределения.
    \item[$\epsilon$)] Определите вероятность того, что студент, которому требуется по меньшей мере 15 минут для выполнения задания, справится с ним более, чем за 30 минут.
\end{enumerate}

\item
Вам известно, что на большом листе бумаги $1.5$ м $\times$ $1$ м нарисован слон. Вам завязали
глаза и выдали кисточку хвоста для слона. Вам нужно прилепить эту кисточку к
листу (рисунок Вы не видели). Вы подходите к листу и произвольно приклеиваете
кисточку
\begin{enumerate}
    \item[$\alpha$)] ) Какова вероятность того, что кисточка окажется на слоне, если площадь рисунка составляет $1$ м$^2$?
    \item[$\beta$)]  Запишите вид функции совместной плотности для координат кисточки.
    \item[$\gamma)$] Запишите вид частных функций плотности для каждой из координат кисточки.
    \item[$\delta$)] Являются ли координаты кисточки независимыми случайными величинами?
    \item[$\epsilon$)] Запишите вид функции плотности суммы координат кисточки.
\end{enumerate}
\textit{Подсказка: слон не должен заслонить равномерного распределения.}

\begin{center}
\includegraphics[scale=1.5]{images/slon.jpg}
\end{center}

\item
Укажите названия букв греческого алфавита и запишите соответствующие заглавные буквы:
\[\alpha, \zeta, \eta, \theta\].

\end{enumerate}

\subsection{Контрольная номер 1, базовый поток, 26.10.2015, решения}

\begin{enumerate}
\item
\begin{enumerate}
\item[$\alpha$)] Найдём вероятности каждого события: $\P(A) = 1/2$, $\P(B) = 1/2$, $\P(C) = 1/2$.

Проверим попарную независимость:
\begin{itemize}
\item $\P(A \cap B) = 1/4$, $\P(A) \cdot \P(B) = 1/2 \cdot 1/2 = 1/4$
\item $\P(A \cap C) = 1/4$, $\P(A) \cdot \P(C) = 1/2 \cdot 1/2 = 1/4$
\item $\P(B \cap C) = 1/4$, $\P(B) \cdot \P(C) = 1/2 \cdot 1/2 = 1/4$
\end{itemize}
Значит, события попарно независимы.
\item[$\beta$)] События $A_1, A_2, A_3$ называются независимыми в совокупности, если $\P(A_1 \cap A_2 \cap A_3) = \P(A_1) \cdot \P(A_2) \cdot \P(A_3)$.

В нашем случае: $\P(A \cap B \cap C) = 0$, $ \P(A) \cdot \P(B) \cdot \P(C) =  \frac{1}{2} \cdot \frac{1}{2} \cdot \frac{1}{2} $, следовательно, события
не являются независимыми в совокупности.
\end{enumerate}
\item
\begin{enumerate}
\item[$\alpha$)] Воспользуемся формулой полной вероятности:
\begin{multline*}
\P(\text{выпала «6»}) = \P(\text{выпала «6»} \mid \text{взят белый кубик}) \cdot \P(\text{взят белый кубик}) + \\
+ \P(\text{выпала «6»} \mid \text{взят красный кубик}) \cdot \P(\text{взят красный кубик}) = \\
= \frac{1}{6} \cdot \frac{1}{2} + \frac{1}{3} \cdot \frac{1}{2} = \frac{1}{4}
\end{multline*}
\item[$\beta$)] Воспользуемся формулой условной вероятности и результатом предыдущего пункта:
\begin{multline*}
\P(\text{взят красный кубик} \mid \text{выпала «6»}) = \frac{\P(\text{взят красный кубик} \cap \text{выпала «6»})}{\P(\text{выпала «6»})} =  \\
= \frac{\frac{1}{2}\cdot \frac{1}{3}}{\frac{1}{4}} = \frac{2}{3}
\end{multline*}
\end{enumerate}
\item
\begin{enumerate}
\item[$\alpha$)] Совместное распределение имеет вид:
\begin{center}
\begin{tabular}{@{}l|llllll@{}}
\toprule
$\eta$ $\backslash$ $\xi$ & $1$                            & $2$                            & $3$                            & $4$                            & $5$                            & $6$                            \\ \midrule
$1$           & $\frac{2}{15}\cdot\frac{1}{6}$ & $\frac{2}{15}\cdot\frac{1}{6}\mbox{*}$  & $\frac{2}{15}\cdot\frac{1}{6}\mbox{*}$   & $\frac{2}{15}\cdot\frac{1}{6} \mbox{*}$   & $\frac{2}{15}\cdot\frac{1}{6} \mbox{*}$   & $\frac{1}{3}\cdot\frac{1}{6} \mbox{*}$   \\
$2$           & $\frac{2}{15}\cdot\frac{1}{6}$ & $\frac{2}{15}\cdot\frac{1}{6}$ & $\frac{2}{15}\cdot\frac{1}{6}\mbox{*}$   & $\frac{2}{15}\cdot\frac{1}{6}\mbox{*}$   & $\frac{2}{15}\cdot\frac{1}{6}\mbox{*}$   & $\frac{1}{3}\cdot\frac{1}{6} \mbox{*}$   \\
$3$           & $\frac{2}{15}\cdot\frac{1}{6}$ & $\frac{2}{15}\cdot\frac{1}{6}$ & $\frac{2}{15}\cdot\frac{1}{6}$ & $\frac{2}{15}\cdot\frac{1}{6} \mbox{*}$   & $\frac{2}{15}\cdot\frac{1}{6} \mbox{*}$   & $\frac{1}{3}\cdot\frac{1}{6} \mbox{*}$   \\
$4$           & $\frac{2}{15}\cdot\frac{1}{6}$ & $\frac{2}{15}\cdot\frac{1}{6}$ & $\frac{2}{15}\cdot\frac{1}{6}$ & $\frac{2}{15}\cdot\frac{1}{6}$ & $\frac{2}{15}\cdot\frac{1}{6} \mbox{*}$ & $\frac{1}{3}\cdot\frac{1}{6} \mbox{*}$   \\
$5$           & $\frac{2}{15}\cdot\frac{1}{6}$ & $\frac{2}{15}\cdot\frac{1}{6}$ & $\frac{2}{15}\cdot\frac{1}{6}$ & $\frac{2}{15}\cdot\frac{1}{6}$ & $\frac{2}{15}\cdot\frac{1}{6}$ & $\frac{1}{3}\cdot\frac{1}{6} \mbox{*}$   \\
$6$           & $\frac{2}{15}\cdot\frac{1}{6}$ & $\frac{2}{15}\cdot\frac{1}{6}$ & $\frac{2}{15}\cdot\frac{1}{6}$ & $\frac{2}{15}\cdot\frac{1}{6}$ & $\frac{2}{15}\cdot\frac{1}{6}$ & $\frac{1}{3}\cdot\frac{1}{6}$ \\ \bottomrule
\end{tabular}
\end{center}
\item[$\beta$)] $\P(\text{выиграет белый кубик}) = (6 + 5 + 4 + 3 + 2) \cdot \frac{2}{15}\cdot\frac{1}{6} + 1 \cdot \frac{1}{3}\cdot\frac{1}{6} = \frac{1}{2}$.

Значит, Пете безразлично, какой кубик брать.
\item[$\gamma)$] $F_{\zeta}(x) = \P(\zeta \leq x)$

Выпишем таблицу распределения случайной величины $\zeta$:

\begin{tabular}{@{}l|cccccc@{}}
\toprule
$\zeta$     & $1$                              & $2$                                      & $3$                                      & $4$                                      & $5$                                      & $6$                                                                              \\ \midrule
$\P(\cdot)$ & $\frac{2}{15} \cdot \frac{1}{6}$ & $\frac{2}{15} \cdot \frac{1}{6} \cdot 3$ & $\frac{2}{15} \cdot \frac{1}{6} \cdot 5$ & $\frac{2}{15} \cdot \frac{1}{6} \cdot 7$ & $\frac{2}{15} \cdot \frac{1}{6} \cdot 9$ & $\frac{1}{3} \cdot \frac{1}{6} \cdot 6 + \frac{2}{15} \cdot \frac{1}{6} \cdot 5$ \\ \bottomrule
\end{tabular}

Тогда функция распределения имеет вид:
\[
F_{\zeta}(x) =
\begin{cases}
0 & x \leq 1 \\
\frac{1}{45} & 1 < x \leq 2 \\
\frac{4}{45} & 2 < x \leq 3 \\
\frac{9}{45} & 3 < x \leq 4 \\
\frac{16}{45} & 4 < x \leq 5 \\
\frac{25}{45} & 5 < x \leq 6 \\
1 & x > 6
\end{cases}
\]
\item[$\delta$)] $\E(\zeta) = \frac{2}{15} \cdot \frac{1}{6} \cdot 1 + \frac{2}{15} \cdot \frac{1}{6} \cdot 3 \cdot 2 + \frac{2}{15} \cdot \frac{1}{6} \cdot 5 \cdot 3 + \frac{2}{15} \cdot \frac{1}{6} \cdot 7 \cdot 4 + \frac{2}{15} \cdot \frac{1}{6} \cdot 9 \cdot 5 + \frac{1}{3} \cdot \frac{1}{6} \cdot 6 + \frac{2}{15} \cdot \frac{1}{6} \cdot 6 = \frac{43}{9} \approx 4.8 $
\end{enumerate}
\item Пусть $x$ — вероятность того, что мужчина честно любит петь в душе.

Распишем по формуле полной вероятности вероятность получить ответ «да»:
\begin{multline*}
P(\text{ответ «Да»}) = 1 \cdot \P(\text{выпала «6»}) + x \cdot(\P(\text{выпала «2»}) + \P(\text{выпала «3»}) +  \\
+ \P(\text{выпала «4»}) + \P(\text{выпала «5»})) = 1 \cdot \frac{1}{6} + x \cdot \frac{4}{6} \Rightarrow x = \frac{3}{4}
\end{multline*}
Тогда истинный процент «певцов» составляет $75 \%$
\item Предположим, что ваше имя — Студент (7 букв), а фамилия — Идеальный (9 букв).
\begin{enumerate}
\item[$\alpha$)] $\P(\text{напишет фаимлию правильно}) = (0.9)^9$
\item[$\beta$)] $\P(\text{ровно 2 ошибки в имени}) = C_{7}^2 \cdot 0.1^2 \cdot 0.9^5$
\item[$\gamma$)] Наиболее вероятное число ошибок — 1
\item[$\delta$)] $\P(\text{допустит хотя бы одну ошибку}) = 1 - \P(\text{не допустит ни одной ошибки}) = 1 - (0.9)^{16}$
\end{enumerate}
\item
\begin{enumerate}
\item[$\alpha$)] Из условия $\int_{0}^{1} (cy^2 + y) dy = 1$ получаем, что $c=3/2$.
\item[$\beta$)]
$F_{Y} (y) =
\begin{cases}
1 & y > 1 \\
\frac{y^3 + y^2}{2} & 0 < y \leq 1 \\
0 & y < 0
\end{cases} $
\item[$\gamma$)] $\P(Y < 0.5) = \int_{0}^{0.5} \left(\frac{3}{2} y^2 + y   \right) dy = \frac{3}{16}$
\item[$\delta$)] $F_{Y} (y) = 0.5 \Rightarrow y \approx 0.75 $
\item[$\epsilon$)] $\P(Y > 0.5 \mid Y \geq 0.25) = \frac{\P(Y > 0.5)}{\P(Y \geq 0.25)} = \frac{1 - \frac{3}{16}}{\int_{0.25}^{1} \left(\frac{3}{2} y^2 + y   \right) dy} = \frac{104}{123}$
\end{enumerate}
\item
\begin{enumerate}
\item[$\alpha$)] $\P(\text{кисточка окажется на слоне}) = \frac{1}{1.5} = \frac{2}{3}$
\item[$\beta$)] $f_{\xi, \eta}(x, y) = \frac{1}{1.5}$
\item[$\gamma$)] $f_{\xi} (x) = \int_{0}^{1} \frac{1}{1.5} dy = 1.5$

$f_{\eta}(y) = \int_{0}^{1.5} \frac{1}{1.5} dx = 1$
\item[$\delta$)] Да, поскольку $ f_{\xi} (x) \cdot f_{\eta}(y) = f_{\xi, \eta}(x, y)$
\item[$\epsilon$)] $f_{\xi+\eta} (t) = \int_{-\infty}^{+\infty} f_{\xi}(u) f_{\eta}(t-u) du $
\end{enumerate}
\end{enumerate}


\subsection{Праздник номер 1, исследователи, индивидуальный тур}

\begin{enumerate}
\item Для разминки вспомним греческий алфавит!

\begin{enumerate}
\item По-гречески — Σωκρατης, а по-русски — \underline{\hspace{2cm}}
\item Изобразите прописные и строчные буквы: эта \underline{\hspace{2cm}}, дзета \underline{\hspace{2cm}}, вега \underline{\hspace{2cm}}, шо \underline{\hspace{2cm}}. Если такой буквы в греческом нет, то поставьте прочерк.
\item Назовите буквы: τ \underline{\hspace{2cm}}, θ \underline{\hspace{2cm}}, ξ \underline{\hspace{2cm}}.
%\item Если пересчитать все буквы в греческом алфавите, то их окажется ровно \underline{\hspace{2cm}} %24
\end{enumerate}

\item Подбрасываются 2 симметричные монеты. Событие $A$ — на первой монете выпал герб, событие $B$ — на второй монете выпал герб, событие $C$ — монеты выпали разными сторонами.
\begin{enumerate}
\item Будут ли эти события попарно независимы?
\item Сформулируйте определение независимости в совокупности для трех событий
\item Являются ли события $A$, $B$, $C$ независимыми в совокупности?
\end{enumerate}


\item Имеются два игральных кубика: \textbf{красный} со смещенным центром тяжести, так что вероятность выпадения «6» равняется 1/3, а оставшиеся грани имеют равные шансы на появление и
правильный \textbf{белый} кубик.  Петя случайным образом выбирает кубик и подбрасывает его.
\begin{enumerate}
\item Вероятность того, что выпадет «6», равна \underline{\hspace{2cm}}
\item Вероятность того, что Петя взял красный кубик, если известно, что выпала шестерка, равна \underline{\hspace{2cm}}
\item Если бы в эксперименте Петя подбрасывал  бы кубик не один раз, а 60 раз, то безусловное математическое ожидание количества выпавших шестёрок равнялось бы \underline{\hspace{2cm}}
\end{enumerate}


\begin{comment}
\item Неразменный пятак всегда выпадает «орлом». У Александра Привалова в кармане один неразменный пятак и два обычных, равновероятно выпадающих «орлом» и «решкой». Привалов достаёт одну из монет наугад не глядя.
\begin{enumerate}
\item Вероятность того, что он достанет неразменный пятак равна \underline{\hspace{2cm}} % 1/3
\item Не глядя на монету, Привалов подкидывает её. Вероятность того, что она выпадет  «орлом», равна \underline{\hspace{2cm}} % 2/3
%\item Если бы эту случайную монету подкинуть не один раз, а 10, то математическое ожидание числа «орлов» равнялось бы \underline{\hspace{2cm}} % 20/3
\item Наконец Привалов глядит на упавшую монету и видит, что выпал «орёл». Вероятность того, что монета — неразменный пятак, равна \underline{\hspace{2cm}}
\end{enumerate}
\end{comment}

\item Винни-Пуху снится сон, будто он спустился в погреб, а там бесконечное количество горшков. Каждый из них независимо от других может оказаться либо пустым с вероятностью $0.8$, либо с мёдом с вероятностью $0.2$. Винни-Пух начинает перебирать горшки по очереди в поисках полного. Хотя у него в голове и опилки, Винни-Пух два раза в один и тот же горшок заглядывать не будет.
\begin{enumerate}
\item Вероятность того, что все горшки окажутся пустыми равна \underline{\hspace{2cm}}
\item Вероятность того, что полный горшок будет найден ровно с шестой попытки, равна \underline{\hspace{2cm}}
\item Вероятность того, что полный горшок будет найден на шестой попытке или ранее, равна \underline{\hspace{2cm}}
%\item Математическое ожидание числа перебранных горшков равняется \underline{\hspace{2cm}} % 5
\end{enumerate}

\item На самом деле у Винни-Пуха в погребе стоит 10 горшков. Каждый из них независимо от других может оказаться либо пустым с вероятностью $0.8$, либо с мёдом с вероятностью $0.2$.
\begin{enumerate}
\item Все десять горшков окажутся пустыми с вероятностью \underline{\hspace{2cm}}
\item Ровно $7$ горшков из десяти окажутся пустыми с вероятностью \underline{\hspace{2cm}}
\item Математическое ожидание числа горшков с мёдом равно \underline{\hspace{2cm}}
\end{enumerate}


\begin{comment}
\item Внутри треугольника с вершинами $(0,0)$, $(2,5)$ и $(8,0)$ случайно равномерно по площади выбирается точка. Пусть $X$ и $Y$ — абсцисса и ордината этой случаной точки.
\begin{enumerate}
\item Вероятность того, что $X>5$ равна \underline{\hspace{2cm}}.
\item Вероятность того, что $X>5$ и одновременно $Y<3$ равна \underline{\hspace{2cm}}.
\item Вероятность того, что $X>5$ если известно, что $Y<3$ равна \underline{\hspace{2cm}}.
\item События $X>5$ и $Y<3$ являются \underline{\hspace{1cm}}висимыми.
\item Функция плотности величины $X$ равна \underline{\hspace{2cm}}
\end{enumerate}
\end{comment}

\item В галактике Флатландии все объекты двумерные. На планету Тау-Слона (окружность) в случайных точках независимо друг от друга садятся три корабля. Любые два корабля могут поддерживать прямую связь между собой, если центральный угол между ними меньше прямого.

\begin{enumerate}
\item Вероятность того, что первый и второй корабли могут поддерживать прямую связь равна \underline{\hspace{2cm}}
\item Вероятность того, что все корабли смогут поддерживать прямую связь друг с другом равна \underline{\hspace{2cm}}
\item Вероятность того, что все корабли смогут поддерживать прямую связь друг с другом, если первый и второй корабль могут поддерживать прямую связь, равна \underline{\hspace{2cm}}
\end{enumerate}
Подсказка: во Флатландии хватит рисунка на плоскости, ведь координату третьего корабля можно принять за\ldots



\item Время (в часах), за которое студенты выполняют экзаменационное задание является случайной величиной $X$ с функцией плотности
\[
f(x)=\begin{cases}
3x^2, \, \text{ если } x \in [0;1] \\
0, \, \text{ иначе }
\end{cases}
\]

\begin{enumerate}
\item Функция распределения случайной величины $X$ равна \underline{\hspace{2cm}}
\item Вероятность того, что случайно выбранный студент закончит работу менее чем за полчаса равна \underline{\hspace{2cm}}.
\item Медиана распределения равна \underline{\hspace{2cm}}
\item Вероятность того, что студент, которому требуется по меньшей мере 15 минут для выполнения задания, справится с ним более, чем за 30 минут, равна \underline{\hspace{2cm}}
\item Функция распределения случайной величины $Y=1/X$ равна \underline{\hspace{2cm}}
\item Функция плотности случайной величины $Y=1/X$ равна \underline{\hspace{2cm}}
\end{enumerate}

\end{enumerate}

\subsection{Индивидуальный тур, решение}

\begin{enumerate}
\item Сократ, эта — Η, η, дзета — Ζ, ζ, вега — нет, шо — ϸ, τ — тау, θ — тета, ξ — кси.
Греческая буква шо, ϸ, была введена Александром Македонским и ныне вышла из употребления. По крайней мере, в греческом :) Заглавная примерно такая же, только её utf-код 03f7 не поддерживается шрифтом Linux Libertine.


\item да; события независимы в совокупности, если для любого поднабора событий $A_1$, \ldots, $A_k$ выполняется равенство $\P(A_1 \cap A_2 \cap \ldots \cap A_k) = \P(A_1) \cdot \ldots \cdot \P(A_k)$; нет
\item $1/4$, $2/3$, $15$
\item $0$, $0.8^5\cdot 0.2$, $1-0.8^6$
\item $0.8^{10}$, $C_{10}^3 0.2^3 0.8^7$, $2$
\item $1/2$, $3/16$, $3/8$
\begin{enumerate}
\item
\begin{flalign*}
F_X(x) &= \begin{cases}
0, \, x<0 \\
x^3, \, x \in [0;1] \\
1, \, x>1
\end{cases}&&
\end{flalign*}
\item $1/8$
\item $2^{-1/3}$
\item $56/63$
\item
\begin{flalign*}
F_Y(y) &= \begin{cases}
0, \, y<0 \\
1-1/y^3, \, y>0
\end{cases}&&
\end{flalign*}
\item
\begin{flalign*}
f_Y(y) &= \begin{cases}
0, \, y<0 \\
3y^{-4}, \, y>0
\end{cases}&&
\end{flalign*}

\end{enumerate}

\end{enumerate}

\subsection{Регата, исследователи, командный тур}

\begin{enumerate}
\item Восьминогий Кракен. У Кракена 8 ног-шупалец. Если отрубить одно щупальце, то в замен него с вероятностью $1/4$ вырастает новое; с вероятностью $1/4$ вырастает два новых; с вероятностью $1/2$, слава Океану, не вырастает ничего.

Против Кракена бьётся сам Капитан! Он наносит точные удары и безупречно умело уворачивается от ударов Кракена.

\begin{enumerate}
\item Какова вероятность того, что Капитан победит, отрубив ровно 10 щупалец?
\item Какова вероятность того, что бой Кракена и Капитана продлится вечно?
\item Сколько щупалец в среднем отрубит Капитан прежде чем победит?
\end{enumerate}

\item Разбавленный ром. Пират Злопамятный Джо очень любит неразбавленный ром. Из-за
того, что он много пьёт, у него проблемы с памятью, и он помнит не
больше, чем три последних пинты. Хозяин таверны с вероятностью 1/4 разбавляет
каждую подаваемую пинту рома. Если по ощущением Джо половина выпитых
пинт или больше была разбавлена, то он разносит таверну к чертям
собачьим.


\begin{enumerate}
\item Какова вероятность того, что хозяин таверны не успеет подать Джо третью пинту рома?
\item Сколько в среднем пинт выпьет Джо, прежде чем разнесёт таверну?
\end{enumerate}

\item $XY$ в степени $Z$. Чтобы поступить на службу Её Величества, пиратам предлагается следующая задача. Случайные величины $X$, $Y$ и $Z$ равномерны на отрезке $[0;1]$ и независимы.

\begin{enumerate}
\item Найдите функцию распределения случайной величины $-\ln X$
\item Найдите функцию распределения случайной величины $-(\ln X + \ln Y)$
\item Найдите функцию распределения случайной величины $-Z(\ln X + \ln Y)$
\item Какое распределение имеет случайная величина $(XY)^Z$?
\end{enumerate}

\item Тортики. Пираты очень любят тортики и праздновать день рождения! Если хотя бы у одного пирата на корабле день рождения, то все, включая капитана, празднуют и кушают тортики. Корабль в праздничный день дрейфует под действием ветра и не факт, что в нужном направлении.

\begin{enumerate}
\item Сколько пиратов нужно нанять капитану, чтобы ожидаемое количество праздничных дней было равно 100?
\item Сколько пиратов нужно нанять капитану, чтобы максимизировать ожидаемое количество рабочих пирато-дней (произведение числа пиратов на число рабочих дней)?
\end{enumerate}


\item Девятый вал. На побережье пиратского острова одна за одной набегают волны. Высота каждой волны — равномерная на $[0;1]$ случайная величина. Высоты волн независимы. Пираты называют волну «большой», если она больше предыдущей и больше следующей. Пираты называют волну «рекордной», если она больше всех предыдущих волн от начала наблюдения. Обозначим события $B_i= \{ i\text{-ая волна была большой} \}$ и $R_i=\{ i\text{-ая волна была рекордной} \}$.

\begin{enumerate}
\item Найдите $\P(R_{100})$, $\P(B_{100})$
\item Капитан насчитал 100 волн. Сколько в среднем из них были «рекордными»?
\item Найдите $\P(R_{99} | R_{100})$, $\P(R_{100}|B_{100})$
\end{enumerate}


\item Три сундука. Три пирата, Генри Рубинов, Френсис Пиастров и Эдвард Золотов играют одной командой в игру. В комнате в ряд, слева направо, стоят в случайном порядке три закрытых внешне неотличимых сундука: с рубинами, пиастрами и золотом. Общаться после начала игры они не могут, но могут заранее договориться о стратегии. Они заходят в комнату по очереди. Каждый из них может открыть два сундука по своему выбору. После каждого пирата комната возвращается уборщицей идеально точно в исходное состояние. Если Рубинов откроет коробку с рубинами, Писатров — с пиастрами, а Золотов — с золотом, то их команда выигрывает. Если хотя бы один из пиратов не найдёт свою цель, то их команда проигрывает.

\begin{enumerate}
\item Какова вероятность выигрыша, если все пираты пробуют открыть первый и второй сундуки?
\item Какова оптимальная стратегия?
\item Какова вероятность выигрыша при использовании оптимальной стратегии?
\end{enumerate}






\end{enumerate}

\subsection{Регата, исследователи, командный тур, решение}

\begin{enumerate}

\item Если отрублено 10 щупалец, значит либо был один удар породивший два новых щупальца, либо было два удара, породивших по одному новому, а все остальные удары не порождали новых щупалец.

Искомая вероятность равна: $8\cdot 0.5^9 \cdot 0.25^1 + C_8^2 0.5^8 0.25^2$.

Вероятность вечного боя равна нулю. Достаточно доказать, что с вероятностью один за конечное время побеждается одноногий Кракен. А эта вероятность удовлетворяет уравнению: $p=\frac{1}{4}p + \frac{1}{4}p^2 + \frac{1}{2} 1$. Единственный осмысленный корень у этого уравнения — $1$.

Замечаем, что на победу над $k$-шупальцевым Кракеном уходим в $k$ раз больше ударов в среднем чем на победу на $1$-щупальцевым. Отсюда:

\[
e_1=1 + 0.5\cdot 0 + 0.25\cdot e_1 + 0.25 \cdot 2e_1
\]

Решаем, получаем $e_1=4$ и $e_8=32$

\item Либо первая пинта разбавлена, либо первая неразбавлена, а вторая разбавлена, то есть
\[
0.25 + 0.75\cdot 0.25 =0.4375
\]

Рисуем граф:


Составляем систему (индекс — количество выпитых неразбавленных пинт):

\[
\begin{cases}
e_0=\frac{1}{4} + \frac{3}{16}2 + \frac{9}{16}(2+e_2) \\
e_2=1+\frac{3}{4}e_2 + \frac{1}{4}e_0
\end{cases}
\]

Находим $e_0=64/7\approx 9$

\item Начало из домашки! Для $t>0$:
\[
\P(-\ln X \leq t)=\P(\ln X > -t)=\P(X > e^{-t})=1-e^{-t}
\]

Итого,
\[
F_{-\ln X}(t)=\begin{cases}
0, \, t < 0 \\
1-e^{-t}, \, t \geq 0
\end{cases}
\]

Из геометрических соображений легко найти $\P(XY < a)$ для $a\in (0;1)$:
\[
\P(XY < a)=a + \int_a^1 \frac{a}{x} \, dx=a-a\ln a
\]

Переходим ко второму пункту, для $t>0$:
\[
\P(-(\ln X + \ln Y) < t)=\P(XY > e^{-t})= 1-e^{-t} -t e^{-t}
\]

Итого:
\[
F_{-\ln X - \ln Y}(t)=\begin{cases}
0, \, t < 0 \\
1-e^{-t} - te^{-t}, \, t \geq 0
\end{cases}
\]

После дифференциирования получаем функцию плотности для $S=-\ln X - \ln Y$:

\[
f_S(s)=\begin{cases}
0, \, s < 0 \\
se^{-s}, \, s \geq 0
\end{cases}
\]

Приближаемся к финальной вероятности:

\[
\P(ZS > t)= \int_t^{\infty} \int_{t/s}^1  se^{-s} \, dz\, ds=
\int_t^{\infty} (s-t)\cdot e^{-s} \, ds= \ldots = e^{-t}
\]

Сравниваем результат с первым пунктом и приходим к выводу, что величина $(XY)^Z$ имеет равномерное распределение на $[0;1]$.

\item Если нанято $n$ пиратов, то вероятность, того, что в конкретный день все работают равна $(364/365)^n$. Следовательно, ожидаемое количество праздничных дней равно $365(1-(364/365)^n)$.

Решаем уравнение

\[
1-(364/365)^n=100/365
\]

Получаем,
\[
n=\frac{\ln 265- \ln 365}{ \ln 364 - \ln 365}\approx 117
\]

Ожидаемое количество рабочих пирато-дней равно: $365n(364/365)^n$.

Получаем
\[
n^*=1/(\ln 365 - \ln 364)\approx 364
\]

\item
\begin{enumerate}
\item $\P(R_{100})=1/100$ (максимум из 100 величин должен плюхнуться на сотое место), $\P(B_{100})=1/3$ (максимум из трёх величин должен плюхнуться на второе место)
\item $\E(X)=1+\frac{1}{2} + \frac{1}{3}+\ldots + \frac{1}{100}\approx \ln 100 \approx 4.6$. Т.к. $X=X_1+X_2+\ldots + X_{100}$ и $\E(X_i)=1/i$.
\item $\P(R_{99} | R_{100})=1/99$, $\P(R_{100}|B_{100})=3/101$

Для проверки: $\P(R_{99} \cap R_{100})=98!/100!$ ($100!$ — всего перестановок, $98!$ — первые 98 можно переставлять свободно, а в конце должны идти второй наибольшое и наибольшее). $\P(R_{100} \cap B_{100})=1/101$ (максимум из 101 числа плюхнется на 100ое место).
\end{enumerate}

\item Если все пираты открывают первый и второй сундуки, то вероятность выигрыша равна нулю.

Оптимальная стратегия (одна из). Три пирата заранее договариваются, о названиях сундуков. Они называют эти три сундука (ещё до игры)  «рубиновым», «пиастровым» и «золотым». Генри Рубинов должен начать с открытия рубинового сундука, Френсис Пиастров — с пиастрового, Эдвард Золотов — с золотого. Далее каждый пират должен открыть тот сундук, на который указывает предмет, лежащий в первом открытом им сундуке. Например, если Генри Рубинов, открыв сначала рубиновый сундук обнаруживает там пиастры, он должен открывать пиастровый сундук.

Вероятность победы при такой стратегии легко находится перебором 6 возможных вариантов и равна\ldots Та-дам!!! $2/3$.




\end{enumerate}


\subsection{Контрольная номер 2, поток Арктура, 12.12.2015}

Продолжительность: 1 час 20 минут

\begin{enumerate}
\item Функция плотности случайного вектора $\xi=(\xi_1, \xi_2)^T$ имеет вид
\[
f(x,y)=\begin{cases}
0.5x + 1.5y, \text{ если } 0<x<1, \; 0<y<1 \\
0, \text{ иначе }
\end{cases}
\]
Найдите:
\begin{enumerate}
\item Математическое ожидание $\E(\xi_1 \cdot \xi_2)$
\item Условную плотность распределения $f_{\xi_1|\xi_2} (x|y)$
\item Условное математическое ожидание $\E(\xi_1| \xi_2=y)$
\item Константу $k$, такую, что функция $h(x,y)=kx\cdot f(x,y)$ будет являться совместной функцией плотности некоторой пары случайных величин
\end{enumerate}

\item На курсе учится очень много студентов. Вероятность того, что случайно выбранный студент по результатам рубежного контроля имеет хотя бы один незачет равна $0.2$. Пусть $\xi$ и $\eta$ — число студентов с незачетами и без незачетов в случайной группе из $10$ студентов. Найдите $\Cov(\xi,\eta)$, $\Corr(\xi,\eta)$, $\Cov(\xi-\eta,\xi)$. Являются ли случайные величины $\xi-\eta$ и $\xi$ независимыми?

\item Доходности акций компаний А и В – случайные величины $\xi$ и $\eta$. Известно, что $\E(\xi)=1$, $E(\eta)=1$, $\Var(\xi)=4$, $\Var(\eta)=9$, $\Corr(\xi,\eta)=-0.5$. Петя принимает решение потратить свой рубль на акции компании А, Вася — 50 копеек на акции компании А и 50 копеек на акции компании В, а Маша  принимает решение вложить свой рубль в портфель $R=\alpha\xi+(1-\alpha)\eta$, $(0 \leq \alpha \leq 1)$, обладающий минимальным риском. Найдите $\alpha$, ожидаемые доходности и риски портфелей Пети, Васи и Маши.

\item Будем считать, что рождение мальчика и девочки равновероятны.
\begin{enumerate}
\item Оцените с помощью неравенства Маркова вероятность того, что среди тысячи новорожденных младенцев, мальчиков будет более 75\%.
\item Оцените с помощью неравенства Чебышёва вероятность того, что доля мальчиков среди тысячи новорожденных младенцев будет отличаться от 0.5 более, чем на 0.25
\item С помощью теоремы Муавра-Лапласа вычислите вероятность из предыдущего пункта.
\end{enumerate}

\item Сейчас валютный курс племени «Мумба» составляет 100 оболов за один рубль. Изменение курса за один день — случайная величина $\delta_i$ с законом распределения:

\begin{center}
\begin{tabular}{lrrr}
\toprule
$\delta_i$ & $-1$ & $0$ & $2$ \\ \midrule
$\P(\cdot)$ & $0.25$ & $0.5$ & $0.25$ \\
\bottomrule
\end{tabular}
\end{center}

Найдите вероятность того, что через полгода (171 день) рубль будет стоить более 250 оболов, если ежедневные изменения курса происходят независимо друг от друга.

\item \textbf{Бонусная задача}

Число посетителей, зашедших в магазин в течении дня — пуассоновская случайная величина с параметром $\lambda$. Каждый из посетителей совершает покупку с вероятностью $p$, не зависимо от других посетителей. Найдите математическое ожидание числа человек, совершивших покупку.

\end{enumerate}


\subsection{Контрольная номер 2, поток Арктура, 12.12.2015, решение}

\begin{enumerate}
\item
\begin{enumerate}
\item $ \E({\xi_1 \cdot \xi_2}) = \int_{0}^1 \int_0^1 xy f(x,y) \, dx \, dy = \int_0^1 \int_0^1 \frac{1}{2}\cdot x^2y + \frac{3}{2}\cdot xy^2 \, dx \, dy = \int_{0}^1 \frac{y}{6} + \frac{3y^2}{4} \,dy = \frac{1}{3}$
\item $f_{\xi_1 | \xi_2} (x | y) = \frac{f_{\xi_1, \xi_2}(x, y)}{f_{\xi_2}(y)} = \frac{0.5x + 1.5y}{0.25 + 1.5y}, \text{ при } y \in (0,1)$
\item
\begin{multline*}
\E(\xi_1 | \xi_2 = y) = \int_0^1 x f_{\xi_1 | \xi_2} (x | y) dx = \\
= \int\limits_{0}^{1}  x \frac{0,5x + 1,5y}{0,25 + 1,5y} dx = \frac{1}{0,25 + 1,5y}  \left. \left( \dfrac{0,5x^3}{3} +  \dfrac{1,5yx^2}{2} \right) \right|_0^1  =  \frac{1/6 + 3/4y}{0,25 + 1,5y}
\end{multline*}
\item
Для того, чтобы функция являлась совместной плотностью для пары случайных величин, должно выполнятся следующее:
\[
\int_{\Omega} kx f(x,y) \, dx \, dy = 1
\]
Вычислим, чему равняется левая часть:
\[
1 = \int_{\Omega} kx f(x,y) \, dx \, dy = \int_{0}^1 \int_{0}^1 kx \left(\frac{x + 3y}{2}\right) dx \, dy = \int_{0}^1 \frac{k}{6} + \frac{3ky}{4} \, dy = \frac{k}{6} + \frac{3k}{8} \Rightarrow
\]
\[
k = \frac{24}{13}
\]
\end{enumerate}
\item Заметим, что $\xi + \eta = 10$, тогда $\Cov(\xi, \eta) = \Cov(\xi, 10-\xi) = -\Var(\xi)$.

Представим случайную величину $\xi$ в виде суммы случайных величин $\xi = \xi_1 + \ldots + \xi_{10}$, где
\[
\xi_i = \begin{cases}
1, & \text{если у студента есть хотя бы один незачёт}, p=0.2 \\
0, & \text{иначе}, p=0.8
\end{cases} \quad i = 1, \ldots, 10
\]

Поскольку результаты каждого из стуентов независимы, $\Var(\xi) = 10\Var(\xi_1)$
\[
\Cov(\xi, \eta) = -10(1^2 \cdot 0.2 - (1\cdot 0.2)^2) = -1.6
\]

Так как случайные величины $\xi$ и $\eta$ связаны соотношением $\xi = 10 - \eta$, $\Corr(\xi, \eta)=-1$.

Подставив в $\Cov(\xi - \eta, \xi)$ выражение $\eta = 10 - \xi$, получим:
\[
\Cov(\xi - \eta, \xi) = 2 \Cov(\xi, \xi) = 2 \cdot 0.16 = 0.32
\]
Случайные величины $\xi - \eta$ и $\xi$ не являются независиыми.
\item Найдем ожидаемую доходность и риск портфеля $R = \alpha \xi + (1-\alpha) \eta$ для любого $\alpha$, тогда при $\alpha = 1$ получим результаты Пети, при $\alpha = 0.5$ — результаты Васи.
\[
\E R = \alpha + (1-\alpha) = 1 \: \, \forall \, \: \alpha \in [0,1]
\]

Находим дисперсию:
\[
\Var(R) = \alpha^2 \cdot 4 + (1-\alpha)^2 \cdot 9 - 6\alpha (1-\alpha) = 19\alpha^2 -24\alpha + 9 \to \min_{\alpha} \Rightarrow
\]

Теперь, найдем оптимальное $\alpha$:
\[
\alpha = \frac{24}{38}
\]

Финальные цифры:
\[
\begin{cases}
\Var(R)^{P} = 4 \Rightarrow \sigma_{P} = 2 \\
\Var(R)^{V} = 1.75 \Rightarrow \sigma_{V} \approx 1.32 \\
\Var(R)^{M} = \frac{27}{19} \Rightarrow \sigma_{M} \approx 1.19 \\
\end{cases}
\]
\item
\begin{enumerate}
\item Пусть $S$ количество мальчиков, тогда используя \href{https://en.wikipedia.org/wiki/Markov%27s_inequality}{неравенство Маркова} получаем:
\[
\P(S \ge 750) \le \frac{\E(S)}{750} = \frac{2}{3}
\]
\item Пусть, теперь, $\overline{X}$ доля мальчиков, то есть, $\overline{X} = \sum_{i=1}^n X_i /n$, где
\[
X_i =
\begin{cases}
1, \text{ если }i\text{-ый ребёнок — мальчик }\\
0, \text{ иначе }
\end{cases}
\]
тогда используя \href{https://en.wikipedia.org/wiki/Markov%27s_inequality}{неравенство Чебышева} получаем:
\[
\P(|\overline{X} - 0.5| \ge 0.25) \le \frac{\Var(\overline{X})}{0.25^2} = \frac{1/4000}{0.25^2} = 0.004
\]
\item Вероятность из предыдущего пункта можно записать в таком виде:
\begin{multline*}
\P(|\overline{X} - 0.5| \ge 0.25) = \P(\overline{X} \ge 0.75) + \P(\overline{X} \le 0.25) = 2\P(\overline{X} \ge 0.75)=\\
= 2\P(\cN(0;1)\geq 0.25\sqrt{4000})=2\P(\cN(0;1)\geq 15.8) = 1.3 \cdot 10^{-56} \approx 0
\end{multline*}
\end{enumerate}
\item Пусть случайная величина $S$ —  это валютный курс через полгода. Заметим, что $S = 100 + \delta_1 + \ldots + \delta_{171}$.
Тогда по ЦПТ $S \sim \cN(142.75, 203.0625)$. Теперь можно искать нужную вероятность:
\[
\P(S > 250) = \P \left(\frac{S -  142.75}{\sqrt{203.0625}} > \frac{250-142.75}{\sqrt{203.0625}} \right) = \P(\cN(0, 1) > 7.6) \approx 0
\]
%\item $\lambda p$
\end{enumerate}




\subsection{Контрольная номер 2, поток Риччи, 12.12.2015}

Продолжительность: 1 час 20 минут


\begin{enumerate}
\item Функция плотности случайного вектора $\xi=(\xi_1, \xi_2)^T$ имеет вид
\[
f(x,y)=\begin{cases}
0.5x + 1.5y, \text{ если } 0<x<1, \; 0<y<1 \\
0, \text{ иначе }
\end{cases}
\]
Найдите:
\begin{enumerate}
\item Математическое ожидание $\E(\xi_1 \cdot \xi_2)$
\item Условную плотность распределения $f_{\xi_1|\xi_2} (x|y)$
\item Условное математическое ожидание $\E(\xi_1| \xi_2=y)$
\item Константу $k$, такую, что функция $h(x,y)=kx\cdot f(x,y)$ будет являться совместной функцией плотности некоторой пары случайных величин
\end{enumerate}

\item На курсе учится очень много студентов. Вероятность того, что случайно выбранный студент получит «отлично» за контрольную равна $0.2$, «хорошо» — $0.3$. Вероятности остальных результатов неизвестны. Пусть $\xi$ и $\eta$ — число отличников и хорошистов в случайной группе из $10$ студентов. Найдите $\Cov(\xi,\eta)$, $\Corr(\xi,\eta)$, $\Cov(\xi-\eta,\xi)$. Являются ли случайные величины $\xi-\eta$ и $\xi$ независимыми?

\item Доходности акций компаний А и В — случайные величины $\xi$ и $\eta$. Известно, что $\E(\xi)=1$, $E(\eta)=1$, $\Var(\xi)=4$, $\Var(\eta)=9$, $\Corr(\xi,\eta)=-0.5$. Петя принимает решение потратить свой рубль на акции компании А, Вася — 50 копеек на акции компании А и 50 копеек на акции компании В, а Маша  принимает решение вложить свой рубль в портфель $R=\alpha\xi+(1-\alpha)\eta$, $(0 \leq \alpha \leq 1)$, обладающий минимальным риском. Найдите $\alpha$, ожидаемые доходности и риски портфелей Пети, Васи и Маши.

\item Будем считать, что рождение мальчика и девочки равновероятны.
\begin{enumerate}
\item С помощью закона больших чисел определите в каком городе, большом или маленьком, больше случается таких дней, когда рождается более 75\% мальчиков.
\item Оцените с помощью неравенства Маркова вероятность того, что среди тысячи новорожденных младенцев мальчиков будет более 75\%.
\item Оцените с помощью неравенства Чебышёва вероятность того, что доля мальчиков среди тысячи новорожденных младенцев будет отличаться от 0.5 более, чем на 0.25
\item С помощью теоремы Муавра-Лапласа вычислите вероятность из предыдущего пункта.
\end{enumerate}

\item Сейчас валютный курс племени «Мумба» составляет 100 оболов за один рубль. Процентное изменение курса за один день — случайная величина $\delta_i$ с законом распределения:

\begin{center}
\begin{tabular}{lrr}
\toprule
$\delta_i$ & $-1\%$  & $1\%$ \\
$\P(\cdot)$ & $0.25$  & $0.75$ \\
\bottomrule
\end{tabular}
\end{center}

Найдите вероятность того, что через полгода (171 день) рубль будет стоить более 271 обола, если ежедневные изменения курса происходят независимо друг от друга.

\item Величины $X_1$, $X_2$, \ldots независимы и равновероятно принимают значения $-1$ и $3$.
\begin{enumerate}
\item Найдите $\plim_{n\to\infty} \frac{\sum_{i=1}^n(X_i-\bar X)^2}{n}$
\item С помощью дельта-метода найдите примерный закон распределения $\frac{\sum_{i=1}^{100}(X_i-\bar X)^2}{100}$
\end{enumerate}

\end{enumerate}

\subsection{Контрольная номер 2, поток Риччи, 12.12.2015, решение}

Решение: Аршак Минасян


\begin{enumerate}

\item
\begin{enumerate}
\item $ \E({\xi_1 \cdot \xi_2}) = \int_{0}^1 \int_0^1 xy f(x,y) \, dx \, dy = \int_0^1 \int_0^1 \frac{1}{2}\cdot x^2y + \frac{3}{2}\cdot xy^2 \, dx \, dy = \int_{0}^1 \frac{y}{6} + \frac{3y^2}{4} \,dy = \frac{1}{3}$
\item $f_{\xi_1 | \xi_2} (x | y) = \frac{f_{\xi_1, \xi_2}(x, y)}{f_{\xi_2}(y)} = \frac{0.5x + 1.5y}{0.25 + 1.5y}, \text{ при } y \in (0,1)$
\item
\begin{multline*}
\E(\xi_1 | \xi_2 = y) = \int_0^1 x f_{\xi_1 | \xi_2} (x | y) dx = \\
= \int\limits_{0}^{1}  x \frac{0,5x + 1,5y}{0,25 + 1,5y} dx = \frac{1}{0,25 + 1,5y}  \left. \left( \dfrac{0,5x^3}{3} +  \dfrac{1,5yx^2}{2} \right) \right|_0^1  =  \frac{1/6 + 3/4y}{0,25 + 1,5y}
\end{multline*}
\item
Для того, чтобы функция являлась совместной плотностью для пары случайных величин, должно выполнятся следующее:
\[
\int_{\Omega} kx f(x,y) \, dx \, dy = 1
\]
Вычислим, чему равняется левая часть:
\[
1 = \int_{\Omega} kx f(x,y) \, dx \, dy = \int_{0}^1 \int_{0}^1 kx \left(\frac{x + 3y}{2}\right) dx \, dy = \int_{0}^1 \frac{k}{6} + \frac{3ky}{4} \, dy = \frac{k}{6} + \frac{3k}{8} \Rightarrow
\]
\[
k = \frac{24}{13}
\]
\end{enumerate}
\item При расчёте ковариации применим разложение случайной величины в сумму простых случайных величин!

$\Cov(\xi, \eta) = \Cov(\xi_1 + \ldots + \xi_{10}, \eta_1 + \ldots + \eta_{10})=10\Cov(\xi_1, \eta_1)=10(0-0.2\cdot 0.3)=-0.6$

$\Var(\xi)=10\cdot 0.2\cdot 0.8=1.6 $

$\Var(\eta)=10\cdot 0.3\cdot 0.7=2.1 $

$\Corr(\xi,\eta)=-0.6/\sqrt{1.6\cdot 2.1} \approx -0.33 $

$\Cov(\xi - \eta, \xi) = \Var(\xi) - \Cov(\xi, \eta) \neq 0$

Следовательно, $\xi$ и $\eta$ зависимы.

\item Найдем ожидаемую доходность и риск портфеля $R = \alpha \xi + (1-\alpha) \eta$ для любого $\alpha$, тогда при $\alpha = 1$ получим результаты Пети, при $\alpha = 0.5$ — результаты Васи.
\[
\E R = \alpha + (1-\alpha) = 1 \: \, \forall \, \: \alpha \in [0,1]
\]

Находим дисперсию:
\[
\Var(R) = \alpha^2 \cdot 4 + (1-\alpha)^2 \cdot 9 - 6\alpha (1-\alpha) = 19\alpha^2 -24\alpha + 9 \to \min_{\alpha} \Rightarrow
\]

Теперь, найдем оптимальное $\alpha$:
\[
\alpha = \frac{24}{38}
\]

Финальные цифры:
\[
\begin{cases}
\Var(R)^{P} = 4 \Rightarrow \sigma_{P} = 2 \\
\Var(R)^{V} = 1.75 \Rightarrow \sigma_{V} \approx 1.32 \\
\Var(R)^{M} = \frac{27}{19} \Rightarrow \sigma_{M} \approx 1.19 \\
\end{cases}
\]

\item
\begin{enumerate}
\item По ЗБЧ имеем:
\[
\frac{\xi_1 + \dots + \xi_n}{n} \to \E(\xi_1) = \frac{1}{2},
\]
Поэтому, чем больше $n$ (количество жителей в городе), тем меньше таких дней, когда количество мальчиков больше $75\%.$ \\
\item Пусть $S$ количество мальчиков, тогда используя \href{https://en.wikipedia.org/wiki/Markov%27s_inequality}{неравенство Маркова} получаем:
\[
\P(S \ge 750) \le \frac{\E(S)}{750} = \frac{2}{3}
\]
\item Пусть, теперь, $\bar X$ доля мальчиков, то есть, $\overline{X} = \sum_{i=1}^n X_i /n$, где
\[
X_i =
\begin{cases}
1, \text{ если }i\text{-ый ребёнок — мальчик }\\
0, \text{ иначе }
\end{cases}
\]
тогда используя \href{https://en.wikipedia.org/wiki/Markov%27s_inequality}{неравенство Чебышева} получаем:
\[
\P(|\overline{X} - 0.5| \ge 0.25) \le \frac{\Var(\overline{X})}{0.25^2} = \frac{1/4000}{0.25^2} = 0.004
\]
\item Вероятность из предыдущего пункта можно записать в таком виде:
\begin{multline*}
\P(|\overline{X} - 0.5| \ge 0.25) = \P(\overline{X} \ge 0.75) + \P(\overline{X} \le 0.25) = 2\P(\overline{X} \ge 0.75)=\\
= 2\P(\cN(0;1)\geq 0.25\sqrt{4000})=2\P(\cN(0;1)\geq 15.8) = 1.3 \cdot 10^{-56} \approx 0
\end{multline*}
\end{enumerate}

\item

Ищем вероятность

\[
100\cdot X_1 \cdot \ldots \cdot X_{171} \geq 271
\]

Здесь $X_i$ принимают значения $0.99$ или $1.01$ с вероятностями $0.25$ и $0.75$

Берем логарифм:

\[
\sum \log X_i \geq 1
\]

Исходим из худшего случая, когда на калькуляторе нет логарифма, тогда неплохо знать, что $\log (1+\alpha) \sim \alpha$, поэтому можно считать, что $\log X_i$ принимает значения $-0.01$ и $0.01$.

Значит $\E(\log X_i)=1/200$, $\Var(\log X_i)=1/100 - 1/200^2 \approx 1/100$.

Поэтому сумма $S \sim \cN(171/200, 171/100)$ и

\[
\P(S \geq 1)=\P(\cN(0, 1) \geq 0.11) \approx 0.46
\]

\item
\begin{enumerate}
\item Используем ЗБЧ:
\[
\plim_{n \to \infty} \frac{\sum_{i=1}^n (X_i - \bar{X})^2}{n} = \plim \frac{\sum X_i^2}{n} - \plim \bar X \cdot \bar X = \E(X_1^2) - (\E(X_1))^2 = \Var(X_1) = 4
\]
\item Обозначим, $Y_i=X_i^2$, тогда наше выражение можно записать в виде:
\[
Q=\overline{Y} - (\overline{X})^2
\]

Причём, $\plim \bar Y = 5$, $\plim \bar X = 1$.

Согласно дельта-методу заменяем его на линейную аппроксимацию в окрестности предела:
\[
Q\approx 4 + (\bar Y - 5) + 2 (\bar X - 1)
\]

Стало быть, при больших $n$:

\[
\E(Q) \approx 4
\]

\begin{multline*}
\Var(Q) \approx \Var(\bar Y) + 4\Var(\bar X) + 4\Cov(\bar Y, \bar X) =\\
= \frac{1}{n} \left(\Var(Y_1) + 4 \Var(X_1) + 4\Cov(X_1, Y_1) \right) = \\
= 0.01 \cdot (16 + 4 \cdot 4 + 4 \cdot 8)= 0.64
\end{multline*}

Итого, $Q \approx \cN(4; 0.64)$

\end{enumerate}

\end{enumerate}



\subsection{Midterm, 21.12.2015}

\input{tests/2015_midterm}

\vspace{3ex}

Можно пользоваться простым калькулятором.  В каждом вопросе единственный верный ответ. Ни пуха, ни пера!

\vspace{3ex}

\AMCnumero{1} % сбрасываем номер вопроса на 1

\cleargroup{all}
\copygroup[5]{probability1}{all}
\copygroup{newpage}{all}
\copygroup[7]{probability}{all}
\copygroup[1]{commontext}{all}
\copygroup[4]{1316}{all}
\copygroup[3]{1719}{all}
\copygroup[1]{commontext3}{all}
\copygroup[4]{2023}{all}
\copygroup[1]{commontext4}{all}
\copygroup[2]{2425}{all}
\copygroup{ruler}{all}
\copygroup[5]{2630}{all}

\insertgroup{all}


\subsection{Контрольная работа 3. 1 апреля 2016}

\epigraph{Ищите и обрящете, толцыте и отверзется вам}{Лука 11:9}

\begin{enumerate}
\item В студенческом буфете осталось только три булочки одинаковой привлекательности и цены, но разной калорийности: 250, 400 и 550 ккал. Голодные Маша и Саша, не глядя на калорийность, покупают по булочке. Найдите математическое ожидание и дисперсию суммы поглощенных студентами калорий.
\item Дана реализация случайной выборки  независимых одинаково распределенных случайных величин: 11, 4, 6.
\begin{enumerate}
  \item Выпишите вариационный ряд;
  \item Постройте выборочную функцию распределения;
  \item Найдите выборочную медиану распределения;
  \item Вычислите выборочное среднее и несмещенную оценку дисперсии.
\end{enumerate}

\item Найдите математическое ожидание, дисперсию и коэффициент корреляции случайных величин $X$ и $Y$, совместное распределение которых имеет функцию плотности
\[
f(x, y) = \frac{5}{4\pi \sqrt{6}} \exp\left(
-\frac{25}{48}\left( (x-1)^2 -0.4(x-1)y + y^2 \right)
\right)
\]

\item Рост и размер обуви $(X, Y)$ взрослого мужчины хорошо описывается двумерным нормальным распределением с математическим ожиданием $(178, 42)$ и ковариационной матрицей $C = \begin{pmatrix}
49 & 5.6 \\
5.6 & 1 \\
\end{pmatrix}$.
\begin{enumerate}
  \item Какой процент мужчин обладает ростом выше 185 см?
  \item Являются ли рост и размер обуви случайно выбранного мужчины независимыми? Обоснуйте ответ.
  \item Среди мужчин с ростом 185 см, каков процент тех, кто имеет размер обуви, меньший сорок второго  $\P(Y < 42 \mid X=185)$?
\end{enumerate}


\item Дана случайная выборка $X_1$, \ldots, $X_n$ из равномерного распределения $U[0; 2\theta]$.
\begin{enumerate}
  \item С помощью первого момента найдите оценку параметра  $\theta$ методом моментов;
  \item Сформулируйте определения несмещенности, состоятельности и эффективности оценок;
  \item Проверьте, будет ли найденная в пункте (а) оценка несмещенной и состоятельной.
  \item С помощью статистики $X_{(n)}= \max\{ X_1,\ldots, X_n \}$ постройте несмещенную оценку параметра $\theta$  вида $cX_{(n)}$. Укажите значение $c$.
  \item Проверьте, будет ли данная оценка состоятельной;
  \item Какая из двух оценок является более эффективной? Обоснуйте ответ.
\end{enumerate}

\item Вовочка хочет проверить утверждение организаторов юбилейной лотереи «Метро-80 лет в ритме столицы», что почти треть всех билетов выигрышные. Для этого он попросил $n$ своих друзей купить по 10 лотерейных билетов.  Пусть  $X_i$ — число выигрышных билетов друга $i$ и $p$ — вероятность выигрыша одного билета.
\begin{enumerate}
  \item  Какое распределение имеет величина $X_i$?
  \item Запишите функцию правдоподобия $L(p)$  для выборки $X_1$, \ldots, $X_n$;
  \item Методом максимального правдоподобия найдите оценку $p$;
  \item Найдите информацию Фишера для одного наблюдения $i(p)$;
  \item Для произвольной несмещенной оценки $T(X_1, \ldots, X_n)$ запишите неравенство Рао-Крамера-Фреше;
  \item Будет оценка $\hat p_{ML}$ эффективной?
  \item Найдите оценку максимального правдоподобия математического ожидания и дисперсии выигранных произвольным другом билетов;
  \item Дана реализация случайной выборки 5 Вовочкиных друзей. Число выигрышных билетов  оказалось равно (3, 4, 0, 2, 6). Найдите значение точечной оценки вероятности выигрыша $p$. Как Вы думаете, похоже ли утверждение организаторов на правду?
\end{enumerate}

\item  Дана выборка $X_1$, $X_2$, \ldots, $X_n$ независимых одинаково распределенных величин из распределения с функцией плотности
\[
f(x)=\begin{cases}
(1+\theta)x^\theta, \text{ если } 0<y<1, \theta+1>0 \\
0, \text{ иначе}
\end{cases}.
\]

Методом максимального правдоподобия найдите оценку параметра $\theta$.

\item Пробег (в 1000 км) автомобиля «Лада Калина» до капитального ремонта двигателя является нормальной случайной величиной с неизвестным математическим ожиданием $\mu$ и известной дисперсией 49. По выборке из 20 автомобилей найдите значение доверительного интервала для математического ожидания пробега с уровнем доверия 0.95.

\end{enumerate}


\subsection{Контрольная работа 3, решения}

\begin{enumerate}
\item Пусть случайная величина $S$ – это сумма поглощённых калорий

\begin{tabular}{cccc}
\toprule
$S$ & $650$ & $800$ & $950$ \\ \midrule
$\P(\cdot)$ & $1/3$ & $1/3$ & $1/3$ \\ \bottomrule
\end{tabular}

Тогда
\[
\E(S) = \frac{1}{3}\cdot 650 +  \frac{1}{3}\cdot 800 +  \frac{1}{3}\cdot 950 = 800
\]
\[
\Var(S) = \frac{1}{3}(650-800)^2 + \frac{1}{3}(800-800)^2 + \frac{1}{3}(950-800)^2 = 15000
\]
\item Вариационный ряд: $4, 6, 11$; медиана: $6$; выборочное среднее: $7$; несмещённая оценка дисперсии: $13$
\item Фунуция плотности двумерного нормального распределения имеет вид:
\begin{multline*}
f(x,y) =  \frac{1}{2\pi}\cdot \frac{1}{\sigma_x \sigma_y \sqrt{1-\rho^2}} \cdot \\
\cdot \exp\left\{{-\frac{1}{2}\frac{1}{\sigma_x^2 \sigma_y^2(1-\rho^2)}\left[\sigma_x^2(x-\mu_x)^2-2\rho\sigma_x\sigma_y(x-\mu_x)(y-\mu_y)+\sigma_y^2(y-\mu_y)^2\right]}\right\}
\end{multline*}
Откуда: $\mu_X=1$, $\mu_Y=0$, $\sigma_X = 1$, $\sigma_Y = 1$, $\rho = 0.2$

\item
\begin{enumerate}
\item \begin{multline*}
X \sim \cN(178, 49)$, $\P(X>185) = 1  - \P(X<185) = \\
= 1- \P\left(\frac{X-178}{7} < \frac{185-178}{7}\right) = 1 - 0.8413 = 0.1587
\end{multline*}
\item Нет, так как $\Cov(X, Y) = 5.6 \neq 0$
\item $Y \mid X \sim \cN\left(\mu_Y + \rho\sigma_Y\cdot\frac{X-\mu_X}{\sigma_X}; \sigma_Y^2(1-\rho^2)\right)$

$Y \mid X=185 \sim \cN(42.8;0.36)$

$\P(Y<42 \mid X=185) = \P\left(\frac{Y-42.8}{0.6} < \frac{42-42.8}{0.6}\mid X=185\right) = 0.9082$
\end{enumerate}

\item
\begin{enumerate}
\item $\E(X) = \frac{0+2\theta}{2}\mid_{\hat{\theta}} = \overline{X}$, $\hat{\theta}_{MM} = \overline{X}$
\item $\forall \theta \in \Theta: \E(\hat{\theta})=\theta \Leftrightarrow \hat{\theta}$ – несмещённая.

$\forall \theta \in \Theta, \forall \epsilon > 0 : \P(\vert \widehat{\theta}_n - \theta \vert > \epsilon) \to 0 \Leftrightarrow  \widehat{\theta}_n$ – состоятельная.

$\forall \theta \in \Theta: I_n (\theta) = \Var(\hat{\theta}) \Leftrightarrow \hat{\theta} $ – эффективная.
\item $\E(\theta) = \E(\overline{X}) = \E(X_1) = \theta \Rightarrow \hat{\theta}$ – несмещённая оценка

$\Var(\hat{\theta_n}) = \Var(\overline{X}) = \frac{\Var(X_1)}{n} = \frac{4\theta^2}{12\cdot n} \to 0$; из условий $\E(\widehat{\theta}_n) = \theta$ и $\Var(\widehat{\theta}_n)  \to_{n \to \infty} 0$ следует, что $\widehat{\theta}_n \stackrel{\P}{\to}  \theta$ при $n \to \infty$, т.е. $\widehat{\theta}_n$ является состоятельной.

\item
\begin{multline*}
F_{X_{(n)}} = \P(max(X_1, \ldots, X_n) \leq x) = \P(X_1 \leq x) \cdot \ldots \cdot \P(X_n \leq x) = (\P(X_1 \leq x))^n = \\
= \begin{cases}
0 & \text{при } x<0 \\
\left(\frac{x}{2\theta}\right)^n & \text{при }  x \in [0, 2\theta] \\
1 & \text{при }  x > 2\theta
\end{cases}
\end{multline*}

\[
f_{X_{(n)}} (x)  = \begin{cases}
0 & \text{при } x<0 \\
\frac{nx^{n-1}}{2^n \theta^n} & \text{при }  x \in [0, 2\theta] \\
0 & \text{при }  x > 2\theta
\end{cases}
\]

\begin{multline*}
\E(X_{(n)}) = \int_{-\infty}^{+\infty} x \cdot f_{X_{(n)}} (x) dx = \int_{0}^{2\theta}	x \cdot \frac{nx^{n-1}}{2^n \theta^n} dx = \frac{n}{2^n \theta^n}  \cdot \frac{x^{n+1}}{n+1} \mid_{x=0}^{x=2\theta} \\
= \frac{n}{2^n \theta^n}  \cdot \frac{2^{n+1}\cdot \theta^{n+1}}{n+1} = \frac{n2\theta}{n+1}
\end{multline*}
Следовательно, $\E \left(\frac{n+1}{2n} \cdot X_{(n)}\right) = \theta$, а значит, $\tilde{\theta} = \frac{n+1}{2n} \cdot X_{(n)}$ – несмещённая оценка вида $c \cdot  X_{(n)}$
\item $\Var(\tilde{\theta}) = \frac{(n+1)^2}{4n^2} \Var(X_{(n)})$

\begin{multline*}
\E(X_{(n)}^2) = \int_{-\infty}^{+\infty} x^2 f_{X_{(n)}} (x) dx = \int_{0}^{2\theta} x^2 \frac{nx^{n-1}}{2^n \theta^n}  dx = \frac{n}{2^n \theta^n}  \int_{0}^{2\theta} x^{n+1} dx = \\
= \frac{n}{2^n \theta^n} \cdot \frac{x^{n+2}}{n+2} \mid_{x=0}^{x=2\theta} = \frac{n}{2^n \theta^n} \cdot  \frac{2^{n+2}\cdot \theta^{n+2}}{n+2} = \frac{n\cdot4\cdot\theta^2}{n+2}
\end{multline*}

\[
\Var(X_{(n)}) = \E(X_{(n)}^2)  - (\E(X_{(n)}))^2 = \frac{4n\theta^2}{n+2} - \frac{4 n^2 \cdot \theta^2}{(n+1)^2} = 4n\theta^2 \left(\frac{1}{n+2} - \frac{n}{(n+1)^2}\right)
\]

\[
\Var(\tilde{\theta}) = \frac{(n+1)^2}{4n^2} \Var(X_{(n)}) = \frac{(n+1)^2}{4n^2}  \cdot 4n\theta^2 \left(\frac{n^2+2n+1 - n^2-2n}{(n+2)(n+1)^2} \right) = \frac{\theta^2}{n(n+2)}
\]
Оценка $\tilde{\theta}_n$ является состоятельной, так как $\E(\tilde{\theta}_n) = \theta$ и $\Var(\tilde{\theta}_n) = \frac{\theta^2}{n(n+2)} \to_{n\to\infty} 0$
\item  Поскольку $\Var(\widehat{\theta}_n) = \frac{\theta^2}{3n}$, $\Var(\tilde{\theta}_n) = \frac{\theta^2}{n(n+2)}$ при достаточно большом $n$ $\Var(\tilde{\theta}_n) < \Var(\widehat{\theta}_n) $. Значит, при таких $n$ оценка $\tilde{\theta}_n$ будет более эффективной по сравнению с оценкой $\widehat{\theta}_n$.
\end{enumerate}

\item
\begin{enumerate}
\item $X_i \sim Bin (n=10, p)$
\item $L(p)  = \prod_{i=1}^{n} C_{10}^{x_i} p^{x_i} (1-p)^{10-x_i}$
\item $\ln L(p) = \sum_{i=1}^{n} \ln C_{10}^{x_i} + \sum_{i=1}^n x_i \ln p + \sum_{i=1}^{n} (10-x_i)\ln (1-p) \to \max_p$

$\frac{\partial \ln L}{\partial p} = \frac{\sum_{i=1}^n x_i}{p} - \frac{\sum_{i=1}^{n} (10-x_i)}{1-p} \mid_{p=\hat{p}} = 0 \Rightarrow \hat{p} = \frac{\overline{X}}{n} = \frac{\sum_{i=1}^{n} x_i}{10n}$

$\frac{\partial^2 \ln L}{\partial p^2} = -\frac{\sum_{i=1}^n x_i}{p^2} -  \frac{\sum_{i=1}^{n} (10-x_i)}{(1-p)^2}$

\item $I(p) = -\E \left(\frac{\partial^2 \ln L}{\partial p^2}  \right) = \E \left(\frac{\sum_{i=1}^n x_i}{p^2} + \frac{\sum_{i=1}^{n} (10-x_i)}{(1-p)^2}\right) = \frac{10np}{p^2} + \frac{10n - 10np}{(1-p)^2} = \frac{10n}{p(1-p)}$

$i(p) = \frac{I(p)}{n} = \frac{10}{p(1-p)}$

\item $\Var(T) \geq \frac{1}{ni(T)}$

\item $\Var(\hat{p}_{ML}) = \Var\left(\frac{\sum_{i=1}^{n} x_i}{10n}\right) = \frac{1}{(10n)^2} n \Var(X_i) = \frac{1}{100n}10p(1-p) = \frac{p(1-p)}{10n}$

$\frac{p(1-p)}{10n} = \frac{1}{\frac{10n}{p(1-p)}} \Rightarrow$ да

\item $\E(X_i) = 10p \Rightarrow \widehat{\E(X_i)} = 10 \hat{p}_{ML} = \overline{X}$

$\Var(X_i) = 10p(1-p) \Rightarrow \widehat{\Var(X_i)} = \overline{X}\left(1-\frac{\overline{X}}{10}\right)$

\item $\hat{p} = \frac{3+4+0+2+6}{10\cdot 5} = 0.3$
\end{enumerate}

\item $L(x, \theta) = \prod_{i=1}^{n} (1 + \theta) x_i^\theta = (1+\theta)^n \prod_{i=1}^n x_i^\theta \to \max_\theta$

$\ln L (x, \theta) = n\ln (1+\theta) + \theta\sum_{i=1}^{n} \ln x_i \to \max_\theta$

$\frac{\partial \ln L}{\partial \theta} = \frac{n}{1+\theta} + \sum_{i=1}^{n} \ln x_i \mid_{\theta=\hat{\theta}} = 0 \Rightarrow \hat{\theta}_{ML} = -\frac{1}{\sum_{i=1}^{n} \ln x_i} -1$

\item $\overline{X} - 1.96 \frac{7}{\sqrt{20}} < \mu <\overline{X} + 1.96 \frac{7}{\sqrt{20}} $
\end{enumerate}


\subsection{Контрольная работа 3. Брутальная часть. 1 апреля 2016}

Правила: 3 часа, всем можно пользоваться, интернетом тоже.

Все семь задач решать вовсе не обязательно, выбирайте любые пять! При самостоятельной работе можно всем пользоваться!!!! :)

\begin{enumerate}

\item Случайные величины $X_1$, \ldots, $X_n$ независимо и одинаково распределены с функцией плотности $f(x)=2ax\exp(-ax^2)$ при $x>0$.



По 100 наблюдениям известно, что $\sum X_i = 169.55$, $\sum X_i^2 = 351.48$.

\begin{enumerate}
\item Оцените параметр $a$ методом максимального правдоподобия.
\item Оцените дисперсию оценки $\hat a_{ML}$
\item Постройте 95\%-ый доверительный интервал для $a$ с помощью оценки максимального правдоподобия
\item Оцените параметр $a$ методом моментов
\item Оцените дисперсию оценки $\hat a_{MM}$
\item Постройте 95\%-ый доверительный интервал для $a$ с помощью оценки метода моментов
\end{enumerate}

\item Для того, чтобы люди давали правдивый ответ на деликатный вопрос (скажем, «Берёте ли Вы взятки?») при опросе используется рандомизация. Вопрос допускает всего два ответа «да» или «нет». Перед ответом респондент подбрасывает монетку, и только респондент видит результат подбрасывания. Если монетка выпадет «орлом», то респондент отвечает правду. Если «решкой», то респондент отвечает наоборот («да» вместо «нет» и «нет» вместо «да»).

Монетка выпадает орлом с вероятностью $0.4$. Из 500 опрошенных 300 ответили «да».

\begin{enumerate}
\item Какова вероятность того, что человек берёт взятки, если он ответил «да» в анкете?
\item Постройте оценку для доли людей берущих взятки
\item Постройте 95\%-ый доверительный интервал для доли людей берущих взятки
\end{enumerate}

\item Винни-Пух хочет измерить высоту Большого дуба, $d$. Для этого Винни-Пух три раза в случайное время дня измерил длину тени Большого Дуба:

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{verbatim}
## [1]  8.9 13.2 25.2
\end{verbatim}
\end{kframe}
\end{knitrout}

Предположим, что в дни измерений траектория движения Солнца проходила ровно через зенит :)

\begin{enumerate}
\item Найдите функцию плотности длины тени
\item Если возможно, постройте оценку метода моментов
\item Если возможно, постройте оценку метода максимального правдоподобия
\item Где живёт Винни-Пух и какого числа 2016 года он проводил измерения?
\end{enumerate}

\item Встроенный в \verb|R| набор данных \verb|morley| содержит результаты 100 опытов Майкельсона и Морли. В 1887 году они проводили измерения скорости света, чтобы понять, зависит ли она от направления.

\begin{enumerate}
\item Постройте 95\%-ый доверительный интервал для скорости света
\item Выпишите использованные формулы и алгоритм построения интервала
\item Чётко сформулируйте все гипотезы при которых данный алгоритм даёт корректный результат
\item Накрывает ли построенный доверительный интервал фактическую скорость света?
\end{enumerate}

Полезные команды: \verb|morley|, \verb|help("morley")|, \verb|mean|, \verb|sd|, \verb|qnorm|, \verb|pnorm|



\item  Исследователь Вениамин дрожащей от волнения рукой рисует прямоугольники размера $a\times b$. Поскольку Вениамин очень волнуется прямоугольники де-факто выходят со случайными сторонами $a+u_i$ и $b+v_i$. Случайные ошибки $u_i$ и $v_i$ независимы и одинаково распределены $N(0;1)$.




Вениамин нарисовал 400 прямоугольничков и посчитал очень аккуратно площадь каждого. Оказалась, что средняя площадь равна $1198.34$ см$^2$, а выборочное стандартное отклонение площади — $52.83$ см$^2$. Вениамин считает, что зная только площади прямоугольничков невозможно оценить оценить каждую из сторон.

Если возможно, то оцените параметры $a$ и $b$ подходящим методом. Если невозможно, то докажите.


\item На поле $D4$ шахматной доски стоит конь. Ли Седоль переставляет коня наугад, выбирая каждый возможный ход равновероятно.

Сколько в среднем пройдет ходов прежде чем Ли Седоль снова вернёт коня на $D4$?



\item В «Киллер» играли $n$ человек. После окончания игры, когда были убиты все, кто может быть убит, встретились два игрока (возможно убитых) и оказалось, что один убил 5 человек, а другой — 7 человек.

Оцените $n$ подходящим методом
\end{enumerate}


\subsection{Контрольная 4, 09.06.2016}

\begin{enumerate}
\item	Сформулируйте определения несмещённости, состоятельности и эффективности оценок.

\item На курсе учится 250 человек. Предположим, что число студентов, не явившихся на экзамен, хорошо описывается законом Пуассона.
\begin{enumerate}
\item	Методом максимального правдоподобия найдите оценку параметра распределения Пуассона.
\item	Проверьте выполнение свойств несмещенности, эффективности и состоятельности для данной оценки.
\item	Найдите оценку максимального правдоподобия для вероятности стопроцентной явки студентов на экзамен.
\item	Используя дельта-метод, постройте для этой вероятности асимптотический доверительный интервал.
\end{enumerate}

\item	Фармацевтическая компания выпустила новое лекарство от бессонницы, утверждая, что оно помогает 80\% людей, страдающих бессонницей. Чтобы проверить утверждение компании, случайным образом выбираются 20 человек, страдающих бессонницей. Обозначим за $Y$ количество человек из выборки, которым лекарство помогло. Основная гипотеза, $H_0$: $p=0.8$, альтернативная гипотеза $H_a$: $p=0.6$. Критическая область: $\{Y<12\}$.
\begin{enumerate}
\item	В терминах этой задачи сформулируйте, что является ошибкой первого рода.
Найдите уровень значимости, соответствующий заданной критической области.
\item	В терминах этой задачи сформулируйте, что является ошибкой второго рода.
Найдите вероятность ошибки второго рода.
\item	Найдите такое значение $c$, что вероятность ошибки первого рода $\alpha \approx 0.1$ при критической области вида $\{Y<c\}$. Найдите соответствующее значение вероятности ошибки второго рода.
\item	Каким должен быть размер выборки, чтобы выборочная доля страдающих бессонницей отличалась от истинной вероятности не более, чем на 0.01 с вероятностью не менее, чем 0.95?
\end{enumerate}

\item	Вася Сидоров утверждает, что ходит в кино в два раза чаще, чем на лекции по статистике, на лекции по статистике в два раза чаще, чем в спортзал. За последние полгода он 10 раз был в спортзале, 1 раз — на лекциях по статистике и 39 раз в кино.

При помощи критерия хи-квадрат Пирсона на уровне значимости $0.05$ проверьте, правдоподобно ли Васино утверждение.

\item У Евдокла есть случайная выборка из экспоненциального распределения с неизвестным параметром $\lambda$ в 50 наблюдений, $X_1$, $X_2$, \ldots, $X_{50}$. Оказалось, что $\bar X = 1.1$. Евдокл хочет проверить гипотезу о равенстве $\lambda = 1$ против альтернативной гипотезы о неравенстве $\lambda \neq 1$ на уровне значимости $0.1$.

Помогите Евдоклу и проверьте гипотезу с помощью критерия отношения правдоподобия.

Пачка логарифмов: $\ln 50 \approx 3.9$, $\ln 55 \approx 4.0$, $\ln 11 \approx 2.4$, $\ln 60 \approx 4.1$, $\ln 12 \approx 2.5$


\item Американский демографический журнал опубликовал исследование, в котором утверждается, что посетители крупных торговых центров за одно посещение тратят  в выходные дни больше, чем в будние. Наибольшие расходы приходятся на воскресенье в период с 4 до 6 часов вечера. Для двух независимых выборок посетителей средние расходы и выборочные стандартные отклонения расходов составили

\begin{tabular}{lrr}
\toprule
 & Выходные & Рабочие дни \\
\midrule
Число наблюдений & 21 & 19 \\
Средние расходы (\$) & 78 & 67 \\
Выборочное стандартное отклонение (\$) & 22 & 20 \\
\bottomrule
\end{tabular}


\begin{enumerate}
\item Проверьте гипотезу о равенстве дисперсий расходов
\item Предполагая, что дисперсии расходов одинаковы, проверьте гипотезу об отсутствии разницы в расходах в выходные и будние дни.
\item Сформулируйте все необходимые для проверки гипотез предыдущих пунктов предпосылки.
\end{enumerate}



\item Винни Пух знает, что пчёлы и мёд бывают правильные и неправильные. По результатам 100~попыток добыть мёд Винни Пух составил таблицу сопряженности признаков.


\begin{tabular}{lrr}
\toprule
 & Мёд правильный & Мёд неправильный \\
\midrule
Пчёлы правильные & 12	& 36 \\
Пчёлы неправильные & 32	& 20 \\
\bottomrule
\end{tabular}


На уровне значимости $0.05$ проверьте гипотезу о независимости характеристик пчёл и мёда.


\begin{figure}[b]
\centering
\includegraphics[width=9cm]{images/winnie_kr_4}
\end{figure}



\end{enumerate}


\subsection{Контрольная 4, решения}

\begin{enumerate}

	\item[4.] $H_0: p_{\text{c}} = \frac{1}{7}, p_{\text{л}} = \frac{2}{7}, p_{\text{к}} = \frac{4}{7}$

	$Q = \sum_{i=1}^{s=3} \frac{(\nu_i - np_i)^2}{np_i} \sim \chi^2_{s-k-1} = \chi^2_2$

	$Q_{obs} = \frac{\left(10-70\frac{1}{7}\right)^2}{70\frac{1}{7}} + \frac{\left(1-70\frac{2}{7}\right)^2}{70\frac{2}{7}} + \frac{\left(39-70\frac{4}{7}\right)^2}{70\frac{4}{7}} = 18.075$

	$Q_{crit} = 5.99$, $Q_{crit} < Q_{obs} \Rightarrow$ гипотеза отвергается

	\item[5.] $LR \sim \chi^2_1$, так как основная гипотеза содержит одно уравнение

	$L(x, \lambda) = \prod_{i=1}^{n=50} \lambda e^{-\lambda x} = \lambda^{50} e^{-\lambda \sum_{i=1}^{n=50} x_i}$

	$\ln L (x, \lambda) = 50\ln\lambda - \lambda \sum_{i=1}^{n=50} x_i \to \max_\lambda$

	$\frac{\partial \ln L}{\partial \lambda} = \frac{50}{\lambda} - \sum_{i=1}^{n=50} x_i \mid_{\lambda=\hat{\lambda}} = 0 \Rightarrow \hat{\lambda}_{ML} = \frac{1}{\overline{X}} = \frac{10}{11}$

	При верной $H_0:  \lambda=1$, тогда $\ln L (\lambda=1) = 50 \ln 1 - 1 \cdot 1.1 \cdot 50 = -55$

	При верной $H_1: \lambda=\lambda_{ML}$, тогда $\ln L \left(\lambda=\frac{10}{11}\right) = 50 \ln \frac{10}{11} - \frac{10}{11} \cdot 50 \cdot 1.1 = -54.77$

	$LR_{obs} = 2(\ln L (H_1) - \ln(H_0)) = 2(-54.77- (-55)) = 0.46$

	$LR_{crit} = 2.71$, $LR_{crit} > LR_{obs} \Rightarrow$ оснований отвергать $H_0$ нет

	\item[6.]  Будем проверять гипотезы на уровне значимости $0.05$
		\begin{enumerate}
			\item $\hat{\sigma}^2_{\text{в}} = 484$, $\hat{\sigma}^2_{\text{р}} = 400$

				$\frac{\hat{\sigma}^2_{\text{в}} }{\hat{\sigma}^2_{\text{р}}} \sim F_{21-1 , 19-1}$

				$F_{obs} = \frac{484}{400} = 1.21$, $F_{crit, left} = 0.4$, $F_{crit, right} = 2.6  \Rightarrow$ оснований отвергать $H_0$ нет

			\item $\hat{\sigma}_0^2 = \frac{22\cdot (21-1) + 20 \cdot (19-1)}{21 + 19 - 2} \approx 21$

			$t_{obs} = \frac{78-67}{\sqrt{21} \sqrt{\frac{1}{21}+ \frac{1}{21}}} \approx 7.8 $

			$t_{crit}  \sim t_{21+19-2} = t_{38}$, $t_{crit} = \pm 2.02 \Rightarrow$ гипотеза отвергается
		\end{enumerate}

	\item[7.] $\gamma = \sum_{i=1}^s \sum_{j=1}^m \frac{\left(n_{ij} - \frac{n_{i\cdot}n_{\cdot j}}{n}\right)^2}{\frac{n_{i\cdot}n_{\cdot j}}{n}} \sim \chi^2_{(s-1)(m-1)}$

	$\gamma_{obs} = \frac{\left(12-\frac{44\cdot48}{100}\right)^2}{\frac{44\cdot48}{100}} + \frac{\left(36-\frac{56\cdot48}{100}\right)^2}{\frac{56\cdot48}{100}} + \frac{\left(32-\frac{44\cdot52}{100}\right)^2}{\frac{44\cdot52}{100}} + \frac{\left(20-\frac{50\cdot52}{100}\right)^2}{\frac{50\cdot52}{100}} \approx 12$

	$\gamma_{criit} = 3.84 \Rightarrow$  гипотеза отвергается

\end{enumerate}


\subsection{Экзамен, 20.06.2016}

\input{tests/2015_final}

\AMCnumero{1} % сбрасываем номер вопроса на 1
\cleargroup{all}
\copygroup[6]{prob_one_sample}{all}
\copygroup[6]{prob_two_samples}{all}
\copygroup[6]{prob_sample_char}{all}
\copygroup[6]{prob_estimators}{all}
\copygroup[6]{prob_ml_mm}{all}
\insertgroup{all}

\section{2016-2017}

\input{chapters/year_2016_2017.tex}

\section{2017-2018}

\input{chapters/year_2017_2018.tex}

\end{document}
